<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="box box-info">
	<div class="box-body">
		<form method="post" id="frm">
			<div class="table-responsive">
				<table id="tbper" class="table table-bordered table-hover" style="width:800px">
					<thead align="center">
						<tr>
							<th>Keterangan</th>
							<th>Jadwal Lama</th>
							<th>Jadwal Baru</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->listJadwal as $data){ ?>
						<tr>
							<td>Periode Akademik</td>
							<td><?php echo $data['kd_periode'] ?></td>
							<td><input type="hidden" id="per" value="<?php echo $data['kd_periode'] ?>"><?php echo $data['kd_periode'] ?></td>
						</tr>
						<tr>
							<td>Nama Kelas</td>
							<td><?php echo $data['nm_kelas'] ?></td>
							<td><input type="hidden" id="paket" value="<?php echo $data['kd_paket_kelas'] ?>"><?php echo $data['nm_kelas'] ?></td>
						</tr>
						<tr>
							<td>Dosen</td>
							<td><?php echo $data['nm_dosen'] ?></td>
							<td><?php echo $data['nm_dosen'] ?></td>
						</tr>
						<tr>
							<td>Mata Kuliah</td>
							<td><?php echo $data['nm_mk'] ?></td>
							<td><?php echo $data['nm_mk'] ?></td>
						</tr>
						<tr>
							<td>Hari</td>
							<td><input type="hidden" id="old_hr" value="<?php echo $data['id_hari'] ?>"><?php echo $data['nm_hari'] ?></td>
							<td>
								<select id="new_hr" class="form-control">
									<?php foreach ($this->listHari as $dataHari){ ?>
									<option value="<?php echo $dataHari['id_hari'] ?>"><?php echo $dataHari['nm_hari'] ?></option>
									<?php }?>
								</select>
							</td>
						</tr>
						<tr>
							<td>Waktu(Slot)</td>
							<td><input type="hidden" id="old_sl" value="<?php echo $data['id_slot'] ?>"><?php echo $data['start_time']." s/d ".$data['end_time'] ?></td>
							<td>
								<input type="text" id="new_sl" style="display:none;">
								<input type="text" class="form-control" id="slot" placeholder="Klik untuk memilih slot jadwal" readonly onclick="hbox('<?php echo $this->baseUrl;?>','helper/slot',new Array('new_sl','slot'))">
							</td>
						</tr>
						<tr>
							<td>Ruangan</td>
							<td><input type="hidden" id="old_ro" value="<?php echo $data['kd_ruangan'] ?>"><?php echo $data['nm_ruangan'] ?></td>
							<td>
								<input type="text" id="new_ro" style="display:none;">
								<input type="text" class="form-control" id="nm_room" placeholder="Klik untuk memilih ruangan" readonly onclick="hbox('<?php echo $this->baseUrl;?>','helper/ruangan',new Array('new_ro','nm_room'))">
							</td>
						</tr>
						<tr>
							<td colspan="3" align="center">
								<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan</button>
								<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	 ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax2/updjdwl","/jadwal/list?id=<?php echo $data['kd_periode'];?>&new=","u");
	  return false;
	});
</script>
<?php } ?>