<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="nav-tabs-custom">
	<ul class="nav nav-tabs">
		<?php $i=1;foreach ($this->listHari as $dataHari){ ?>
		<?php if($i==$this->tab){$active="active";}else{$active="";}?>
		<li class="<?php echo $active;?>"><a href="#tab_<?php echo $dataHari['nm_hari'] ?>" data-toggle="tab"><?php echo $dataHari['nm_hari'] ?></a></li>
		<?php $i++;} ?>
	</ul>
	<div class="tab-content">
		<?php $i=1;foreach ($this->listHari as $dataHari){ ?>
		<?php if($i==$this->tab){$active="active";}else{$active="";}?>
		<div class="tab-pane <?php echo $active;?>" id="tab_<?php echo $dataHari['nm_hari'] ?>">
			<strong>JADWAL PERKULIAHAN HARI <?php echo $dataHari['nm_hari'] ?></strong>
			<form class="form-horizontal" method="post" id="frm<?php echo $i;?>">
				<div class="box-body">
					<div class="col-md-6">
						<div class="form-group">
							<label class="col-sm-4 control-label">Program Studi</label>
							<div class="col-sm-8">
								<input type="text" id="kd_pkt_<?php echo $i;?>" style="display:none;">
								<input type="hidden" id="per_<?php echo $i;?>" value="<?php echo $this->per;?>">
								<input type="hidden" id="id_hari_<?php echo $i;?>" value="<?php echo $dataHari['id_hari'];?>">
								<select id="prd_<?php echo $i;?>" class="form-control">
									<option disabled selected value="">pilih program studi</option>
									<?php foreach ($this->listProdi as $dataProdi) { ?>
									<option value="<?php echo $dataProdi['kd_prodi'] ?>"><?php echo $dataProdi['nm_prodi']; ?></option>
									<?php } ?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label">Nama Kelas</label>
							<div class="col-sm-8">
								<input type="text" class="form-control" id="nm_mk_<?php echo $i;?>" placeholder="Klik untuk memilih paket kelas dari prodi di atas" readonly onclick="hbox('<?php echo $this->baseUrl;?>','helper/paketkelas',new Array('kd_pkt_<?php echo $i;?>','nm_mk_<?php echo $i;?>','dsn_<?php echo $i;?>','mk_<?php echo $i;?>'),new Array('per_<?php echo $i;?>','prd_<?php echo $i;?>'))">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label">Dosen</label>
							<div class="col-sm-8">
								<input type="text" class="form-control" id="dsn_<?php echo $i;?>" placeholder="terisi otomatis dari pilihan paket kelas" readonly>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label class="col-sm-4 control-label">Mata Kuliah</label>
							<div class="col-sm-8">
								<input type="text" class="form-control" id="mk_<?php echo $i;?>" placeholder="terisi otomatis dari pilihan paket kelas" readonly>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label">Ruangan</label>
							<div class="col-sm-8">
								<input type="text" id="id_room_<?php echo $i;?>" style="display:none;">
								<input type="text" class="form-control" id="nm_room_<?php echo $i;?>" placeholder="Klik untuk memilih ruangan" readonly onclick="hbox('<?php echo $this->baseUrl;?>','helper/ruangan',new Array('id_room_<?php echo $i;?>','nm_room_<?php echo $i;?>'))">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label"> SlotJadwal</label>
							<div class="col-sm-8">
								<input type="text" id="id_slot_<?php echo $i;?>" style="display:none;">
								<input type="text" class="form-control" id="slot_<?php echo $i;?>" placeholder="Klik untuk memilih slot jadwal" readonly onclick="hbox('<?php echo $this->baseUrl;?>','helper/slot',new Array('id_slot_<?php echo $i;?>','slot_<?php echo $i;?>'))">
							</div>
						</div>
					</div>
				</div>
				<div class="box-body">
					<div class="box-footer col-sm-6">
						<button type="submit" class="btn btn-primary pull-right col-sm-4" sb value="<?php echo $i;?>">Tambah</button>
					</div>
					<div class="box-footer col-sm-6">
						<button type="reset" class="btn btn-default pull-left col-sm-4">Reset</button>
					</div>
				</div>
			</form>
			<div class="table-responsive">
				<table id="tbjdwl_<?php echo $i;?>" class="table table-bordered table-hover">
					<thead>
						<tr>
							<th width="12%">Slot Waktu</th>
							<th>Ruangan</th>
							<th>Kelas</th>
							<th>Dosen</th>
							<th>Kode MK</th>
							<th>Nama MK</th>
							<th>Prodi</th>
							<th width="7%">Aksi</th>
						</tr>
					</thead>
					<tbody>
					<?php foreach ($this->listJadwal as $dataJadwal){ ?>
					<?php if($dataJadwal['id_hari']==$dataHari['id_hari']){ ?>
					<tr>
						<td><?php echo $dataJadwal['start_time']." s/d ".$dataJadwal['end_time'];?></td>
						<td><?php echo $dataJadwal['nm_ruangan'];?></td>
						<td><?php echo $dataJadwal['nm_kelas'];?></td>
						<td><?php echo $dataJadwal['nm_dosen'];?></td>
						<td><?php echo $dataJadwal['kode_mk'];?></td>
						<td><?php echo $dataJadwal['nm_mk'];?></td>
						<td><?php echo $dataJadwal['nm_prodi_kur'];?></td>
						<td align="center">
							<button type="button" class="btn btn-warning btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/jadwal/edit?hr=<?php echo $dataJadwal['id_hari'];?>&sl=<?php echo $dataJadwal['id_slot'];?>&ro=<?php echo $dataJadwal['kd_ruangan'];?>&per=<?php echo $this->per;?>')"><i class="fa fa-retweet"></i></button>
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah anda yakin ingin menghapus jadwal kuliah ini?<br>Kelas : <?php echo $dataJadwal['nm_kelas'];?><br>Dosen : <?php echo str_replace("'","\'",$dataJadwal['nm_dosen']);?><br>Mata Kuliah : <?php echo str_replace("'","\'",$dataJadwal['nm_mk']);?>','<?php echo $this->baseUrl;?>','/ajax2/deljdwl', new Array('<?php echo $this->per;?>','<?php echo $dataJadwal['id_hari']?>','<?php echo $dataJadwal['id_slot']?>','<?php echo $dataJadwal['kd_ruangan']?>'))"><i class="fa fa-remove"></i></button>
						</td>
					</tr>
					<?php }?>
					<?php }?>
					</tbody>	
				</table>
			</div>
		</div>
		<?php $i++;} ?>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("[sb]").on('click',(function() {
	 x=$(this).val();
	 ajaxSubmit("frm"+x,"<?php echo $this->baseUrl;?>","/ajax2/insjdwl?frm="+x,"/jadwal/list?id=<?php echo $this->per;?>&tab="+x+"&new=","u");
	  return false;
	}));
</script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>
	$(function () {
		for(i=1;i<=7;i++){
			tabel('tbjdwl_'+i,true,true,true,true,true,false);
		}
	});
</script>