<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/plugins/morris/morris.css">
<?php //echo $this->x;?>
<?php if(!$this->chart){?>
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Filter </h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">FILTER : PERIODE</label>
				<input type="hidden" id="cht" value="b">
				<div class="col-sm-4">
					<select id="per" class="form-control data-placeholder="pilih periode akademik" name="per">
						<?php foreach ($this->listPeriode as $dataPeriode) { ?>
						<option value="<?php echo $dataPeriode['kd_periode']; ?>"><?php echo $dataPeriode['kd_periode']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="submit" class="btn btn-info pull-right col-sm-2">Show</button>
			</div>
		</div>
	</form>
</div>
<?php }else{ ?>
<div class="box box-success">
	<div class="box-header with-border">
		<h3 class="box-title">Report Chart Jadwal Kuliah</h3>
		<div class="box-tools pull-right">
			<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		</div>
		<div class="box-body chart-responsive">
			<div class="chart" id="cht_jdw" style="height: 500px;"></div>
		</div>
	</div>
</div>
<?php } ?>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
	    ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax5/showjdwcht","/jadwal/report","s");
	    return false;
	  });
	});
</script>
<script src="<?php echo $this->baseUrl;?>/public/plugins/morris/raphael.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/plugins/morris/morris.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/plugins/morris/html2canvas.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/js/chart.js"></script>
<script>
	$(function () {
		chart('cht_jdw','<?php echo $this->chart;?>',<?php echo json_encode($this->key);?>,<?php echo json_encode($this->labels);?>,<?php echo json_encode($this->data);?>);
	});
</script>