<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Verifikator</h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">Perihal</label>
				<div class="col-sm-4">
					<input type="hidden" id="id_mk_kur" value="<?php echo $this->id_mk_kur;?>">
					<input type="text" class="form-control" id="hal" placeholder="perihal">
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Bagian/Sistem</label>
				<div class="col-sm-4">
					<select class="form-control" id="bags">
						<option value="Akademik|SIA">Akademik/SIA</option>
						<option value="Keuangan|SIK">Keuangan/SIK</option>
						<option value="Laboratorium|LAB">Laboratorium/LAB</option>
						<option value="Perpustakaan|SIP">Perpustakaan/LIB</option>
						<option value="Portofolio|SIA">Portofolio/SIA</option>
						<option value="Prodi|SIA">Prodi/SIA</option>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
				<button type="submit" class="btn btn-primary pull-right col-sm-2">Tambah</button>
			</div>
		</div>
	</form>
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbakt" class="table table-bordered table-hover">
				<thead align="center">
					<tr>
						<th width="5%">NO</th>
						<th>PERIHAL</th>
						<th width="25%">BAGIAN/SISTEM</th>
						<th width="5%">AKSI</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listMkApp as $data) { ?>
					<tr>
						<td><?php echo $i; ?></td>
						<td><?php echo $data['perihal']; ?></td>
						<td><?php echo $data['bagian']."/".$data['sistem']; ?></td>
						<td align="center">
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan menghapus data ini ? <strong><?php echo $data['perihal'];?></strong>','<?php echo $this->baseUrl;?>','/ajax3/delapproverta',new Array('<?php echo $data['id_matkul_ta_approver'];?>'))"><i class="fa fa-remove"></i></button>
						</td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<!-- DataTables -->
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbakt',true,true,true,true,true,false);});</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax3/insapproverta","/ajarta/approverta?id=<?php echo $this->id_mk_kur;?>&new=","u");
	  return false;
	});
</script>