<?=$this->doctype() ?>
<!DOCTYPE html>
<?php $param = new Zend_Session_Namespace('ses_ac');$tpl=$param->tpl;?>
<html>
	<head>
		<meta charset=utf-8>
		<meta http-equiv=X-UA-Compatible content="IE=edge">
		<title>SIAkademik | <?php echo strtoupper($this->title);?></title>
		<link rel="shortcut icon" href=<?php echo $this->baseUrl;?>/image/png?url=public/img/logo.png>
		<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name=viewport>
		<link rel=stylesheet href=<?php echo $this->baseUrl;?>/public/bootstrap/css/bootstrap.min.css>
		<link rel=stylesheet href=<?php echo $this->baseUrl;?>/public/dist/css/AdminLTE.min.css>
		<link rel=stylesheet href=<?php echo $this->baseUrl;?>/public/dist/css/skins/skin-<?php echo $tpl;?>.min.css>
		<link rel=stylesheet href=<?php echo $this->baseUrl;?>/public/dist/font-awesome/css/font-awesome.min.css>
		<link rel=stylesheet href=<?php echo $this->baseUrl;?>/public/dist/ionicons/css/ionicons.min.css>
	</head>
	<body class="hold-transition skin-<?php echo $tpl;?> fixed sidebar-mini sidebar-collapse">
		<script src=<?php echo $this->baseUrl?>/public/plugins/jQuery/jQuery-2.2.0.min.js></script>
		<script src=<?php echo $this->baseUrl?>/public/bootstrap/js/bootstrap.min.js></script>
		<script src=<?php echo $this->baseUrl?>/public/dist/js/app.min.js></script>
		<div class=wrapper>
		<header class=main-header>
			<a href=<?php echo $this->baseUrl?>/home class=logo>
			<span class=logo-mini><img src=<?php echo $this->baseUrl;?>/image/png?url=public/img/logo.png width=45px></span>
			<span class=logo-lg><img src=<?php echo $this->baseUrl;?>/image/png?url=public/img/logo.png width=45px>&nbsp;&nbsp;<strong>Akademik</strong></span>
			</a>
			<nav class="navbar navbar-static-top" role=navigation>
				<a href=# class=sidebar-toggle data-toggle=offcanvas role=button>
				<span class=sr-only>Toggle navigation</span>
				</a>
				<div class=navbar-custom-menu>
					<ul class="nav navbar-nav">
						<li class="dropdown user user-menu">
							<a href=# class=dropdown-toggle data-toggle=dropdown>
							<img src=<?php echo $this->baseUrl;?>/public/dist/img/avatar5.png class=user-image alt="User Image">
							<span class=hidden-xs><?php echo $this->namauser;?></span>
							</a>
							<ul class=dropdown-menu>
								<li class=user-header>
									<img src=<?php echo $this->baseUrl;?>/public/dist/img/avatar5.png class=img-circle alt="User Image">
									<p>
										<?php echo $this->namauser;?>
										<small><?php echo $this->nm_pt." (".$this->kd_pt.")"; ?></small>
									</p>
								</li>
								<li class="user-body">
									<div class="row">
										<div class="col-xs-4 text-center">
											<a href=<?php echo $this->baseUrl;?>/profile>Profile</a>
					                  	</div>
					                  	<div class="col-xs-4 text-center">
					                    	<a href="#">Message</a>
					                  	</div>
					                  	<div class="col-xs-4 text-center">
					                    	<a href=<?php echo $this->baseUrl;?>/profile/akses >Akses</a>
					                  	</div>
					                </div>
					            </li>
								<li class=user-footer>
									<div class=pull-left>
										<a href=# class="btn btn-default btn-flat"><i class="fa fa-question-circle"></i> Help</a>
									</div>
									<div class=pull-right>
										<a href=<?php echo $this->baseUrl;?>/logout class="btn btn-default btn-flat">Sign out <i class="fa  fa-sign-out"></i></a>
									</div>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</nav>
		</header>
		<aside class=main-sidebar>
			<section class=sidebar>
				<div class=user-panel>
					<div class="pull-left image">
						<img src="<?php echo $this->baseUrl;?>/public/dist/img/avatar5.png" class=img-circle alt="User Image">
					</div>
					<div class="pull-left info">
						<p><?php echo $this->namauser;?></p>
						<a><i class="fa fa-calendar text-success"></i><?php echo date("d M Y")?></a>
					</div>
				</div>
				<ul class=sidebar-menu>
					<li class=header>Menu :</li>
					<?php if ($this->menu!="F"){?>
					<?php $menu = $this->menu;?>
					<?php $header = "";$i=0;$active=array();?>
					<?php foreach ($menu as $menuHeader){?>
					<?php $arrMenuHeader = explode('|', $menuHeader);?>
					<?php if (($header != $arrMenuHeader[2])){?>
					<?php 
						if($this->active_tree==$arrMenuHeader[4]){
							$active[$i]="active";
						}else{
							$active[$i]="";
						}
					?>
					<li class="treeview <?php echo $active[$i];?>" >
						<a href=#>
						<i class="fa fa-<?php echo $arrMenuHeader[3];?>"></i>
						<span><?php echo $arrMenuHeader[2];?></span>
						<i class="fa fa-angle-left pull-right"></i>
						</a>
						<ul class=treeview-menu>
							<?php $j=0;$active_menu=array();?>
							<?php foreach ($menu as $menuDetil){?>
							<?php $arrMenuDetil = explode('|', $menuDetil);?>
							<?php if (($arrMenuHeader[2]==$arrMenuDetil[2])&&($arrMenuDetil[1]!="")){?>
							<?php 
								if($this->active_menu==$arrMenuDetil[0]){
									$active_menu[$i][$j]="active";
								}else{
									$active_menu[$i][$j]="";
								}
							?>
							<li class="<?php echo $active_menu[$i][$j];?>" ><a href=<?php echo $this->baseUrl?>/<?php echo $arrMenuDetil[0]?>><i class="fa fa-caret-right"></i><?php echo $arrMenuDetil[1]?></a></li>
							<?php }?>
							<?php $j++;}?>
						</ul>
					</li>
					<?php }?>
					<?php $header = $arrMenuHeader[2];?>
					<?php $i++;}?>
					<?php }?>
					</li>
				</ul>
			</section>
		</aside>
		<div class=content-wrapper>
		<nav class="navbar navbar-default">
			<div class=container-fluid>
				<div class="navbar-nav navbar-right">
					<h4 class=navbar-text>&nbsp;&nbsp;<?php echo strtoupper($this->title); ?>&nbsp;&nbsp;</h4>
				</div>
				<div class="navbar-nav navbar-left">
					&nbsp;
					<button class="btn btn-primary btn-sm navbar-btn" onclick="nav('<?php echo $this->baseUrl; ?>/<?php echo $this->lback;?>')" <?php echo $this->bdis;?>><i class="fa fa-backward"></i>&nbsp;&nbsp;Back</button>
					<button class="btn btn-primary btn-sm" onclick="nav('<?php echo $this->baseUrl; ?>/<?php echo $this->llist;?>')" <?php echo $this->ldis;?>><i class="fa fa-list"></i>&nbsp;&nbsp;List</button>
					<button class="btn btn-primary btn-sm" onclick="nav('<?php echo $this->baseUrl; ?>/<?php echo $this->lnew;?>')" <?php echo $this->ndis;?>><i class="fa fa-plus"></i>&nbsp;&nbsp;New</button>
					<button class="btn btn-primary btn-sm" onclick="nav('<?php echo $this->baseUrl; ?>/<?php echo $this->lexport;?>')" <?php echo $this->edis;?>><i class="fa fa-file-o"></i>&nbsp;&nbsp;Export</button>
					<button class="btn btn-primary btn-sm" onclick="nav('<?php echo $this->baseUrl; ?>/<?php echo $this->limport;?>')" <?php echo $this->idis;?>><i class="fa fa-upload"></i>&nbsp;&nbsp;Upload</button>
				</div>
			</div>
		</nav>
		<section class=content style=padding-top:0px>
		<div class="modal fade" id=myModal tabindex=-1 role=dialog aria-labelledby=myModalLabel aria-hidden=true>
			<div class=modal-dialog>
				<div class=modal-content>
					<div class=modal-header>
						<h4>Halaman <?php echo $this->title; ?></h4>
					</div>
					<div class=modal-body></div>
					<div class=modal-footer>
						<button type=button id=btC class="btn btn-default" data-dismiss=modal>Close</button>
					</div>
				</div>
			</div>
		</div>