<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Data Diskusi</h3>
</div>
<div class="inqbox-content">
	<div class="panel panel-primary">
		<div class="panel-body">
			<div class="col-sm-2">Minggu</div>
			<div class="col-sm-10">: <?php echo $this->minggu;?></div>
			<div class="col-sm-2">Diterbitkan</div>
			<div class="col-sm-10">: <?php echo $this->tgl1;?></div>
			<div class="col-sm-2">Deadline</div>
			<div class="col-sm-10">: <?php echo $this->tgl2;?></div>
			<div class="col-sm-2">Kontributor</div>
			<div class="col-sm-10">: <?php echo $this->nm_dosen;?></div>
		</div>
	</div>
	<div class="panel panel-primary">
		<div class="panel-body">
			<h3><?php echo $this->jdl;?></h3>
			<div class="col-sm-12"><strong>Materi Diskusi :</strong><br><?php echo $this->knt;?></div>
		</div>
	</div>
	<?php if($this->allowInput!=1){?>
	<h5 class="alert alert-danger"><i class="icon fa fa-warning"></i>&nbsp;&nbsp;Anda tidak dapat mengentri/mengubah nilai di luar jadwal entri nilai. Silakan hubungi Administrator!</h5>
	<?php } ?>
	<div class="table-responsive">
	<form class="form-horizontal" method="post" id="frm">
		<?php if($this->allowInput==1){?>
		<div class="box-header col-sm-12">
			<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan Nilai</button>
			<br><br><br>
		</div>
		<?php } ?>
		<table id="tbkls" class="table table-bordered table-hover">
			<thead align="center">
				<tr>
					<th>RESPON</th>
					<th width="10%">NILAI</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=1;$n=0;foreach ($this->listDiskusiMhs as $dataDisk) { ?>
				<tr>
					<td>	<strong><?php echo $dataDisk['nm_mhs']." (".$dataDisk['nim'].")"; ?></strong><br><br>
						<?php echo $dataDisk['respon']; ?><br><br>
						<i><small><?php echo $dataDisk['created']; ?></small></i>
					</td>
					<td align="center">
						<?php if($this->allowInput!=1){?>
						<?php echo number_format($dataDisk['nilai'],2,',','.'); ?>
						<?php }else{ ?>
						<input type="hidden" id="id_disk_mhs_<?php echo $n;?>" value="<?php echo $dataDisk['id_diskusi_mhs'];?>">
						<input type="number" class="form-control" id="nl_<?php echo $n;?>" placeholder="0.00" value="<?php echo $dataDisk['nilai'];?>">
						<?php } ?>
					</td>
				</tr>
				<?php $i++; $n++;} ?>
				<input type="hidden" id="n" value="<?php echo $n;?>">
		</table>
		<?php if($this->allowInput==1){?>
		<div class="box-footer col-sm-12">
			<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan Nilai</button>
		</div>
		<?php } ?>
	</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/updnldiskusi","/diskusi/detil?id=<?php echo $this->id_diskusi;?>&new=","u");
	  return false;
});
</script>