<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/css/plugins/chosen/chosen.css">
<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Filter </h3>
</div>
<form class="form-horizontal" method="post" id="frm">
	<div class="inqbox-content col-sm-12">
		<div class="form-group">
			<label class="col-sm-2 control-label">Angkatan</label>
			<div class="col-sm-4">
				<select id="akt" class="form-control chosen-select" multiple="multiple" data-placeholder="pilih angkatan" name="akt" sel-2>
					<?php foreach ($this->listAkt as $dataAngkatan) { ?>
					<option value="<?php echo $dataAngkatan['id_angkatan']; ?>"><?php echo $dataAngkatan['id_angkatan']; ?></option>
					<?php } ?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">Program Studi</label>
			<div class="col-sm-4">
				<select id="prd" class="form-control chosen-select" multiple="multiple" data-placeholder="pilih program studi" name="prd" sel-2>
					<?php foreach ($this->listProdi as $dataProdi) { ?>
					<option value="<?php echo $dataProdi['kd_prodi']; ?>"><?php echo $dataProdi['kd_prodi']." : ".$dataProdi['nm_prodi']; ?></option>
					<?php } ?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">Status Mahasiswa</label>
			<div class="col-sm-4">
				<select id="stat" class="form-control chosen-select" multiple="multiple" data-placeholder="pilih status mahasiswa" name="stat" sel-2>
					<?php foreach ($this->listStat as $dataStat) { ?>
					<option value="<?php echo $dataStat['id_stat_mhs']; ?>"><?php echo $dataStat['id_stat_mhs']." : ".$dataStat['status_mhs']; ?></option>
					<?php } ?>
				</select>
			</div>
		</div>
		<div class="box-footer col-sm-6">
			<button type="submit" class="btn btn-info pull-right col-sm-2">Search</button>
		</div>
	</div>
</form>
<script src="<?php echo $this->baseUrl;?>/public/js/plugins/chosen/chosen.jquery.js"></script>
<script>
$("[sel-2]").chosen();
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script type="text/javascript">
$(document).ready(function(){
  $("#frm").submit(function() {
    ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/showmhswali","/mhswali/list","s");
    return false;
  });
});
</script>