							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="footer">
				<div class="footer-inner">
					<div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder"><?php echo $this->nm_pt;?></span> &copy; 2016 
						</span>
					</div>
				</div>
			</div>
			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
			</a>
			<div class="pull-right hidden-xs">
				<div id=loader style=display:none><img id=loadingbar src=<?php echo $this->baseUrl;?>/public/img/loading.gif></div>
			</div>
		</div>
		<script type="text/javascript">
			window.jQuery || document.write("<script src='<?php echo $this->baseUrl;?>/public/assets/js/jquery.min.js'>"+"<"+"/script>");
		</script>
		<script type="text/javascript">
			if('ontouchstart' in document.documentElement) document.write("<script src='<?php echo $this->baseUrl;?>/public/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
		</script>
		<script src="<?php echo $this->baseUrl;?>/public/assets/js/bootstrap.min.js"></script>
		<script src="<?php echo $this->baseUrl;?>/public/assets/js/ace-elements.min.js"></script>
		<script src="<?php echo $this->baseUrl;?>/public/assets/js/ace.min.js"></script>
	</body>
</html>