<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker-bs3.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Filter </h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">FILTER : PRODI</label>
				<div class="col-sm-4">
					<select id="prd" class="form-control data-placeholder="pilih program studi" name="prd">
						<?php foreach ($this->listProdi as $dataProdi) { ?>
						<option value="<?php echo $dataProdi['kd_prodi']; ?>"><?php echo $dataProdi['kd_prodi']." : ".$dataProdi['nm_prodi']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Dari Tanggal</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="tgl1" placeholder="tanggal awal" readonly tgl>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Sampai Tanggal</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="tgl2" placeholder="tanggal akhir" readonly tgl>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Tipe Rekapan</label>
				<div class="col-sm-4">
					<select id="tp" class="form-control">
						<option value="0">Detil</option>
						<option value="1">Kumulatif</option>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="submit" class="btn btn-success pull-right col-sm-4">Generate Rekap</button>
			</div>
		</div>
	</form>
</div>
<script src="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/moment.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker.js"></script>
<script>
	$(function(){$("[tgl]").daterangepicker({singleDatePicker:true,format:'DD MMMM YYYY'});});
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
	    ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax5/showkbmrekapdosen","/kbm/erekapdosen","s");
	    return false;
	  });
	});
</script>