<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<?php //echo $this->x;?>
<?php if(!$this->per){?>
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Filter </h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">FILTER : PERIODE</label>
				<div class="col-sm-4">
					<select id="per" class="form-control data-placeholder="pilih periode akademik" name="per">
						<?php foreach ($this->listPeriode as $dataPeriode) { ?>
						<option value="<?php echo $dataPeriode['kd_periode']; ?>"><?php echo $dataPeriode['kd_periode']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">FILTER : PRODI</label>
				<div class="col-sm-4">
					<select id="prd" class="form-control data-placeholder="pilih program studi" name="prd">
						<?php foreach ($this->listProdi as $dataProdi) { ?>
						<option value="<?php echo $dataProdi['kd_prodi']; ?>"><?php echo $dataProdi['kd_prodi']." : ".$dataProdi['nm_prodi']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="submit" class="btn btn-info pull-right col-sm-2">Show</button>
			</div>
		</div>
	</form>
</div>
<?php }else{ ?>
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">REKAP PERKULIAHAN SEMESTER <?php echo $this->per;?> PRODI <?php echo $this->nm_prd;?></h3>
	</div>
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbpkls" class="table table-bordered table-hover table-striped">
				<thead align="center">
					<tr align="center">
						<td rowspan="3" width="3%">NO</td>
						<td rowspan="3" width="15%">NAMA DOSEN</td>
						<td rowspan="3" width="10%">MATA KULIAH</td>
						<td rowspan="3" width="12%">KELAS</td>
						<td rowspan="3" width="12%">TANGGAL</td>
						<td rowspan="3">MATERI</td>
						<td colspan="5">PERTEMUAN</td>
					</tr>
					<tr align="center">
						<td rowspan="2" width="5%">DOSEN</td>
						<td colspan="4">MHS</td>
					</tr>
					<tr align="center">
						<td width="3%">H</td>
						<td width="3%">A</td>
						<td width="3%">S</td>
						<td width="3%">I</td>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;$n=1;foreach ($this->listReport as $dataRep) { ?>
					<?php 
						$kd_dsn[0]="";
						$kd_mk[0]="";
						$kls[0]="";
					?>
					<tr>
						<?php $kd_dsn[$i]=$dataRep['kd_dosen'];if($dataRep['kd_dosen']!=$kd_dsn[$i-1]){?>
						<td><?php echo $n; ?></td>
						<td><?php echo $dataRep['nm_dosen'];?></td>
						<?php $n++;}else{ ?>
						<td></td>
						<td></td>
						<?php } ?>
						<?php $kd_mk[$i]=$dataRep['kode_mk'];if(($dataRep['kode_mk']!=$kd_mk[$i-1])or($dataRep['kd_dosen']!=$kd_dsn[$i-1])){?>
						<td><?php echo $dataRep['nm_mk']; ?></td>
						<?php }else{?>
						<td></td>
						<?php }?>
						<?php $kls[$i]=$dataRep['kd_paket_kelas'];if(($dataRep['kd_paket_kelas']!=$kls[$i-1])or($dataRep['kode_mk']!=$kd_mk[$i-1]or($dataRep['kd_dosen']!=$kd_dsn[$i-1]))){?>
						<?php $hDosen=1;$sumHdr=0; ?>
						<td><?php echo $dataRep['nm_kelas']."-".$dataRep['jns_kelas']; ?></td>
						<?php }else{?>
						<?php $hDosen++;$sumHdr=$sumHdr+$dataRep['n_hadir']; ?>
						<td></td>
						<?php }?>
						<td><?php echo $dataRep['tgl_kuliah_fmt']; ?></td>
						<td><?php echo $dataRep['materi']; ?></td>
						<td align="center">1</td>
						<td align="center"><?php echo $dataRep['n_hadir']; ?></td>
						<td align="center"><?php echo $dataRep['n_alpha']; ?></td>
						<td align="center"><?php echo $dataRep['n_sakit']; ?></td>
						<td align="center"><?php echo $dataRep['n_izin']; ?></td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<?php } ?>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
	    ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax5/showkbmrep","/kbm/report","s");
	    return false;
	  });
	});
</script>