<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Data Diskusi</h3>
</div>
<div class="inqbox-content">
	<div class="panel panel-primary">
		<div class="panel-body">
			<div class="col-sm-4">Program Studi</div>
			<div class="col-sm-8">: <?php echo $this->nm_prodi;?></div>
			<div class="col-sm-4">Periode Akademik</div>
			<div class="col-sm-8">: <?php echo $this->kd_per;?></div>
			<div class="col-sm-4">Jenis Kelas</div>
			<div class="col-sm-8">: <?php echo $this->jns_kelas;?></div>
			<div class="col-sm-4">Dosen</div>
			<div class="col-sm-8">: <?php echo $this->nm_dsn." (".$this->kd_dsn.")";?></div>
			<div class="col-sm-4">Mata Kuliah</div>
			<div class="col-sm-8">: <?php echo $this->nm_mk." (".$this->kd_mk.") - ".$this->sks." SKS";?></div>
			<div class="col-sm-4">Nama Kelas</div>
			<div class="col-sm-8">: <?php echo $this->nm_kelas;?></div>
		</div>
	</div>
	<div class="table-responsive">
		<table id="tbkls" class="table table-bordered table-hover">
			<thead align="center">
				<tr>
					<th width="5%">NO</th>
					<th width="8%">MINGGU</th>
					<th>DISKUSI</th>
					<th width="15%">TANGGAL</th>
					<th width="15%">KONTRIBUTOR</th>
					<th width="10%">STATUS</th>
					<th width="10%">NILAI</th>
					<th width="10%">AKSI</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=1;foreach ($this->listDiskusi as $dataDiskusi) { ?>
				<tr>
					<td><?php echo $i; ?></td>
					<td><?php echo $dataDiskusi['minggu']; ?></td>
					<td>
						<strong>Judul</strong> : <?php echo $dataDiskusi['judul_diskusi']; ?><br>
						<strong>Materi Diskusi </strong> : <br> <?php echo $dataDiskusi['konten_diskusi']; ?><br>
						<strong>Parameter</strong> : <?php echo $dataTugas['param_nilai']; ?>
					</td>
					<td align="center">
						<strong>Diterbitkan </strong> : <?php echo $dataDiskusi['published_fmt']; ?><br>
						<strong>Kadaluwarsa </strong> : <?php echo $dataDiskusi['expired_fmt']; ?><br>
					</td>
					<td align="center">
						<?php echo $dataDiskusi['nm_dosen']." (".$dataDiskusi['created'].")"; ?>
					</td>
					<td align="center">
						<?php echo $dataDiskusi['status_diskusi'];?><br><br>
						<span class="label label-<?php echo $dataDiskusi['warna'];?>"><?php echo $dataDiskusi['status_done'];?></span>
					</td>
					<td align="center">
						<?php echo $dataDiskusi['nilai']; ?>
					</td>
					<td align="center">
						<?php if($dataDiskusi['status_diskusi']=='RUNNING'){?>
						<button type="button" class="btn btn-warning btn-sm" onclick="nav('<?php echo $this->baseUrl;?>/lms/diskusidetil?id=<?php echo $dataDiskusi['id_diskusi'];?>&kul=<?php echo $this->kd_kuliah;?>&a=<?php echo $this->a;?>')"><i class="fa fa-pencil">&nbsp;Posting Respon</i></button>
						<?php }else{ ?>
						<button type="button" class="btn btn-reset btn-sm" onclick="nav('<?php echo $this->baseUrl;?>/lms/diskusidetil?id=<?php echo $dataDiskusi['id_diskusi'];?>&kul=<?php echo $this->kd_kuliah;?>&a=<?php echo $this->a;?>')"><i class="fa fa-eye">&nbsp;Lihat Respon</i></button>
						<?php } ?>
					</td>
				</tr>
				<?php $i++; } ?>
		</table>
	</div>
</div>