<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Data Diskusi</h3>
</div>
<div class="inqbox-content">
	<div class="panel panel-primary">
		<div class="panel-body">
			<div class="col-sm-2">Minggu</div>
			<div class="col-sm-10">: <?php echo $this->minggu;?></div>
			<div class="col-sm-2">Diterbitkan</div>
			<div class="col-sm-10">: <?php echo $this->tgl1;?></div>
			<div class="col-sm-2">Kadaluwarsa</div>
			<div class="col-sm-10">: <?php echo $this->tgl2;?></div>
			<div class="col-sm-2">Kontributor</div>
			<div class="col-sm-10">: <?php echo $this->nm_dosen;?></div>
			<div class="col-sm-2">Status Tugas</div>
			<div class="col-sm-10">: <?php echo $this->status_diskusi;?></div>
		</div>
	</div>
	<div class="panel panel-primary">
		<div class="panel-body">
			<h3><?php echo $this->jdl;?></h3>
			<div class="col-sm-12"><strong>Materi Diskusi :</strong><br><?php echo $this->knt;?></div>
		</div>
	</div>
	<?php if($this->allow=='f'){?>
	<h5 class="alert alert-danger"><i class="icon fa fa-warning"></i>&nbsp;&nbsp;Anda tidak dapat memposting respon diskusi ini lagi, karena sudah kadaluwarsa atau belum Running</h5>
	<?php }else{ ?>
	<div class="panel-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="col-md-12">
				<div class="form-group">
					<label class="col-sm-2 control-label">Respon</label>
					<div class="col-sm-10">
						<input type="hidden" id="id_diskusi" value="<?php echo $this->id_diskusi;?>">
						<input type="hidden" id="kd_kuliah" value="<?php echo $this->kd_kuliah;?>">
						<textarea class="form-control" id="rsp" placeholder="respon" rows="8"></textarea>
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="box-footer col-sm-6">
					<button type="submit" class="btn btn-primary pull-right col-sm-4" id="btnsbm">Kirim</button>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-4" id="btnres">Reset</button>
				</div>
			</div>
		</form>
	</div>
	<?php } ?>
	<div class="table-responsive">
		<table id="tbkls" class="table table-bordered table-hover">
			<thead align="center">
				<tr>
					<th>RESPON</th>
					<th width="10%">NILAI</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=1;$n=0;foreach ($this->listDiskMhs as $dataDisk) { ?>
				<tr>
					<td>	<strong><?php echo $dataDisk['nm_mhs']." (".$dataDisk['nim'].")"; ?></strong><br><br>
						<?php echo $dataDisk['respon']; ?><br><br>
						<i><small><?php echo $dataDisk['created']; ?></small></i>
					</td>
					<td align="center">
						<?php if($this->nim==$dataDisk['nim']){?>
						<?php echo number_format($dataDisk['nilai'],2,',','.'); ?>
						<?php } ?>
					</td>
				</tr>
				<?php $i++; $n++;} ?>
		</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","","/ajax/insdiskusimhs","/lms/diskusidetil?id=<?php echo $this->id_diskusi;?>&kul=<?php echo $this->kd_kuliah;?>&a=<?php echo $this->a;?>&new=","u");
	  return false;
	});
</script>