<div class="table-header">
	Daftar Periode Akademik
</div>
<div>
	<table id="tbl" class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th>KODE PERIODE</th>
				<th>STATUS PERIODE</th>
				<th>TANGGAL DIMULAI</th>
				<th>TANGGAL SELESAI</th>
				<th width="10%">KALENDER KEUANGAN</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->listPeriode as $dataPer) { ?>
			<tr>
				<td><?php echo $dataPer['kd_periode']; ?></td>
				<td><?php echo $dataPer['status_periode_akademik']; ?></td>
				<td><?php echo $dataPer['tanggal_mulai_fmt']; ?></td>
				<td><?php echo $dataPer['tanggal_selesai_fmt']; ?></td>
				<td align="center">
					<button type="button" class="btn btn-info btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/kalender/detil?id=<?php echo $dataPer['kd_periode'];?>')"><i class="fa fa-calendar"></i></button>
				</td>
			</tr>
			<?php }?>
		</tbody>
	</table>
</div>
<script src="<?php echo $this->baseUrl;?>/public/assets/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/assets/js/jquery.dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/js/tabel.js"></script>
<script>
	$(function(){tabel('tbl')});
</script>