<div class="table-header">
	Daftar Komponen Biaya
</div>
<div>
	<table id="tbl" class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th class="center" width="15%">ID Komponen</th>
				<th class="center">Nama Komponen Biaya</th>
				<th class="center" width="10%">Status</th>
				<th class="center" width="15%">Biaya Interval ?</th>
				<th class="center" width="15%">Aksi</th>
				<th class="center" width="15%">Ubah Status</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->listKompBiaya as $dtKompBiaya){?>
			<tr>
				<td><?php echo $dtKompBiaya['id_komp'];?></td>
				<td><?php echo $dtKompBiaya['nm_komp'];?></td>
				<?php 
					if($dtKompBiaya['status']=='t'){
						$status="BERLAKU";
					}else{
						$status="TIDAK BERLAKU";
					}
					if($dtKompBiaya['biaya_ta']=='t'){
						$ta="YA";
					}else{
						$ta="TIDAK";
					}
				?>
				<td class="center"><?php echo $status;?></td>
				<td class="center"><?php echo $ta;?></td>
				<td class="center">
					<div class="hidden-sm hidden-xs action-buttons">
						<a class="green" onclick="nav('<?php echo $this->baseUrl;?>/kompbiaya/edit?id=<?php echo $dtKompBiaya['id_komp'];?>')"><i class="ace-icon fa fa-pencil bigger-130"></i></a>
						<a class="red" onclick="confirm('Apakah Anda yakin akan menghapus komponen biaya ini ? <strong><?php echo str_replace("'", "\'", $dtKompBiaya['nm_komp']);?></strong>','<?php echo $this->baseUrl;?>','/ajax/delkompbiaya',new Array('<?php echo $dtKompBiaya['id_komp'];?>'))"><i class="ace-icon fa fa-trash-o bigger-130"></i></a>
					</div>
				</td>
				<td class="center">
					<div class="hidden-sm hidden-xs action-buttons">
						<?php 
							if($dtKompBiaya['status']=='t'){
								$st='f';
								$app='remove';
							}else{
								$st='t';
								$app='check';
							}
						?>
						<a class="red" onclick="confirm('Apakah Anda yakin akan mengubah status komponen biaya ini ? <strong><?php echo str_replace("'", "\'", $dtKompBiaya['nm_komp']);?></strong>','<?php echo $this->baseUrl;?>','/ajax/updstatkompbiaya',new Array('<?php echo $st;?>','<?php echo $dtKompBiaya['id_komp'];?>'))"><i class="ace-icon fa fa-<?php echo $app;?> bigger-130"></i></a>
					</div>
				</td>
			</tr>
			<?php }?>
		</tbody>
	</table>
</div>
<script src="<?php echo $this->baseUrl;?>/public/assets/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/assets/js/jquery.dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/js/tabel.js"></script>
<script>
	$(function(){tabel('tbl')});
</script>