<form class="form-horizontal" role="form" id="frm">
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> ID Komponen Biaya </label>
		<div class="col-sm-9">
			<input type="text" id="idKomp" placeholder="ID Komponen Biaya" class="col-xs-10 col-sm-5" />
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nama Komponen Biaya </label>
		<div class="col-sm-9">
			<input type="text" id="nmKomp" placeholder="Nama Komponen Biaya" class="col-xs-10 col-sm-5" />
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Biaya Interval ? </label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="ta">
				<option value="f">TIDAK</option>
				<option value="t">YA</option>
			</select>
		</div>
	</div>
	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<button class="btn btn-info" type="submit"><i class="ace-icon fa fa-check bigger-110"></i>Submit</button>
			&nbsp; &nbsp; &nbsp;
			<button class="btn" type="reset"><i class="ace-icon fa fa-undo bigger-110"></i>Reset</button>
		</div>
	</div>
</form>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/inskompbiaya","/kompbiaya?new=","i");
	  return false;
	});
</script>