<div class="row">
	<div class="col-sm-8">
		<div class="col-sm-4">Nama (NIM)</div>
		<div class="col-sm-8">: <?php echo $this->nm." (".$this->nim.")";?></div>
		<div class="col-sm-4">Program Studi</div>
		<div class="col-sm-8">: <?php echo $this->nm_prd;?></div>
		<div class="col-sm-4">Angkatan</div>
		<div class="col-sm-8">: <?php echo $this->akt;?></div>
		<div class="col-sm-4">Status Masuk</div>
		<div class="col-sm-8">: <?php echo $this->stat_msk;?></div>
		<div class="col-sm-4">Status Registrasi</div>
		<div class="col-sm-8">: <?php echo $this->stat_reg;?></div>
		<?php
			$nm_gel=$this->nm_gel; 
			if($this->nm_gel==""){
				$nm_gel="<span class='label label-warning'>Belum Diset</span>";
			}
		?>
		<div class="col-sm-4">Gelombang</div>
		<div class="col-sm-8">: <?php echo $nm_gel;?></div>
		<div class="col-sm-4">Periode Akademik</div>
		<div class="col-sm-8">: <?php echo $this->per;?></div>
	</div>
</div>
<div class="table-header">
	Rincian Biaya Periodik <?php $per;?>
</div>
<table class="table table-striped table-bordered table-hover">
	<thead>
		<tr>
			<th class="center" width="5%">No</th>
			<th class="center" width="15%">Komponen Biaya</th>
			<th class="center" width="12%">Nominal Biaya</th>
			<th class="center" width="20%">Formulasi Biaya</th>
			<th class="center" width="12%">Nominal Komponen</th>
			<th class="center" width="12%">Nominal Kompensasi</th>
			<th class="center" width="12%">Terbayar</th>
			<th class="center" width="12%">Tunggakan</th>
		</tr>
	</thead>
	<tbody>
		<?php $totBiaya=0;$totKomp=0;$totBayar=0;$i=1;foreach ($this->listMhsBiayaDtl as $dtBiaya) { ?>
		<tr>
			<td class="center"><?php echo $i;?></td>
			<td><?php echo $dtBiaya['nm_komp'];?></td>
			<td align="right"><?php echo number_format($dtBiaya['nominal_formula'],2,',','.');?></td>
			<?php 
				$rule="";
				if($dtBiaya['id_rule']=='1'){
					$rule=number_format($dtBiaya['hard_nominal'],2,',','.');
				}elseif ($dtBiaya['id_rule']=='2'){
					$rule=$dtBiaya['nm_param'];
				}elseif ($dtBiaya['id_rule']=='3'){
					$rule=$dtBiaya['bil_pengali'];
				}
			?>
			<td class="center"><?php echo $dtBiaya['nm_rule'];?> :<?php echo $rule;?></td>
			<td align="right"><?php echo number_format($dtBiaya['nominal_komp'],2,',','.');?></td>
			<td align="right"><?php echo number_format($dtBiaya['nominal_kompensasi'],2,',','.');?></td>
			<td align="right"><?php echo number_format($dtBiaya['nominal_alocate'],2,',','.');?></td>
			<td align="right"><?php echo number_format(($dtBiaya['nominal_komp']-$dtBiaya['nominal_kompensasi']-$dtBiaya['nominal_alocate']),2,',','.');?></td>
		</tr>
		<?php 
			$i++;
			$totBiaya=$totBiaya+$dtBiaya['nominal_komp'];
			$totKomp=$totKomp+$dtBiaya['nominal_kompensasi'];
			$totBayar=$totBayar+$dtBiaya['nominal_alocate'];
		}?>
		<tr>
			<td colspan="4" class="center"><strong>TOTAL</strong></td>
			<td align="right"><strong><?php echo number_format($totBiaya,2,',','.');?></strong></td>
			<td align="right"><strong><?php echo number_format($totKomp,2,',','.');?></strong></td>
			<td align="right"><strong><?php echo number_format($totBayar,2,',','.');?></strong></td>
			<td align="right"><strong><?php echo number_format(($totBiaya-$totKomp-$totBayar),2,',','.');?></strong></td>
		</tr>
	</tbody>
</table>
<div class="table-header">
	Kartu Studi Mahasiswa (KRS)
</div>
<table class="table table-striped table-bordered table-hover">
	<tr align="center">
		<td rowspan="3" width="5%">No</td>
		<td colspan="4">Mata Kuliah</td>
		<td colspan="2">Dosen</td>
		<td rowspan="3">Nama Kelas</td>
		<td rowspan="3">Status</td>
	</tr>
	<tr align="center">
		<td width="8%" rowspan="2">Kode Mata Kuliah</td>
		<td width="18%" rowspan="2">Nama Mata Kuliah</td>
		<td colspan="2">* SKS</td>
		<td width="10%" rowspan="2">Kode Dosen</td>
		<td width="20%" rowspan="2">Nama Dosen</td>
	</tr>
	<tr align="center">
		<td width="5%">Default</td>
		<td width="5%">Taken</td>
	</tr>
	<?php $i=1;$totSksDef=0;$totSksTaken=0;$totSksTakenApp=0;foreach ($this->listKuliah as $dataKuliah){ ?>
	<tr>
		<td align="center"><?php echo $i ?></td>
		<td><?php echo $dataKuliah['kode_mk'] ?></td>
		<td><?php echo $dataKuliah['nm_mk'] ?></td>
		<td align="center"><?php echo ($dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']);?></td>
		<td align="center"><?php echo $dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']-$dataKuliah['sks_deducted'];?></td>
		<td align="center"><?php echo $dataKuliah['kd_dosen'];?></td>
		<td><?php echo $dataKuliah['nm_dosen'] ?></td>
		<td align="center"><?php echo $dataKuliah['nm_kelas'];?></td>
		<?php
			if($dataKuliah['approved']=='t'){
				$ap = "check-square-o";
				$totSksTakenApp=$totSksTakenApp+($dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']-$dataKuliah['sks_deducted']);
			}else{
				$ap = "warning";
			}
		?>
		<td align="center"><i class="fa fa-<?php echo $ap;?>"></i></td>
	</tr>
	<?php $totSksDef=$totSksDef+($dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']);$totSksTaken=$totSksTaken+($dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']-$dataKuliah['sks_deducted']);$i++;}?>
	<?php $j=$i;$totSksDefTA=0;$totSksTakenTA=0;$totSksTakenTAApp=0;foreach ($this->listKuliahTA as $dataKuliahTA){ ?>
	<tr>
		<td align="center"><?php echo $j ?></td>
		<td><?php echo $dataKuliahTA['kode_mk'] ?></td>
		<td><?php echo $dataKuliahTA['nm_mk'] ?></td>
		<td align="center"><?php echo ($dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']);?></td>
		<td align="center"><?php echo $dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']-$dataKuliahTA['sks_deducted'];?></td>
		<td align="center"><?php echo $dataKuliahTA['kd_dosen'];?></td>
		<td><?php echo $dataKuliahTA['nm_dosen'] ?></td>
		<td align="center"><?php echo $dataKuliahTA['nm_kelas'];?> (Periode Mulai : <?php echo $dataKuliahTA['kd_periode_mulai'];?>)</td>
		<?php
			if($dataKuliahTA['approved']=='t'){
				$ap = "check-square-o";
				$totSksTakenTAApp=$totSksTakenTAApp+($dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']-$dataKuliahTA['sks_deducted']);
			}else{
				$ap = "warning";
			}
		?>
		<td align="center"><i class="fa fa-<?php echo $ap;?>"></i></td>
	</tr>
	<?php $totSksDefTA=$totSksDefTA+($dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']);$totSksTakenTA=$totSksTakenTA+($dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']-$dataKuliahTA['sks_deducted']);$j++;}?>
	<tr>
		<td align="center" colspan="3"><b>Jumlah</b></td>
		<td align="center"><?php echo $totSksDef+$totSksDefTA;?></td>
		<td align="center"><?php echo $totSksTaken+$totSksTakenTA;?></td>
		<td colspan="3"><strong>Jumlah SKS Approved</strong></td>
		<td align="center"><strong><?php echo $totSksTakenApp+$totSksTakenTAApp;?></strong></td>
	</tr>	
</table>