<table style="width: 100%;">
	<tr>
		<td align="center"><strong><a style="font-size: 18px">SEKOLAH TINGGI FARMASI INDONESIA</a></strong></td>
	</tr>
	<tr>
		<td align="center"><strong><a style="font-size: 20px"><?php echo $this->judul_kop;?></a></strong></td>
	</tr>
	<tr>
		<td align="center"><strong><a style="font-size: 12px">JL.SOEKARNO HATTA 354 BANDUNG</td>
	</tr>
	<tr>
		<td><hr></td>
	</tr>
</table>