<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/assets/css/datepicker.min.css" />
<div class="row">
	<div class="col-sm-8">
		<div class="col-sm-4">Nama (NIM)</div>
		<div class="col-sm-8">: <?php echo $this->nm." (".$this->nim.")";?></div>
		<div class="col-sm-4">Program Studi</div>
		<div class="col-sm-8">: <?php echo $this->nm_prd;?></div>
		<div class="col-sm-4">Angkatan</div>
		<div class="col-sm-8">: <?php echo $this->akt;?></div>
		<div class="col-sm-4">Status Masuk</div>
		<div class="col-sm-8">: <?php echo $this->stat_msk;?></div>
		<div class="col-sm-4">Gelombang</div>
		<?php
			$nm_gel=$this->nm_gel; 
			if($this->nm_gel==""){
				$nm_gel="<span class='label label-warning'>Belum Diset</span>";
			}
		?>
		<div class="col-sm-8">: 
			<?php echo $nm_gel;?>
			<?php if($this->nm_gel==""){?>
				<a class="label label-primary" onclick="nav('<?php echo $this->baseUrl; ?>/gelmhs/new?nim=<?php echo $this->nim;?>&src=mhsbi')">Set Disini</a>
			<?php }?>
		</div>
	</div>
</div>
<div class="table-header">
	Biaya Periodik Mahasiswa
	<button class="btn btn-success btn-sm pull-right" onclick="confirm('Apakah Anda yakin akan merealokasi pembayaran mahasiswa ini ? NIM : <strong><?php echo $this->nim;?></strong>','<?php echo $this->baseUrl;?>','/ajax/realocate',new Array('<?php echo $this->nim;?>'))"><i class="ace-icon fa fa-refresh bigger-130"></i> Realokasi Pembayaran</button>
</div>
<div>
	<table id="tbl" class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th class="center" width="5%" rowspan="2">No</th>
				<th class="center" width="15%" rowspan="2">Periode Akademik</th>
				<th class="center" rowspan="2">Status Her Registrasi</th>
				<th class="center" width="8%" rowspan="2">Status Mahasiswa</th>
				<th class="center" colspan="4">SKS/Jumlah MK</th>
				<th class="center" width="12%" rowspan="2">Total Biaya</th>
				<th class="center" width="12%" rowspan="2">Kompensasi (Klik untuk menambahkan)</th>
				<th class="center" width="12%" rowspan="2">Tunggakan/Lebih Bayar</th>
				<th class="center" width="5%" rowspan="2">Rincian Biaya</th>
			</tr>
			<tr>
				<th class="center" width="5%">Teori</th>
				<th class="center" width="5%">Prak</th>
				<th class="center" width="5%">TA</th>
				<th class="center" width="5%">Konv</th>
			</tr>
		</thead>
		<tbody>
			<?php $totBiaya=0;$totTunggakanPer=0;$i=1;foreach ($this->listMhsBiayaPer as $dtMhsReg){?>
			<tr>
				<td class="center"><?php echo $i;?></td>
				<td class="center"><?php echo $dtMhsReg['kd_periode'];?></td>
				<td class="center"><?php echo $dtMhsReg['status_reg'];?></td>
				<td class="center"><?php echo $dtMhsReg['status_mhs_periode'];?></td>
				<td class="center"><?php echo $dtMhsReg['sks_teori'];?>/<?php echo $dtMhsReg['n_teori'];?></td>
				<td class="center"><?php echo $dtMhsReg['sks_prak'];?>/<?php echo $dtMhsReg['n_prak'];?></td>
				<td class="center"><?php echo $dtMhsReg['sks_ta'];?>/<?php echo $dtMhsReg['n_ta'];?></td>
				<td class="center">
					<?php 
						if($dtMhsReg['ada_formula_sks_konv']=='t'){
							echo $dtMhsReg['sks_konv'];
						}else{
							echo "0";
						}
					;?>
				</td>
				<td align="right"><?php echo number_format($dtMhsReg['tot_biaya'],2,',','.');?></td>
				<td align="right">
					<a onclick="nav('<?php echo $this->baseUrl;?>/kompensasi/index?nim=<?php echo $dtMhsReg['nim'];?>&per=<?php echo $dtMhsReg['kd_periode'];?>')" style="cursor: pointer;"><?php echo number_format($dtMhsReg['tot_kompensasi'],2,',','.');?></a>
				</td>
				<td align="right"><?php echo number_format(($dtMhsReg['tot_biaya']-$dtMhsReg['tot_kompensasi']-$dtMhsReg['tot_nom_bayar_periode']),2,',','.');?></td>
				<td class="center">
					<button type="button" class="btn btn-primary btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/mhsbiaya/detil?nim=<?php echo $dtMhsReg['nim'];?>&per=<?php echo $dtMhsReg['kd_periode'];?>')"><i class="fa fa-eye"></i></button>
				</td>
			</tr>
			<?php 
				$totTunggakanPer=$totTunggakanPer+($dtMhsReg['tot_biaya']-$dtMhsReg['tot_kompensasi']-$dtMhsReg['tot_nom_bayar_periode']);
				$totBiaya=$totBiaya+$dtMhsReg['tot_biaya']-$dtMhsReg['tot_kompensasi'];
				$i++;
			}?>
			<tr>
				<td colspan="12">
					<strong>Total Tunggakan / Lebih Bayar Periodik (Kumulatif) : <?php echo number_format(($totBiaya-$this->totBayarPer),2,',','.'); ?></strong>
					<br>
					<label class="label label-warning">Nb: Jika Minus berarti lebih bayar</label>
				</td>
			</tr>
		</tbody>
	</table>
</div>
<div class="table-header">
	Biaya Interval Mahasiswa
</div>
<div>
	<table id="tbl" class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th class="center" width="5%" rowspan="2">No</th>
				<th class="center" width="15%" rowspan="2">Periode Akademik</th>
				<th class="center">Komponen Biaya</th>
				<th class="center">Parameter - Indikator Biaya</th>
				<th class="center">Periode Berlaku</th>
				<th class="center" width="12%">Paket Biaya</th>
				<th class="center" width="12%">Total Biaya</th>
				<th class="center" width="12%">Tunggakan/Lebih Bayar</th>
			</tr>
		</thead>
		<tbody>
			<?php $totTunggakanInt=0;$i=1;foreach ($this->listBiayaInterval as $dtBiayaIntv){?>
			<?php 
				$nomByrIntv=0;
				foreach ($this->listBayar as $dtBayarInt) {
					if(($dtBiayaIntv['kd_periode']==$dtBayarInt['kd_periode'])and($dtBiayaIntv['id_komp']==$dtBayarInt['id_komp'])and($dtBayarInt['id_term']=='3')){
						$nomByrIntv=$nomByrIntv+$dtBayarInt['nominal'];
					}
				}
				$tunggakan=$dtBiayaIntv['nominal']-$nomByrIntv;
				$totTunggakanInt=$totTunggakanInt+$tunggakan;
			?>
			<tr>
				<td class="center"><?php echo $i;?></td>
				<td class="center"><?php echo $dtBiayaIntv['kd_periode'];?></td>
				<td class="center"><?php echo $dtBiayaIntv['nm_komp'];?></td>
				<td class="center"><?php echo $dtBiayaIntv['nm_param']."&gt;".$dtBiayaIntv['min_value'];?></td>
				<td class="center"><?php echo $dtBiayaIntv['kd_periode_berlaku'];?></td>
				<td class="center"><?php echo $dtBiayaIntv['nm_paket'];?></td>
				<td align="right"><?php echo number_format($dtBiayaIntv['nominal'],2,',','.');?></td>
				<td align="right"><?php echo number_format($tunggakan,2,',','.');?></td>
			</tr>
			<?php $i++;}?>
			<tr>
				<td colspan="7"><strong>Total Tunggakan / Lebih Bayar Biaya Interval</strong></td>
				<td align="right"><strong><?php echo number_format($totTunggakanInt,2,',','.');?></strong></td>
			</tr>
		</tbody>
	</table>
</div>
<div class="table-header">
	Sumbangan Mahasiswa
</div>
<div>
	<table id="tbl" class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th class="center" width="5%" rowspan="2">No</th>
				<th class="center" width="15%" rowspan="2">Periode Akademik</th>
				<th class="center">Komponen Biaya</th>
				<th class="center" width="12%">Nominal</th>
				<th class="center" width="12%">Tunggakan/Lebih Bayar</th>
			</tr>
		</thead>
		<tbody>
			<?php $totTunggakanSumb=0;$i=1;foreach ($this->listSumbangan as $dtSumbangan){?>
			<?php 
				$nomByrSumb=0;
				foreach ($this->listBayar as $dtBayarSumb) {
					if(($dtSumbangan['kd_periode']==$dtBayarSumb['kd_periode'])and($dtSumbangan['id_komp']==$dtBayarSumb['id_komp'])and($dtBayarSumb['id_term']=='4')){
						$nomByrSumb=$nomByrSumb+$dtBayarSumb['nominal'];
					}
				}
				$tunggakanSumb=$dtSumbangan['nominal']-$nomByrSumb;
				$totTunggakanSumb=$totTunggakanSumb+$tunggakanSumb;
			?>
			<tr>
				<td class="center"><?php echo $i;?></td>
				<td class="center"><?php echo $dtSumbangan['kd_periode'];?></td>
				<td class="center"><?php echo $dtSumbangan['nm_komp'];?></td>
				<td align="right"><?php echo number_format($dtSumbangan['nominal'],2,',','.');?></td>
				<td align="right"><?php echo number_format($tunggakanSumb,2,',','.');?></td>
			</tr>
			<?php $i++;}?>
			<tr>
				<td colspan="4"><strong>Total Tunggakan / Lebih Bayar Sumbangan</strong></td>
				<td align="right"><strong><?php echo number_format($totTunggakanSumb,2,',','.');?></strong></td>
			</tr>
		</tbody>
	</table>
</div>
<form class="form-horizontal" role="form" id="frm">
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Tanggal Bayar </label>
		<div class="col-sm-9">
			<input type="hidden" value="<?php echo $this->nim;?>" id="nim">
			<input class="date-picker col-xs-10 col-sm-5" id="tgl" readonly="readonly" type="text" data-date-format="dd MM yyyy">
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Jumlah Bayar</label>
		<div class="col-sm-9">
			<input type="number" id="nominal" class="col-xs-10 col-sm-5" placeholder="nominal" min="1" max="10000000000" step="0.01">
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Via Bayar</label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="via">
				<option value="" disabled="disabled" selected="selected">pilih via bayar</option>
				<?php foreach ($this->listVia as $dtVia){?>
				<option value="<?php echo $dtVia['id_via'];?>"><?php echo $dtVia['via'];?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Bank Tujuan</label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="bank">
				<option value="" disabled="disabled" selected="selected">pilih bank tujuan</option>
				<?php foreach ($this->listBank as $dtBank){?>
				<option value="<?php echo $dtBank['id_bank'];?>"><?php echo $dtBank['nm_bank']." (".$dtBank['no_rek'].")"?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> No.Bukti </label>
		<div class="col-sm-9">
			<input class="col-xs-10 col-sm-5" id="nobukti" type="text">
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Term Pembayaran</label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="term">
				<option value="" disabled="disabled" selected="selected">pilih term pembayaran</option>
				<?php foreach ($this->listTerm as $dtTerm){?>
				<option value="<?php echo $dtTerm['id_term'];?>"><?php echo $dtTerm['nm_term'];?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group hidden f-per">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Periode Akademik</label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="per">
				<option value="" disabled="disabled" selected="selected">pilih periode akademik</option>
				<?php foreach ($this->listMhsBiayaPer as $dtReg){?>
				<option value="<?php echo $dtReg['kd_periode'];?>"><?php echo $dtReg['kd_periode'];?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group hidden f-komp">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Komponen Biaya Interval</label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="komp">
				<option value="" disabled="disabled" selected="selected">pilih biaya interval</option>
				<?php foreach ($this->listBiayaInterval as $dtIntv){?>
				<option value="<?php echo $dtIntv['kd_periode']."||".$dtIntv['id_komp'];?>"><?php echo $dtIntv['nm_komp']." (".$dtIntv['kd_periode'].")";?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group hidden f-sumb">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Komponen Sumbangan</label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="sumb">
				<option value="" disabled="disabled" selected="selected">pilih komponen sumbangan</option>
				<?php foreach ($this->listSumbangan as $dtSumb){?>
				<option value="<?php echo $dtSumb['kd_periode']."||".$dtSumb['id_komp'];?>"><?php echo $dtSumb['nm_komp']." (".$dtSumb['kd_periode'].")";?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<button class="btn btn-info" type="submit"><i class="ace-icon fa fa-check bigger-110"></i>Submit</button>
			&nbsp; &nbsp; &nbsp;
			<button class="btn" type="reset" id="reset"><i class="ace-icon fa fa-undo bigger-110"></i>Reset</button>
		</div>
	</div>
</form>
<div class="alert alert-block alert-success">
	<i class="ace-icon fa fa-info-circle green"></i>
		Status verified menunjukkan data sudah diverifikasi bagian keuangan institusi. Status validated menunjukkan data sudah divalidasi oleh admin yayasan dan sudah tidak dapat diubah atau dihapus lagi.
	</div>
<div class="table-header">
	Histori Pembayaran Mahasiswa
</div>
<div>
	<table id="tbl" class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th class="center" width="5%" rowspan="2">No</th>
				<th class="center" width="12%" rowspan="2">Kode Pembayaran</th>
				<th class="center" width="15%" rowspan="2">Tanggal Bayar</th>
				<th class="center" width="15%" rowspan="2">Proses Pembayaran</th>
				<th class="center" width="15%" rowspan="2">Term Bayar</th>
				<th class="center" colspan="2">Tujuan Pembayaran</th>
				<th class="center" width="12%" rowspan="2">Jumlah Bayar</th>
				<th class="center" width="5%" rowspan="2">Status</th>
				<th class="center" width="8%" rowspan="2">Aksi</th>
				<th class="center" width="5%" rowspan="2">Print</th>
			</tr>
			<tr>
				<th class="center">Periode Akademik</th>
				<th class="center">Komponen Biaya</th>
			</tr>
		</thead>
		<tbody>
			<?php $i=1;foreach ($this->listBayar as $dtBayar){?>
			<tr>
				<td class="center"><?php echo $i;?></td>
				<td><?php echo $dtBayar['no_trans'];?></td>
				<td><?php echo $dtBayar['tgl_bayar_fmt'];?></td>
				<td><?php echo $dtBayar['via']." ke ".$dtBayar['nm_bank']." (".$dtBayar['no_rek'].") - ".$dtBayar['no_bukti'];?></td>
				<td class="center"><?php echo $dtBayar['nm_term'];?></td>
				<td class="center"><?php echo $dtBayar['kd_periode'];?></td>
				<td class="center"><?php echo $dtBayar['nm_komp'];?></td>
				<td align="right"><?php echo number_format($dtBayar['nominal'],2,',','.');?></td>
				<?php 
					$stat="Undefined";
					if($dtBayar['status_bayar']==0){
						$stat="Not Verified";
					}elseif ($dtBayar['status_bayar']==1){
						$stat="Verified";
					}elseif ($dtBayar['status_bayar']==2){
						$stat="Validated";
					}
				?>
				<td class="center"><?php echo $stat;?></td>
				<td class="center">
					<?php if($dtBayar['status_bayar']!=2){?>
					<div class="hidden-sm hidden-xs action-buttons">
						<a class="green" onclick="nav('<?php echo $this->baseUrl;?>/bayar/edit?kd=<?php echo $dtBayar['no_trans'];?>')"><i class="ace-icon fa fa-pencil bigger-130"></i></a>
						<a class="red" onclick="confirm('Apakah Anda yakin akan menghapus pembayaran ini ? <strong><?php echo $dtBayar['no_trans'];?></strong>','<?php echo $this->baseUrl;?>','/ajax/delbayar',new Array('<?php echo $dtBayar['no_trans'];?>'))"><i class="ace-icon fa fa-trash-o bigger-130"></i></a>
					</div>
					<?php }?>
				</td>
				<td align="center">
					<a class="btn btn-xs" onclick="openWin('<?php echo $this->baseUrl?>/mhsbiaya/ebayar?id=<?php echo $dtBayar['no_trans'];?>')"><i class="ace-icon fa fa-print"></i></a>
				</td>
			</tr>
			<?php $i++;}?>
		</tbody>
	</table>
</div>
<script src="<?php echo $this->baseUrl;?>/public/assets/js/bootstrap-datepicker.min.js"></script>
<script>
$('.date-picker').datepicker({
	autoclose: true,
	todayHighlight: true
})
</script>
<script>
	$("#term").change(function() {
	  var term=$("#term").val();
	  if(term=='2'){
		  $(".f-per").removeClass("hidden");
		  $(".f-komp").removeClass("hidden").addClass("hidden");
		  $(".f-sumb").removeClass("hidden").addClass("hidden");
	  }else if(term=='3'){
		  $(".f-komp").removeClass("hidden");
		  $(".f-per").removeClass("hidden").addClass("hidden");
		  $(".f-sumb").removeClass("hidden").addClass("hidden");
	  }else if(term=='4'){
		  $(".f-sumb").removeClass("hidden");
		  $(".f-per").removeClass("hidden").addClass("hidden");
		  $(".f-komp").removeClass("hidden").addClass("hidden");
	  }else{
		  $(".f-komp").removeClass("hidden").addClass("hidden");
		  $(".f-per").removeClass("hidden").addClass("hidden");
		  $(".f-sumb").removeClass("hidden").addClass("hidden");
	  }
	});
</script>
<script>
	$("#reset").on('click',(function() {
		$(".f-komp").removeClass("hidden").addClass("hidden");
		$(".f-per").removeClass("hidden").addClass("hidden");
		$(".f-sumb").removeClass("hidden").addClass("hidden");
	}));
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	 ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/insbayar","/mhsbiaya/list?nim=<?php echo $this->nim;?>&new=","u");
	 return false;
	});
</script>
<script>
	function openWin(url)
	{
		params  = 'width='+screen.width;
		 params += ', height='+screen.height;
		 params += ', top=0, left=0'
		 params += ', fullscreen=yes';
  		myWindow=window.open(url,'',params);
  		myWindow.document.close();
  		myWindow.focus();
  		//myWindow.print(); 
  		 return false;
	}
</script>