<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker-bs3.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Range Nilai</h3>
	</div>
	<div class="box-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="box-body">
				<div class="form-group">
					<label class="col-sm-2 control-label">Kode Range Nilai</label>
					<div class="col-sm-4">
						<input type="hidden" id="old_id" value="<?php echo $this->id;?>">
						<input type="text" class="form-control" id="id" placeholder="kode range nilai" maxlength="5" value="<?php echo $this->id;?>">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Nama Range Nilai</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="nm" placeholder="nama range nilai" maxlength="15" value="<?php echo $this->nm;?>">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Indeks Nilai Tunda</label>
					<div class="col-sm-4">
						<select class="form-control" id="id_tunda">
							<option disabled value="" selected>pilih indeks nilai tunda</option>
							<?php foreach ($this->listInd as $dataInd) {?>
							<?php
								if($dataInd['id_indeks']==$this->ind_t){
									$sel_id="selected";
								}else{
									$sel_id="";
								}
							?>
							<option value="<?php echo $dataInd['id_indeks'];?>" <?php echo $sel_id;?>><?php echo $dataInd['indeks'];?></option>
							<?php } ?>
						</select>
					</div>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
					<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan</button>
				</div>
			</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax2/updrange","/rangenilai/index?new=","u");
	  return false;
	});
</script>