<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="box box-info">
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbroom" class="table table-bordered table-hover">
				<thead align="center">
					<tr>
						<th width="15%">KODE RANGE</th>
						<th>NAMA RANGE NILAI</th>
						<th width="15%">NILAI TUNDA</th>
						<th width="15%">NILAI ANGKA</th>
						<th width="15%">AKSI</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listRangeNilai as $data) { ?>
					<tr>
						<td><?php echo $data['id_range_hdr']; ?></td>
						<td><?php echo $data['nama_range']; ?></td>
						<td align="center"><?php echo $data['indeks_tunda']; ?></td>
						<td align="center">
							<button type="button" class="btn btn-info btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/rangenilai/detil?id=<?php echo $data['id_range_hdr'];?>')"><i class="fa fa-eye"></i></button>
						</td>
						<td align="center">
							<button type="button" class="btn btn-warning btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/rangenilai/edit?id=<?php echo $data['id_range_hdr'];?>')"><i class="fa fa-pencil"></i></button>
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan menghapus range nilai ini ? <strong><?php echo str_replace("'", "\'", $data['nama_range']);?></strong>. Menghapus range nilai juga akan menghapus indeks-indeks nilainya','<?php echo $this->baseUrl;?>','/ajax2/delrange',new Array('<?php echo $data['id_range_hdr'];?>'))"><i class="fa fa-remove"></i></button>
						</td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<!-- DataTables -->
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbroom',true,true,true,true,true,false);});</script>