<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Filter Periode Akademik</h3>
</div>
<div class="inqbox-content">
	<form id="frm" class="form-horizontal">
		<div class="form-group">
			<div class="col-sm-4">
				<select id="sel_per" class="form-control">
					<?php foreach ($this->listPer as $dtPer){?>
					<?php 
						$per="";
						if($dtPer['kd_periode']==$this->per){
							$per="selected";
						}
					?>
					<option value="<?php echo $dtPer['kd_periode'];?>" <?php echo $per;?> ><?php echo $dtPer['kd_periode'];?></option>
					<?php }?>
				</select>
			</div>
		</div>
	</form>
</div>
<div class="inqbox-content">
	<div class="nav-tabs-custom">
		<ul class="nav nav-tabs">
			<?php $i=1;foreach ($this->listHari as $dataHari){ ?>
			<?php if($i==$this->tab){$active="active";}else{$active="";}?>
			<li class="<?php echo $active;?>"><a href="#tab_<?php echo $dataHari['nm_hari'] ?>" data-toggle="tab"><?php echo $dataHari['nm_hari'] ?></a></li>
			<?php $i++;} ?>
		</ul>
		<div class="tab-content">
			<?php $i=1;foreach ($this->listHari as $dataHari){ ?>
			<?php if($i==$this->tab){$active="active";}else{$active="";}?>
			<div class="tab-pane <?php echo $active;?>" id="tab_<?php echo $dataHari['nm_hari'] ?>">
				<div class="table-responsive">
					<table id="tbjdwl_<?php echo $i;?>" class="table table-bordered table-hover">
						<thead>
							<tr>
								<th width="12%">Slot Waktu</th>
								<th>Ruangan</th>
								<th>Kelas</th>
								<th>Dosen</th>
								<th>Kode MK</th>
								<th>Nama MK</th>
								<th>Prodi</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach ($this->listJadwal as $dataJadwal){ ?>
						<?php if($dataJadwal['id_hari']==$dataHari['id_hari']){ ?>
						<tr>
							<td><?php echo $dataJadwal['start_time']." s/d ".$dataJadwal['end_time'];?></td>
							<td><?php echo $dataJadwal['nm_ruangan'];?></td>
							<td><?php echo $dataJadwal['nm_kelas'];?></td>
							<td><?php echo $dataJadwal['nm_dosen'];?></td>
							<td><?php echo $dataJadwal['kode_mk'];?></td>
							<td><?php echo $dataJadwal['nm_mk'];?></td>
							<td><?php echo $dataJadwal['nm_prodi_kur'];?></td>
						</tr>
						<?php }?>
						<?php }?>
						</tbody>	
					</table>
				</div>
			</div>
			<?php $i++;} ?>
		</div>
	</div>
</div>
<script>
	$('#sel_per').on('change',(function() {
		per=$('#sel_per').val();
		nav('<?php echo $this->baseUrl;?>/jadwal/index?id='+per);
	}))
</script>