<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/assets/css/datepicker.min.css" />
<form class="form-horizontal" role="form" id="frm">
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Tanggal Bayar </label>
		<div class="col-sm-9">
			<input type="hidden" value="<?php echo $this->notrans;?>" id="notrans">
			<input type="hidden" value="<?php echo $this->nim;?>" id="nim">
			<input class="date-picker col-xs-10 col-sm-5" id="tgl" readonly="readonly" type="text" data-date-format="dd MM yyyy" value="<?php echo $this->tgl;?>">
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Jumlah Bayar</label>
		<div class="col-sm-9">
			<input type="number" id="nominal" class="col-xs-10 col-sm-5" placeholder="nominal" min="1" max="10000000000" step="0.01" value="<?php echo $this->nom;?>">
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Via Bayar</label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="via">
				<option value="" disabled="disabled">pilih via bayar</option>
				<?php foreach ($this->listVia as $dtVia){?>
				<?php 
					if($dtVia['id_via']==$this->via){
						$via="selected";
					}else{
						$via="";
					}
				?>
				<option value="<?php echo $dtVia['id_via'];?>" <?php echo $via;?>><?php echo $dtVia['via'];?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Bank Tujuan</label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="bank">
				<option value="" disabled="disabled" >pilih bank tujuan</option>
				<?php foreach ($this->listBank as $dtBank){?>
				<?php 
					if($dtBank['id_bank']==$this->bank){
						$bank="selected";
					}else{
						$bank="";
					}
				?>
				<option value="<?php echo $dtBank['id_bank'];?>" <?php echo $bank;?> ><?php echo $dtBank['nm_bank']." (".$dtBank['no_rek'].")"?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> No.Bukti </label>
		<div class="col-sm-9">
			<input class="col-xs-10 col-sm-5" id="nobukti" type="text" value="<?php echo $this->bukti;?>">
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Term Pembayaran</label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="term">
				<option value="" disabled="disabled">pilih term pembayaran</option>
				<?php foreach ($this->listTerm as $dtTerm){?>
				<?php 
					if($dtTerm['id_term']==$this->term){
						$term="selected";
					}else{
						$term="";
					}
				?>
				<option value="<?php echo $dtTerm['id_term'];?>" <?php echo $term;?> ><?php echo $dtTerm['nm_term'];?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group <?php echo $this->hid_per;?> f-per">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Periode Akademik</label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="per">
				<option value="" disabled="disabled">pilih periode akademik</option>
				<?php foreach ($this->listMhsBiayaPer as $dtReg){?>
				<?php 
					if($dtReg['kd_periode']==$this->per){
						$per="selected";
					}else{
						$per="";
					}
				?>
				<option value="<?php echo $dtReg['kd_periode'];?>" <?php echo $per;?>><?php echo $dtReg['kd_periode'];?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group <?php echo $this->hid_kom;?> f-komp">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Komponen Biaya Interval</label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="komp">
				<option value="" disabled="disabled" selected="selected">pilih biaya interval</option>
				<?php foreach ($this->listBiayaInterval as $dtIntv){?>
				<?php 
					if(($dtIntv['id_komp']==$this->komp)and($dtIntv['kd_periode']==$this->per)){
						$komp="selected";
					}else{
						$komp="";
					}
				?>
				<option value="<?php echo $dtIntv['kd_periode']."||".$dtIntv['id_komp'];?>" <?php echo $komp?>><?php echo $dtIntv['nm_komp']." (".$dtIntv['kd_periode'].")";?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group <?php echo $this->hid_sumb;?> f-sumb">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Komponen Sumbangan</label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="sumb">
				<option value="" disabled="disabled" selected="selected">pilih komponen sumbangan</option>
				<?php foreach ($this->listSumbangan as $dtSumb){?>
				<?php 
					if(($dtSumb['id_komp']==$this->komp)and($dtSumb['kd_periode']==$this->per)){
						$komp="selected";
					}else{
						$komp="";
					}
				?>
				<option value="<?php echo $dtSumb['kd_periode']."||".$dtSumb['id_komp'];?>" <?php echo $komp;?>><?php echo $dtSumb['nm_komp']." (".$dtSumb['kd_periode'].")";?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<button class="btn btn-info" type="submit"><i class="ace-icon fa fa-check bigger-110"></i>Submit</button>
			&nbsp; &nbsp; &nbsp;
			<button class="btn" type="reset" id="reset"><i class="ace-icon fa fa-undo bigger-110"></i>Reset</button>
		</div>
	</div>
</form>
<script src="<?php echo $this->baseUrl;?>/public/assets/js/bootstrap-datepicker.min.js"></script>
<script>
$('.date-picker').datepicker({
	autoclose: true,
	todayHighlight: true
})
</script>
<script>
	$("#term").change(function() {
	  var term=$("#term").val();
	  if(term=='2'){
		  $(".f-per").removeClass("hidden");
		  $(".f-komp").removeClass("hidden").addClass("hidden");
		  $(".f-sumb").removeClass("hidden").addClass("hidden");
	  }else if(term=='3'){
		  $(".f-komp").removeClass("hidden");
		  $(".f-per").removeClass("hidden").addClass("hidden");
		  $(".f-sumb").removeClass("hidden").addClass("hidden");
	  }else if(term=='4'){
		  $(".f-sumb").removeClass("hidden");
		  $(".f-per").removeClass("hidden").addClass("hidden");
		  $(".f-komp").removeClass("hidden").addClass("hidden");
	  }else{
		  $(".f-komp").removeClass("hidden").addClass("hidden");
		  $(".f-per").removeClass("hidden").addClass("hidden");
		  $(".f-sumb").removeClass("hidden").addClass("hidden");
	  }
	});
</script>
<script>
	$("#reset").on('click',(function() {
		$(".f-komp").removeClass("hidden").addClass("hidden");
		$(".f-per").removeClass("hidden").addClass("hidden");
		$(".f-sumb").removeClass("hidden").addClass("hidden");
	}));
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	 ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/updbayar","/mhsbiaya/list?nim=<?php echo $this->nim;?>&new=","u");
	 return false;
	});
</script>