<?php echo $this->render('helper/function.phtml');?>
<div class="box  box-info">
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbmkk" class="table table-bordered table-hover" style="cursor: pointer;">
				<thead align="center">
					<tr>
						<th>NO</th>
						<th>KODE MATA KULIAH</th>
						<th>NAMA MATA KULIAH</th>
						<th>SEMESTER</th>
						<th>SKS</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listMkKur as $dataMk) { ?>
					<tr onclick="insVal('<?php echo $this->readyCaller;?>', new Array('<?php echo escQuoteJS($dataMk['id_mk_kurikulum']);?>','<?php echo escQuoteJS($dataMk['kode_mk']);?>','<?php echo escQuoteJS($dataMk['nm_mk']);?>','<?php echo escQuoteJS($dataMk['sks_tot']);?>'))">
						<td><?php echo $i; ?></td>
						<td><?php echo $dataMk['kode_mk']; ?></td>
						<td><?php echo $dataMk['nm_mk']; ?></td>
						<td><?php echo $dataMk['smt_def']; ?></td>
						<td><?php echo $dataMk['sks_tot']; ?></td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<script>$(function () {tabel('tbmkk',true,true,true,true,true,false);});</script>