<?php echo $this->render('helper/function.phtml');?>
<div class="box  box-info">
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbmk" class="table table-bordered table-hover" style="cursor: pointer;">
				<thead align="center">
					<tr>
						<th>NO</th>
						<th>NAMA MATA KULIAH</th>
						<th>PROGRAM STUDI</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listMk as $dataMk) { ?>
					<tr onclick="insVal('<?php echo $this->readyCaller;?>', new Array('<?php echo escQuoteJS($dataMk['id_mk']);?>','<?php echo escQuoteJS($dataMk['nm_mk']);?>'))">
						<td><?php echo $i; ?></td>
						<td><?php echo $dataMk['nm_mk']; ?></td>
						<td><?php echo $dataMk['nm_prodi']; ?></td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<script>$(function () {tabel('tbmk',true,true,true,true,true,false);});</script>