<?php echo $this->render('helper/function.phtml');?>
<div class="box  box-info">
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbmenu" class="table table-bordered table-hover" style="cursor: pointer;">
				<thead align="center">
					<tr>
						<th>NO</th>
						<th>KODE AKSES</th>
						<th>AKSES MENU</th>
						<th>URL</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listMenu as $dataMenu) { ?>
					<tr onclick="insVal('<?php echo $this->readyCaller;?>', new Array('<?php echo escQuoteJS($dataMenu['id']);?>','<?php echo escQuoteJS($dataMenu['nama_menu']);?>'))">
						<td><?php echo $i; ?></td>
						<td><?php echo $dataMenu['id']; ?></td>
						<td><?php echo $dataMenu['nama_menu']; ?></td>
						<td><?php echo $dataMenu['url']; ?></td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<script>$(function () {tabel('tbmenu',true,true,true,true,true,false);});</script>