<?php echo $this->render('helper/function.phtml');?>
<div class="box  box-info">
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbroom" class="table table-bordered table-hover" style="cursor: pointer;">
				<thead align="center">
					<tr>
						<th>KODE RUANGAN</th>
						<th>RUANGAN</th>
						<th>KAPASITAS</th>
						<th>KAPASITAS UJIAN</th>
						<th>KATEGORI RUANGAN</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listRuangan as $data) { ?>
					<tr onclick="insVal('<?php echo $this->readyCaller;?>', new Array('<?php echo escQuoteJS($data['kd_ruangan']);?>','<?php echo escQuoteJS($data['nm_ruangan']);?>'))">
						<td><?php echo $data['kd_ruangan']; ?></td>
						<td><?php echo $data['nm_ruangan']; ?></td>
						<td align="center"><?php echo $data['kapasitas']; ?></td>
						<td align="center"><?php echo $data['kapasitas_ujian']; ?></td>
						<td><?php echo $data['kat_ruangan']; ?></td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<script>$(function () {tabel('tbroom',true,true,true,true,true,true);});</script>