 <link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/plugins/fullcalendar/fullcalendar.min.css">
 <link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/plugins/fullcalendar/fullcalendar.print.css" media="print">
 <div class="box  box-info">
 	<div class="box-header with-border">
 		<h4>Selamat Datang <?php echo $this->namauser;?></h4>
 	</div>
 </div>
 <div class="row">
 	<div class="col-md-3 col-sm-6 col-xs-12">
 		<div class="info-box">
 			<span class="info-box-icon bg-blue" style="padding:20px;">
 				<i class="ion ion-ios-people-outline"></i>
 			</span>
 			<div class="info-box-content">
 				<span class="info-box-text">Mahasiswa Aktif</span>
 				<span class="info-box-number"><?php echo number_format($this->nMhsA,0,',','.');?></span>
 			</div>
 		</div>
 	</div>
 	<div class="col-md-3 col-sm-6 col-xs-12">
 		<div class="info-box">
 			<span class="info-box-icon bg-green" style="padding:20px;">
 				<i class="ion-person-stalker"></i>
 			</span>
 			<div class="info-box-content">
 				<span class="info-box-text">Dosen Aktif</span>
 				<span class="info-box-number"><?php echo number_format($this->nDsnA,0,',','.');?></span>
 			</div>
 		</div>
 	</div>
 	<div class="col-md-3 col-sm-6 col-xs-12">
 		<div class="info-box">
 			<span class="info-box-icon bg-yellow" style="padding:20px;">
 				<i class="ion-ios-albums-outline"></i>
 			</span>
 			<div class="info-box-content">
 				<span class="info-box-text">Paket Kelas</span>
 				<span class="info-box-number"><?php echo number_format($this->nPklsAll,0,',','.');?></span>
 			</div>
 		</div>
 	</div>
 	<div class="col-md-3 col-sm-6 col-xs-12">
 		<div class="info-box">
 			<span class="info-box-icon bg-red" style="padding:20px;">
 				<i class="ion-checkmark-circled"></i>
 			</span>
 			<div class="info-box-content">
 				<span class="info-box-text">KRS Approved</span>
 				<span class="info-box-number"><?php echo number_format($this->nKuliah,0,',','.');?></span>
 			</div>
 		</div>
 	</div>
</div>
<div class="box  box-info">
 	<div class="box-body">
 		<div class="col-md-6">
 			<h5 class="callout callout-warning"><i class="icon fa fa-user"></i>&nbsp;&nbsp;Akses</h5>
	 		<div class="table-responsive">
				<table id="tbmenu" class="table table-bordered table-hover table-striped">
					<thead align="center">
						<tr>
							<th>AKSES MENU</th>
							<th>URL</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->listMenu as $dataMenu) { ?>
						<tr>
							<td><?php echo $dataMenu['nama_menu']; ?></td>
							<td><?php echo $dataMenu['url']; ?></td>
						</tr>
						<?php } ?>
				</table>
			</div>
		</div>
	 	<div class="col-md-6 pull-right">
	 		<h5 class="callout callout-info"><i class="icon fa fa-calendar"></i>&nbsp;&nbsp;<?php echo $this->perAktif." (".$this->tglPer.")";?></h5>
	 		<div class="box box-primary">
	 			<div class="box-body no-padding">
	 				<div id="calendar"></div>
	 			</div>
	 		</div>
        </div>
	</div>
</div>
<script src="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/moment.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/plugins/fullcalendar/fullcalendar.min.js"></script>
<script>
  $(function () {
    var date = new Date();
    var d = date.getDate(),
        m = date.getMonth(),
        y = date.getFullYear();
    $('#calendar').fullCalendar({
      header: {
        left: 'prev, today',
        center: 'title',
        right : 'next'
      },
      buttonText: {
        today: 'today'
      },
      events: <?php echo $this->listKal;?>
    });
  });
</script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbmenu',true,false,true,false,false,false);});</script>