<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Data Tugas</h3>
</div>
<div class="inqbox-content">
	<div class="panel panel-primary">
		<div class="panel-body">
			<div class="col-sm-2">Minggu</div>
			<div class="col-sm-10">: <?php echo $this->minggu;?></div>
			<div class="col-sm-2">Judul Tugas</div>
			<div class="col-sm-10">: <?php echo $this->jdl;?></div>
			<div class="col-sm-2">Instruksi Tugas</div>
			<div class="col-sm-10">: <?php echo $this->knt;?></div>
			<div class="col-sm-2">Diterbitkan</div>
			<div class="col-sm-10">: <?php echo $this->tgl1;?></div>
			<div class="col-sm-2">Deadline</div>
			<div class="col-sm-10">: <?php echo $this->tgl2;?></div>
			<div class="col-sm-2">Nama File</div>
			<div class="col-sm-10">: <?php echo $this->file;?></div>
			<div class="col-sm-2">Link</div>
			<div class="col-sm-10">: <?php echo $this->link;?></div>
			<div class="col-sm-2">Kontributor</div>
			<div class="col-sm-10">: <?php echo $this->nm_dosen;?></div>
		</div>
	</div>
	<?php if($this->allowInput!=1){?>
	<h5 class="alert alert-danger"><i class="icon fa fa-warning"></i>&nbsp;&nbsp;Anda tidak dapat mengentri/mengubah nilai di luar jadwal entri nilai. Silakan hubungi Administrator!</h5>
	<?php } ?>
	<div class="table-responsive">
	<?php if($this->allowInput==1){?>
	<div>
		<h5 class="alert alert-info">
			<i class="icon fa fa-info-circle"></i>
			<ul>
				<li>Klik pada tombol "Generate Template" untuk mendapatkan daftar nilai mahasiswa dalam bentuk file excel</li>
				<li>Pada file excel yang sudah ter-download, edit nilai-nilai mahasiswa pada sel yang berwarna abu-abu saja. Adapaun NIM, angkatan dan nama mahasiswa tidak perlu diubah-ubah</li>
				<li>Setelah pengeditan selesai, simpan perubahan file, klik tombol pilih file, kemudian cari file yang sudah diedit tadi, kemudian klik tombol upload</li>
			</ul>
		</h5>
	</div>
	<div class="col-sm-6">
		<form class="form-horizontal" method="post" id="frm2" enctype="multipart/form-data">
			<div class="box-body">
				<div class="form-group">
					<label class="col-sm-4 control-label">Template Nilai</label>
					<div class="col-sm-8">
						<button type="button" onclick="nav('<?php echo $this->baseUrl;?>/tugas/exportdetil?id=<?php echo $this->id_tugas;?>')" class="btn btn-success col-sm-6">Generate Template</button>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-4 control-label">File Nilai</label>
					<div class="col-sm-8">
						<input type="file" id="fileToUpload" name="fileToUpload" accept="application/vnd.ms-excel" >
					</div>
				</div>
				<div><?php echo $this->msg;?></div>
				<div class="box-footer">
					<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
					<button type="button" id="upload" class="btn btn-primary pull-right col-sm-2">Upload</button>
				</div>
			</div>
		</form>
	</div>
	<?php } ?>
	<form class="form-horizontal" method="post" id="frm">
		<?php if($this->allowInput==1){?>
		<div class="box-header col-sm-12">
			<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan Nilai</button>
			<br><br><br>
		</div>
		<?php } ?>
		<table id="tbkls" class="table table-bordered table-hover">
			<thead align="center">
				<tr>
					<th width="5%">NO</th>
					<th width="10%">NIM</th>
					<th width="18%">NAMA MAHASISWA</th>
					<th width="8%">ANGKATAN</th>
					<th width="12%">RESPON</th>
					<th>TUGAS DIKIRIM</th>
					<th width="10%">NILAI</th>
					<th width="10%">AKSI</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=1;$n=0;foreach ($this->listTugasMhs as $dataTugas) { ?>
				<tr>
					<td><?php echo $i; ?></td>
					<td><?php echo $dataTugas['nim']; ?></td>
					<td><?php echo $dataTugas['nm_mhs']; ?></td>
					<td align="center"><?php echo $dataTugas['id_angkatan']; ?></td>
					<td><?php echo $dataTugas['respon']; ?></td>
					<td>
						<strong>Nama File</strong> : <?php echo $dataTugas['nm_file']; ?><br>
						<strong>Link</strong> : <a href="<?php echo $dataTugas['link']; ?>"><?php echo $dataTugas['link']; ?></a><br>
						<strong>Terkirim</strong> : <?php echo $dataTugas['created']; ?>
					</td>
					<td align="center">
						<?php if($this->allowInput!=1){?>
						<?php echo number_format($dataTugas['nilai'],2,',','.'); ?>
						<?php }else{ ?>
						<input type="hidden" id="id_tgs_mhs_<?php echo $n;?>" value="<?php echo $dataTugas['id_tugas_mhs'];?>">
						<input type="number" class="form-control" id="nl_<?php echo $n;?>" placeholder="0.00" value="<?php echo $dataTugas['nilai'];?>">
						<?php } ?>
					</td>
					<td align="center">
						<?php 
            					    $arrFile=explode(".",$dataTugas['nm_file']);
        	    				    $ext=end($arrFile);
	            				?>
						<button type="button" class="btn btn-info btn-sm" onclick="nav('<?php echo $this->baseUrl;?>/image/anyfile?url=public/file/tugasmhs/<?php echo $dataTugas['id_tugas_mhs'].".".$ext?>&newname=<?php echo $dataTugas['nm_file'];?>')"><i class="fa fa-download"></i></button>
					</td>
				</tr>
				<?php $i++; $n++;} ?>
				<input type="hidden" id="n" value="<?php echo $n;?>">
		</table>
		<?php if($this->allowInput==1){?>
		<div class="box-footer col-sm-12">
			<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan Nilai</button>
		</div>
		<?php } ?>
	</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/updnltugas","/tugas/detil?id=<?php echo $this->id_tugas;?>&new=","u");
	  return false;
});
</script>
<script>
$('#upload').on('click', function() {
  ajaxUpload('fileToUpload','<?php echo $this->baseUrl;?>','/ajax/uplnltugas');
});
</script>