<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Data Rencana Studi</h3>
</div>
<div class="inqbox-content">
	<?php if($this->allowReg==1){?>
	<div class="alert alert-info">
		<strong><i class="icon fa fa-info-circle"></i>&nbsp;&nbsp;PETUNJUK PENGISIAN FORM PKRS</strong>
		<ul>
			<li><strong>FORM PKRS</strong> adalah form yang digunakan untuk melakukan perubahan pada KRS</li>
			<li>Form ini akan mencatat perubahan KRS Anda baik itu <strong>MENAMBAH, DROP MAUPUN UBAH SKS</strong> Mata Kuliah yang sudah diapprove oleh Dosen Wali pada masa KRS</li>
			<li>KRS menampilkan mata kuliah kelas, tetapi untuk menambahkan mata kuliah khusus TA, masuk ke menu <a class="btn btn-primary btn-sm" onclick="nav('<?php echo $this->baseUrl ?>/pkrsta/index?per=<?php echo $this->per;?>')">PKRS Mata Kuliah TA (klik di sini)</a></li>
			<li>Cara menambah mata kuliah, mengubah SKS maupun menghapus mata kuliah <strong>SAMA DENGAN KRS</strong></li>
			<li>Hanya saja, ketika Anda menambah, menghapus ataupun mengubah SKS pada KRS, <strong>KRS tidak akan berubah seketika</strong>, tetapi <strong>perubahan disimpan dahulu pada tabel Form PKRS</strong></li>
			<li>Jika Dosen Wali approve PKRS Anda, maka perubahan akan berdampak pada KRS Anda</li>
			<li>Selama masa PKRS, Anda diperkenankan untuk membatalkan perubahan KRS sebelum disetujui oleh dosen wali dengan klik tombol <label class="label label-danger">Batal</label></li>
			<li>Setelah masa PKRS berakhir, maka Anda tidak dapat mengubah kembali kartu studi Anda</li>
		</ul>
	</div>
	<?php }else{?>
	<div class="alert alert-danger">Periode Akademik ini tidak diperkenankan untuk PKRS</div>	
	<?php }?>
	<div class="panel panel-primary">
		<div class="panel-body">
			<div class="col-md-4">Periode Akademik</div>
			<div class="col-md-8">: <?php echo $this->per;?></div>
			<div class="col-md-4">NIM</div>
			<div class="col-md-8">: <?php echo $this->nim;?></div>
			<div class="col-md-4">Nama Mahasiswa</div>
			<div class="col-md-8">: <?php echo $this->nm_mhs;?></div>
			<div class="col-md-4">Angkatan</div>
			<div class="col-md-8">: <?php echo $this->akt;?></div>
			<div class="col-md-4">Prodi</div>
			<div class="col-md-8">: <?php echo $this->prd;?></div>
			<div class="col-md-4">Dosen Wali</div>
			<div class="col-md-8">: <?php echo $this->dw;?></div>
		</div>
	</div>
</div>
<div class="inqbox-content">
	<h4 align="center">Form PKRS</h4>
	<div class="table-responsive">
		<table id="tbkrs" class="table table-bordered table-hover">
			<tr class="bg-maroon" align="center">
				<td rowspan="3" width="5%">No</td>
				<td colspan="4">Mata Kuliah</td>
				<td colspan="2">Dosen</td>
				<td rowspan="3">Nama Kelas</td>
				<td rowspan="3" width="5%">Perubahan</td>
				<td rowspan="3" width="5%">Status Approve Dosen Wali</td>
				<td rowspan="3" width="5%">Aksi</td>
			</tr>
			<tr class="bg-maroon" align="center">
				<td width="8%" rowspan="2">Kode Mata Kuliah</td>
				<td width="18%" rowspan="2">Nama Mata Kuliah</td>
				<td colspan="2">* SKS</td>
				<td width="10%" rowspan="2">Kode Dosen</td>
				<td width="20%" rowspan="2">Nama Dosen</td>
			</tr>
			<tr class="bg-maroon" align="center">
				<td width="5%">Default</td>
				<td width="7%">* Taken</td>
			</tr>
			<?php $i=1;foreach ($this->listPkrs as $dtPkrs) { ?>
			<tr>
				<td align="center"><?php echo $i;?></td>
				<td><?php echo $dtPkrs['kode_mk'];?></td>
				<td><?php echo $dtPkrs['nm_mk'];?></td>
				<td align="center"><?php echo $dtPkrs['sks_tm']+$dtPkrs['sks_prak']+$dtPkrs['sks_prak_lap']+$dtPkrs['sks_sim'];?></td>
				<?php if(($dtPkrs['mode']=="i")and($dtPkrs['executed']==0)and($this->allowReg==1)){?>
					<td align="center"><a class="badge bg-aqua" onclick="nav('<?php echo $this->baseUrl;?>/pkrs/editsks?nim=<?php echo $dtPkrs['nim'];?>&pkt=<?php echo $dtPkrs['kd_paket_kelas']?>')"><?php echo $dtPkrs['sks_tm']+$dtPkrs['sks_prak']+$dtPkrs['sks_prak_lap']+$dtPkrs['sks_sim']-$dtPkrs['sks_deducted'];?></a></td>
				<?php }else{?>
				<td align="center"><?php echo $dtPkrs['sks_tm']+$dtPkrs['sks_prak']+$dtPkrs['sks_prak_lap']+$dtPkrs['sks_sim']-$dtPkrs['sks_deducted'];?></td>
				<?php }?>
				<td align="center"><?php echo $dtPkrs['kd_dosen'];?></td>
				<td><?php echo $dtPkrs['nm_dosen'];?></td>
				<td align="center"><?php echo $dtPkrs['nm_kelas'];?></td>
				<?php 
					if($dtPkrs['mode']=='i'){
						$mode="TAMBAH";
					}elseif ($dtPkrs['mode']=='d'){
						$mode="DROP";
					}elseif ($dtPkrs['mode']=='u'){
						$mode="UBAH SKS";
					}else{
						$mode="-";
					}
					if($dtPkrs['executed']=='0'){
						$appPkrs="NOT APPROVED";
					}elseif ($dtPkrs['executed']=='1'){
						$appPkrs="APPROVED";
					}else{
						$appPkrs="NOT APPROVED";
					}
				?>
				<td align="center"><?php echo $mode;?></td>
				<td align="center"><?php echo $appPkrs;?></td>
				<td align="center">
					<?php if(($dtPkrs['executed']==0)and($this->allowReg==1)){ ?>
					<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah anda yakin membatalkan PKRS <b><?php echo str_replace("'", "\'", $dtPkrs['nm_mk']);?></b>','<?php echo $this->baseUrl;?>','/ajax/delpkrs',new Array('<?php echo $dtPkrs['nim'];?>','<?php echo $dtPkrs['kd_paket_kelas'];?>'))">Batal</button>
					<?php }else{ ?>
					<?php } ?>
				</td>
			</tr>
			<?php $i++;}?>
			<?php $j=$i;foreach ($this->listPkrsTA as $dtPkrsTA) { ?>
			<tr>
				<td align="center"><?php echo $i;?></td>
				<td><?php echo $dtPkrsTA['kode_mk'];?></td>
				<td><?php echo $dtPkrsTA['nm_mk'];?></td>
				<td align="center"><?php echo $dtPkrsTA['sks_tm']+$dtPkrsTA['sks_prak']+$dtPkrsTA['sks_prak_lap']+$dtPkrsTA['sks_sim'];?></td>
				<td align="center"><?php echo $dtPkrsTA['sks_tm']+$dtPkrsTA['sks_prak']+$dtPkrsTA['sks_prak_lap']+$dtPkrsTA['sks_sim']-$dtPkrsTA['sks_deducted'];?></td>
				<td align="center"><?php echo $dtPkrsTA['kd_dosen'];?></td>
				<td><?php echo $dtPkrsTA['nm_dosen'];?></td>
				<td align="center"><?php echo $dtPkrsTA['nm_kelas'];?> (Periode Mulai:<?php echo $dtPkrsTA['kd_periode_mulai'];?>)</td>
				<?php 
					if($dtPkrsTA['mode']=='i'){
						$mode="TAMBAH";
					}elseif ($dtPkrsTA['mode']=='d'){
						$mode="DROP";
					}elseif ($dtPkrsTA['mode']=='u'){
						$mode="UBAH SKS";
					}else{
						$mode="-";
					}
					if($dtPkrsTA['executed']=='0'){
						$appPkrs="NOT APPROVED";
					}elseif ($dtPkrsTA['executed']=='1'){
						$appPkrs="APPROVED";
					}else{
						$appPkrs="NOT APPROVED";
					}
				?>
				<td align="center"><?php echo $mode;?></td>
				<td align="center"><?php echo $appPkrs;?></td>
				<td align="center">
					<?php if($dtPkrsTA['executed']!=0){ ?>
					<?php }else{ ?>
					<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah anda yakin membatalkan PKRS <b><?php echo str_replace("'", "\'", $dtPkrsTA['nm_mk']);?></b>','<?php echo $this->baseUrl;?>','/ajax/delpkrs',new Array('<?php echo $dtPkrsTA['nim'];?>','<?php echo $dtPkrsTA['kd_paket_kelas'];?>'))">Batal</button>
					<?php } ?>
				</td>
			</tr>
			<?php $j++;}?>
		</table>
	</div>
</div>
<form method="post" id="frm">
	<div class="inqbox-content">
		<h4 align="center">Tabel Kartu Studi Mahasiswa</h4>
		<div class="table-responsive">
			<table id="tbkrs" class="table table-bordered table-hover">
				<tr class="bg-maroon" align="center">
					<td rowspan="3" width="5%">No</td>
					<td colspan="4">Mata Kuliah</td>
					<td colspan="2">Dosen</td>
					<td rowspan="3">Nama Kelas</td>
					<td rowspan="3" width="10%">Status Approve Dosen Wali</td>
					<td rowspan="3" width="10%">Aksi</td>
				</tr>
				<tr class="bg-maroon" align="center">
					<td width="8%" rowspan="2">Kode Mata Kuliah</td>
					<td width="18%" rowspan="2">Nama Mata Kuliah</td>
					<td colspan="2">* SKS</td>
					<td width="10%" rowspan="2">Kode Dosen</td>
					<td width="20%" rowspan="2">Nama Dosen</td>
				</tr>
				<tr class="bg-maroon" align="center">
					<td width="5%">Default</td>
					<td width="7%">* Taken</td>
				</tr>
				<?php $i=1;$totSksDef=0;$totSksTaken=0;$totSksTakenApp=0;foreach ($this->listKuliah as $dataKuliah){ ?>
				<tr>
					<td align="center"><?php echo $i ?></td>
					<td><?php echo $dataKuliah['kode_mk'] ?></td>
					<td><?php echo $dataKuliah['nm_mk'] ?></td>
					<td align="center"><?php echo ($dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']);?></td>
					<?php if($this->allowReg==1){?>
					<td align="center"><a class="badge bg-aqua" onclick="nav('<?php echo $this->baseUrl;?>/pkrs/edit?id=<?php echo $dataKuliah['kd_kuliah'];?>')"><?php echo $dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']-$dataKuliah['sks_deducted'];?></a></td>
					<?php }else{?>
					<td align="center"><?php echo $dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']-$dataKuliah['sks_deducted'];?></td>
					<?php }?>
					<td align="center"><?php echo $dataKuliah['kd_dosen'];?></td>
					<td><?php echo $dataKuliah['nm_dosen'] ?></td>
					<td align="center"><?php echo $dataKuliah['nm_kelas'];?></td>
					<?php
						if($dataKuliah['approved']=='t'){
							$ap = "APPROVED";
							$totSksTakenApp=$totSksTakenApp+($dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']-$dataKuliah['sks_deducted']);
						}else{
							$ap = "NOT-APPROVED";
						}
						?>
					<td align="center"><?php echo $ap;?></td>
					<td align="center">
						<?php if($this->allowReg==1){?>
						<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah anda yakin menghapus mata kuliah <b><?php echo str_replace("'", "\'", $dataKuliah['nm_mk']);?></b>','<?php echo $this->baseUrl;?>','/ajax/inspkrsdrop',new Array('<?php echo $dataKuliah['nim'];?>','<?php echo $dataKuliah['kd_paket_kelas'];?>','<?php echo $dataKuliah['sks_deducted'];?>'))"><i class="fa fa-remove"></i></button>
						<?php } ?>
					</td>
				</tr>
				<?php $totSksDef=$totSksDef+($dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']);$totSksTaken=$totSksTaken+($dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']-$dataKuliah['sks_deducted']);$i++;}?>
				<?php $j=$i;$totSksDefTA=0;$totSksTakenTA=0;$totSksTakenTAApp=0;foreach ($this->listKuliahTA as $dataKuliahTA){ ?>
				<tr>
					<td align="center"><?php echo $j ?></td>
					<td><?php echo $dataKuliahTA['kode_mk'] ?></td>
					<td><?php echo $dataKuliahTA['nm_mk'] ?></td>
					<td align="center"><?php echo ($dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']);?></td>
					<td align="center"><?php echo $dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']-$dataKuliahTA['sks_deducted'];?></td>
					<td align="center"><?php echo $dataKuliahTA['kd_dosen'];?></td>
					<td><?php echo $dataKuliahTA['nm_dosen'] ?></td>
					<td align="center"><?php echo $dataKuliahTA['nm_kelas'];?> (Periode Mulai : <?php echo $dataKuliahTA['kd_periode_mulai'];?>)</td>
					<?php
						if($dataKuliahTA['approved']=='t'){
							$ap = "APPROVED";
							$totSksTakenTAApp=$totSksTakenTAApp+($dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']-$dataKuliahTA['sks_deducted']);
						}else{
							$ap = "NOT-APPROVED";
						}
						?>
					<td align="center"><?php echo $ap;?></td>
					<td align="center">
					<?php if($this->allowReg==1){?>
					<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah anda yakin menghapus mata kuliah <b><?php echo str_replace("'", "\'", $dataKuliahTA['nm_mk']);?></b>','<?php echo $this->baseUrl;?>','/ajax/inspkrsdrop?ta=1',new Array('<?php echo $dataKuliahTA['nim'];?>','<?php echo $dataKuliahTA['kd_paket_kelas'];?>','<?php echo $dataKuliahTA['sks_deducted'];?>','<?php echo $dataKuliahTA['kd_periode_mulai']?>'))"><i class="fa fa-remove"></i></button>
					<?php }?>
					</td>
				</tr>
				<?php $totSksDefTA=$totSksDefTA+($dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']);$totSksTakenTA=$totSksTakenTA+($dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']-$dataKuliahTA['sks_deducted']);$j++;}?>
				<tr class="bg-maroon">
					<td align="center" colspan="3"><b>Jumlah</b></td>
					<td align="center"><?php echo $totSksDef+$totSksDefTA;?></td>
					<td align="center"><?php echo $totSksTaken+$totSksTakenTA;?></td>
					<td colspan="3"><strong>Jumlah SKS Approved</strong></td>
					<td align="center"><strong><?php echo $totSksTakenApp+$totSksTakenTAApp;?></strong></td>
					<td></td>
				</tr>	
			</table>
		</div>
		<?php if($this->allowReg==1){?>
		<div class="form-group">
			<button type="submit" id="sb" class="btn btn-primary">Tambah Paket Kelas</button>
			<button type="reset" class="btn btn-default">Reset</button>
			<input type="hidden" id="key" value="nim">
			<input type="hidden" id="nim" value="<?php echo $this->nim;?>">
			<input type="hidden" id="per" value="<?php echo $this->per;?>">
			<button type="button" class="btn btn-success pull-right" onclick="hbox('<?php echo $this->baseUrl;?>','helper/jadwal',new Array('nim','per'), new Array('key','nim','per'))">Lihat Jadwal</button>
		</div>
		<?php }?>
	</div>
	<?php if($this->allowReg==1){?>
	<div class="inqbox-content">
		<div class="table-responsive">
			<h4 align="center">Tabel Paket Kelas, Periode <?php echo $this->per;?></h4>
			<table id="tbpkls" class="table table-bordered table-hover">
				<thead>
					<tr>
						<th>*</th>
						<th>Nama Kelas</th>
						<th>Nama Dosen</th>
						<th>Mata Kuliah</th>
						<th>Semester</th>
						<th>SKS</th>
						<th>Jadwal</th>
					</tr>
				</thead>
				<input type="hidden" id="n" value="<?php echo count($this->listPaketkelas)-count($this->listKuliah);?>">
				<?php $n=0;$i=1;foreach ($this->listPaketkelas as $baris):?>
				<?php
					$j=0;
					foreach ($this->listKuliah as $dataKuliah){
						if($dataKuliah['kd_paket_kelas']==$baris['kd_paket_kelas']){
							$j++;
						}
					}
					?>
				<?php if($j==0){ ?>
				<tbody>
					<tr>
						<td><input type="checkbox" id="cbpk_<?php echo $n;?>" value="<?php echo $baris['kd_paket_kelas'] ?>" cbpk><input type="text" style="display:none;" id="paket_<?php echo $n;?>"></td>
						<td>
							<input type="hidden" id="key2" value="pkt">
							<input type="hidden" id="pk_<?php echo $n;?>" value="<?php echo $baris['kd_paket_kelas'];?>">
							<input type="hidden" id="per_pkt" value="<?php echo $this->per;?>">
							<?php echo $baris['nm_kelas']." (".$baris['jns_kelas'].")";?>
						</td>
						<td><?php echo $baris['nm_dosen'] ?></td>
						<td><?php echo $baris['nm_mk'] ?></td>
						<td align="center"><?php echo $baris['smt_def'] ?></td>
						<td align="center"><?php echo $baris['sks_tm']+$baris['sks_prak']+$baris['sks_prak_lap']+$baris['sks_sim'] ?></td>
						<td align="center">
							<button type="button" class="btn btn-success pull-right" onclick="hbox('<?php echo $this->baseUrl;?>','helper/jadwal',new Array('paket_<?php echo $n;?>','per_pkt'), new Array('key2','pk_<?php echo $n;?>','per_pkt'))">Lihat Jadwal</button>
						</td>
					</tr>
					<?php $n++;} ?>
					<?php $i++;endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
	<?php }?>
</form>
<script>
	$("[cbpk]").on('change',(function() {
		id=$(this).attr('id');
		n= id.split('_');
		if($(this).is(':checked')){
			$("#paket_"+n[1]).val($(this).val());
		}else{
			$("#paket_"+n[1]).val('');
		}
	}))
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/inspkrsadd","/pkrs?new=","u");
	  return false;
	});
</script>