<div class="inqbox-title border-top-danger">
	 <h5>Form Pengajuan Judul Mata Kuliah <?php echo $this->nm_mk;?></h5>
</div>
<div class="inqbox-content">
	<form method="post" id="frm" class="form-horizontal"> 
 		<div class="form-group">
 			<label class="col-sm-2 control-label">Judul</label>
 			<div class="col-sm-6">
 				<input type="text" id="kd_kuliah" value="<?php echo $this->kd_kuliah;?>" style="display:none;">
				<textarea rows="6" cols="300" class="form-control" id="judul"></textarea>
 			</div>
 		</div>
 		<div class="form-group">
 			<div class="col-sm-4 col-sm-offset-2">
 				<button class="btn btn-white" type="reset">Reset</button>
 				<button class="btn btn-primary" type="submit">Submit</button>
 			</div>
 		</div>
	</form>
</div>
<div class="inqbox-content">
	<div class="table-responsive">
		<table id="tbkur" class="table table-bordered table-hover">
			<tr>
				<th width="5%">No</th>
				<th>Judul</th>
				<th width="15%">Tanggal Diajukan</th>
				<th width="15%">Status</th>
				<th width="20%">Approver</th>
				<th width="5%">Aksi</th>
			</tr>
			<?php $j=1; foreach ($this->listJudul as $data) { ?>
			<tr>
				<td><?php echo $j;?></td>
				<td><?php echo $data['judul_ta'];?></td>
				<td><?php echo $data['created'];?></td>
				<td align="center"><?php echo $data['ket_status'];?></td>
				<td><?php echo $data['nm_dosen_approver'];?></td>
				<td align="center">
					<?php if($data['status']==0){ ?>
					<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin membatalkan pengajuan ini?','<?php echo $this->baseUrl;?>','/ajax/deljudulta', new Array ('<?php echo $data['id_judul_ta'];?>'))" >Batalkan</button>
					<?php } ?>
				</td>
			</tr>
			<?php $j++; } ?>
		</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/insjudulta","/judulta/new?id=<?php echo $this->kd_kuliah;?>&new=","u");
	  return false;
	});
</script>