<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="box box-info">
	<div class="box-header with-border" class="col-sm-2">
		<div class="col-sm-8">
			<strong>
			Kategori Ruangan : <?php echo $this->katRoom;?>
			</strong>
		</div>
	</div>
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbroom" class="table table-bordered table-hover">
				<thead align="center">
					<tr>
						<th>KODE RUANGAN</th>
						<th>RUANGAN</th>
						<th>KAPASITAS</th>
						<th>KAPASITAS UJIAN</th>
						<th>KATEGORI RUANGAN</th>
						<th>AKSI</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listRuangan as $data) { ?>
					<tr>
						<td><?php echo $data['kd_ruangan']; ?></td>
						<td><?php echo $data['nm_ruangan']; ?></td>
						<td align="center"><?php echo $data['kapasitas']; ?></td>
						<td align="center"><?php echo $data['kapasitas_ujian']; ?></td>
						<td><?php echo $data['kat_ruangan']; ?></td>
						<td align="center">
							<button type="button" class="btn btn-warning btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/ruangan/edit?kd=<?php echo $data['kd_ruangan'];?>')"><i class="fa fa-pencil"></i></button>
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan menghapus ruangan ini ? <strong><?php echo str_replace("'", "\'", $data['nm_ruangan']);?></strong>','<?php echo $this->baseUrl;?>','/ajax2/delroom',new Array('<?php echo $data['kd_ruangan'];?>'))"><i class="fa fa-remove"></i></button>
						</td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<!-- DataTables -->
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbroom',true,true,true,true,true,false);});</script>