<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker-bs3.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Ruangan</h3>
	</div>
	<div class="box-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="box-body">
				<div class="form-group">
					<label class="col-sm-2 control-label">Kode Ruangan</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="kd" placeholder="kode ruangan" maxlength="20">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Nama Ruangan</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="nm" placeholder="nama ruangan" maxlength="60">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Kapasitas Ruangan</label>
					<div class="col-sm-4">
						<input type="number" class="form-control" id="kpsts" placeholder="kapasitas ruangan" min="1" max="200" step="1">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Kapasitas untuk Ujian</label>
					<div class="col-sm-4">
						<input type="number" class="form-control" id="kpsts_u" placeholder="kapasitas untuk ujian" min="0" max="200" step="1">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Kategori Ruangan</label>
					<div class="col-sm-4">
						<select class="form-control" id="id_kat">
							<option disabled value="" selected>pilih kategori ruangan</option>
							<?php foreach ($this->listKatRuangan as $dataKat) {?>
							<option value="<?php echo $dataKat['id_kat_ruangan'];?>"><?php echo $dataKat['kat_ruangan'];?></option>
							<?php } ?>
						</select>
					</div>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
					<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan</button>
				</div>
			</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
		kat = $('#id_kat').val();
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax2/insroom","/ruangan/list?kat="+kat+"&new=","i");
	  return false;
	});
</script>