<div class="table-header">
	Pra Registrasi Mahasiswa 
</div>
<div>
	<table id="tbl" class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th class="center" width="15%" rowspan="3">NIM</th>
				<th class="center" rowspan="3">Nama</th>
				<th class="center" width="15%" rowspan="3">Prodi/Angkatan</th>
				<th class="center" width="20%" rowspan="3">Status Pra Registrasi</th>
			</tr>
		</thead>
		<tbody>
			<?php $i=1;foreach ($this->listMhsReg as $dtMhsReg){?>
			<tr>
				<td><?php echo $dtMhsReg['nim'];?></td>
				<td><?php echo $dtMhsReg['nm_mhs'];?></td>
				<td class="center"><?php echo $dtMhsReg['nm_prodi']."/".$dtMhsReg['id_angkatan'];?></td>
				<?php if($dtMhsReg['status_reg']!=''){ ?>
				<td class="center"><?php echo $dtMhsReg['status_reg']."(".$dtMhsReg['status_mhs_periode'].")";?></td>
				<?php }else{ ?>
				<td align="center">Unregistered</td>
				<?php } ?>
			</tr>
			<?php $i++;}?>
		</tbody>
	</table>
</div>
<script src="<?php echo $this->baseUrl;?>/public/assets/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/assets/js/jquery.dataTables.bootstrap.min.js"></script>
<script>
$(document).ready(function() {
    $('#tbl').DataTable( {
        "scrollX": true
    } );
} );
</script>