<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Data Rencana Studi</h3>
</div>
<div class="inqbox-content">
	<?php if($this->allowReg==1){?>
	<div class="alert alert-info">
		<strong><i class="icon fa fa-info-circle"></i>&nbsp;&nbsp;PETUNJUK PERWALIAN</strong>
		<ul>
			<li>Selama masa KRS, Anda diperkenankan untuk melakukan approve terhadap KRS dari mahasiswa sdengan klik tombol <label class="label label-success">Approve</label></li>
			<li>Anda dapat membatalkan approve terhadap KRS dari mahasiswa sdengan klik tombol <label class="label label-warning">Disapprove</label></li>
			<li>Selama masa KRS, Anda dapat mengirimkan feedback perwalian kepada mahasiswa bersangkutan dengan mengisi form perwalian di bawah KRS</li>
			<li>Setelah masa KRS berakhir, maka Anda tidak dapat mengubah status approval kartu studi mahasiswa dan melakukan feedback perwalian</li>
		</ul>
	</div>
	<?php }else{?>
	<div class="alert alert-danger">Periode Akademik ini tidak diperkenankan untuk melakukan approve KRS ataupun Perwalian</div>	
	<?php }?>
	<div class="panel panel-primary">
		<div class="panel-body">
			<div class="col-md-4">Periode Akademik</div>
			<div class="col-md-8">: <?php echo $this->per;?></div>
			<div class="col-md-4">NIM</div>
			<div class="col-md-8">: <?php echo $this->nim;?></div>
			<div class="col-md-4">Nama Mahasiswa</div>
			<div class="col-md-8">: <?php echo $this->nm_mhs;?></div>
			<div class="col-md-4">Angkatan</div>
			<div class="col-md-8">: <?php echo $this->akt;?></div>
			<div class="col-md-4">Prodi</div>
			<div class="col-md-8">: <?php echo $this->prd;?></div>
			<div class="col-md-4">Dosen Wali</div>
			<div class="col-md-8">: <?php echo $this->dw;?></div>
		</div>
	</div>
</div>
<div class="inqbox-content">
	<h4 align="center">Tabel Kartu Studi Mahasiswa</h4>
	<div class="table-responsive">
		<form id="frm_krs" method="post">
		<table id="tbkrs" class="table table-bordered table-hover">
			<tr class="bg-maroon" align="center">
				<td rowspan="3" width="5%">No</td>
				<td colspan="4">Mata Kuliah</td>
				<td colspan="2">Dosen</td>
				<td rowspan="3">Nama Kelas</td>
				<td rowspan="3" width="10%">Status Approve Dosen Wali</td>
				<td width="8%">Aksi</td>
			</tr>
			<tr class="bg-maroon" align="center">
				<td width="8%" rowspan="2">Kode Mata Kuliah</td>
				<td width="18%" rowspan="2">Nama Mata Kuliah</td>
				<td colspan="2">* SKS</td>
				<td width="10%" rowspan="2">Kode Dosen</td>
				<td width="20%" rowspan="2">Nama Dosen</td>
				<td width="8%"><input type="submit" value="Approve" class="btn btn-success"></td>
			</tr>
			<tr class="bg-maroon" align="center">
				<td width="5%">Default</td>
				<td width="7%">* Taken</td>
				<td width="8%"><input type="checkbox" name="ckbCheckAll" id="ckbCheckAll" onclick="selectAll(this)"></td>
			</tr>
			<?php $x=0;$i=1;$totSksDef=0;$totSksTaken=0;$totSksTakenApp=0;foreach ($this->listKuliah as $dataKuliah){ ?>
			<tr>
				<td align="center"><?php echo $i ?></td>
				<td><?php echo $dataKuliah['kode_mk'] ?></td>
				<td><?php echo $dataKuliah['nm_mk'] ?></td>
				<td align="center"><?php echo ($dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']);?></td>
				<?php if($this->allowReg==1){?>
				<td align="center"><?php echo $dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']-$dataKuliah['sks_deducted'];?></td>
				<?php }else{?>
				<td align="center"><?php echo $dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']-$dataKuliah['sks_deducted'];?></td>
				<?php }?>
				<td align="center"><?php echo $dataKuliah['kd_dosen'];?></td>
				<td><?php echo $dataKuliah['nm_dosen'] ?></td>
				<td align="center"><?php echo $dataKuliah['nm_kelas'];?></td>
				<?php
					if($dataKuliah['approved']=='t'){
						$ap = "APPROVED";
						$totSksTakenApp=$totSksTakenApp+($dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']-$dataKuliah['sks_deducted']);
					}else{
						$ap = "NOT-APPROVED";
					}
					?>
				<td align="center"><?php echo $ap;?></td>
				<td align="center">
					<?php if($this->allowReg==1){?>
					<?php if($dataKuliah['approved']=='t'){ ?>
					<button type="button" class="btn btn-warning btn-xs" onclick="confirm('Apakah anda yakin mengubah status mata kuliah <b><?php echo str_replace("'", "\'", $dataKuliah['nm_mk']);?> menjadi DISAPPROVED?','<?php echo $this->baseUrl;?>','/ajax/updkrsstat',new Array('f','<?php echo $dataKuliah['kd_kuliah'];?>'))">Disapprove</button>
					<?php }else{ ?>
					<input type="checkbox" id="cbkul_<?php echo $x;?>" cbkul value="<?php echo $dataKuliah['kd_kuliah'];?>">
					<input type="text" style="display:none;" id="mk_<?php echo $x;?>" value="<?php echo $dataKuliah['nm_mk']?>">
					<input type="text" style="display:none;" id="kul_<?php echo $x;?>">
					<?php $x++;} ?>
					<?php } ?>
				</td>
			</tr>
			<?php $totSksDef=$totSksDef+($dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']);$totSksTaken=$totSksTaken+($dataKuliah['sks_tm']+$dataKuliah['sks_prak']+$dataKuliah['sks_prak_lap']+$dataKuliah['sks_sim']-$dataKuliah['sks_deducted']);$i++;}?>
			<?php $y=$x;$j=$i;$totSksDefTA=0;$totSksTakenTA=0;$totSksTakenTAApp=0;foreach ($this->listKuliahTA as $dataKuliahTA){ ?>
			<tr>
			<td align="center"><?php echo $j ?></td>
			<td><?php echo $dataKuliahTA['kode_mk'] ?></td>
			<td><?php echo $dataKuliahTA['nm_mk'] ?></td>
			<td align="center"><?php echo ($dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']);?></td>
			<td align="center"><?php echo $dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']-$dataKuliahTA['sks_deducted'];?></td>
			<td align="center"><?php echo $dataKuliahTA['kd_dosen'];?></td>
			<td><?php echo $dataKuliahTA['nm_dosen'] ?></td>
			<td align="center"><?php echo $dataKuliahTA['nm_kelas'];?> (Periode Mulai : <?php echo $dataKuliahTA['kd_periode_mulai'];?>)</td>
			<?php
				if($dataKuliahTA['approved']=='t'){
					$ap = "APPROVED";
					$totSksTakenTAApp=$totSksTakenTAApp+($dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']-$dataKuliahTA['sks_deducted']);
				}else{
					$ap = "NOT-APPROVED";
				}
				?>
			<td align="center"><?php echo $ap;?></td>
			<td align="center">
				<?php if($this->allowReg==1){?>
				<?php if($dataKuliahTA['approved']=='t'){ ?>
				<button type="button" class="btn btn-warning btn-xs" onclick="confirm('Apakah anda yakin mengubah status mata kuliah <b><?php echo str_replace("'", "\'", $dataKuliahTA['nm_mk']);?> menjadi DISAPPROVED?','<?php echo $this->baseUrl;?>','/ajax/updkrsstatta',new Array('f','<?php echo $dataKuliahTA['kd_kuliah'];?>'))">Disapprove</button>
				<?php }else{ ?>
				<input type="checkbox" id="cbkul_<?php echo $y;?>" cbkul value="<?php echo $dataKuliahTA['kd_kuliah'];?>">
				<input type="text" style="display:none;" id="mk_<?php echo $y;?>" value="<?php echo $dataKuliahTA['nm_mk']?>">
				<input type="text" style="display:none;" id="kul_<?php echo $y;?>">
				<?php $y++;} ?>
				<?php } ?>
			</td>
			</tr>
			<?php $totSksDefTA=$totSksDefTA+($dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']);$totSksTakenTA=$totSksTakenTA+($dataKuliahTA['sks_tm']+$dataKuliahTA['sks_prak']+$dataKuliahTA['sks_prak_lap']+$dataKuliahTA['sks_sim']-$dataKuliahTA['sks_deducted']);$j++;}?>
			<tr class="bg-maroon">
			<td align="center" colspan="3"><b>Jumlah</b><input type="hidden" value="<?php echo $y;?>" id="x"></td>
			<td align="center"><?php echo $totSksDef+$totSksDefTA;?></td>
			<td align="center"><?php echo $totSksTaken+$totSksTakenTA;?></td>
			<td colspan="3"><strong>Jumlah SKS Approved</strong></td>
			<td align="center"><strong><?php echo $totSksTakenApp+$totSksTakenTAApp;?></strong></td>
			<td></td>
			</tr>	
		</table>
		</form>
	</div>
</div>
<div class="inqbox-title border-top-danger">
	 <h5>Form Feedback Perwalian</h5>
</div>
<div class="inqbox-content">
	<?php if($this->allowReg==1){?>
		<form method="post" id="frm" class="form-horizontal"> 
			<div class="form-group">
 				<label class="col-sm-2 control-label">Periode Akademik</label>
 				<label class="col-sm-4"><?php echo $this->per;?></label>
 			</div>
 			<div class="form-group">
 				<label class="col-sm-2 control-label">Isi Feedback</label>
 				<div class="col-sm-4">
 					<input type="text" id="nim" value="<?php echo $this->nim;?>" style="display:none;">
 					<input type="text" id="per" value="<?php echo $this->per;?>" style="display:none;">
 					<input type="text" id="dw" value="<?php echo $this->dw;?>" style="display:none;">
 					<input type="text" id="nm_mhs" value="<?php echo $this->nm_mhs;?>" style="display:none;">
					<textarea rows="6" cols="300" class="form-control" id="isi"></textarea>
 				</div>
 			</div>
 			<div class="form-group">
 				<div class="col-sm-4 col-sm-offset-2">
 					<button class="btn btn-white" type="reset">Batal</button>
 					<button class="btn btn-primary" type="submit">Posting</button>
 				</div>
 			</div>
		</form>
	<?php }else{?>
	<div class="alert alert-warning">
		Saat ini (<strong><?php echo date("d F Y") ?></strong>) tidak dalam jadwal <strong>Perwalian</strong>
	</div>
	<?php }?>
</div>
<div class="inqbox-content">
	<?php foreach ($this->listPerwalian as $dtPerwalian){ ?>
	<div class="social-feed-separated">
		<div class="social-avatar">
			<a href="#">
				<?php if($dtPerwalian['asal_feedback']=='M'){?>
				<img alt="image" src="<?php echo $this->baseUrl;?>/image/png?url=public/file/mhs/foto/<?php echo $this->idmhs;?>.jpg" alt="Foto Mahasiswa" onerror="this.src='<?php echo $this->baseUrl;?>/image/png?url=public/file/mhs/foto/default.jpg'">
				<?php }else{?>
				<img alt="image" src="<?php echo $this->baseUrl;?>/image/png?url=public/file/dsn/foto/<?php echo $this->kd_dw;?>.jpg" alt="Foto Dosen" onerror="this.src='<?php echo $this->baseUrl;?>/image/png?url=public/file/dsn/foto/default.jpg'">
				<?php }?>
			</a>
		</div>
		<div class="social-feed-box">
			<div class="social-avatar">
				<a><?php echo $dtPerwalian['sender']." &gt; ".$dtPerwalian['receiver']?></a>
				<small class="text-muted"><?php echo $dtPerwalian['waktu_posting'];?> - <?php echo $dtPerwalian['tanggal_posting_fmt']?></small>
			</div>
			<div class="social-body">
				<p>
					<?php echo $dtPerwalian['isi_feedback'];?>
				</p>
			</div>
		</div>
	</div>
	<?php } ?>
</div>
<script>
	function selectAll(all){
		var checked = all.checked;
		var chkBoxes = document.getElementsByTagName("input");
		for (var counter=0;counter<chkBoxes.length;counter++) {
			chkBoxes[counter].checked = checked ;
		}
		var x=$("#x").val();
		for (i=0;i<x;i++){
			if($("#cbkul_"+i).is(':checked')){
				$("#kul_"+i).val($("#cbkul_"+i).val());
			}else{
				$("#kul_"+i).val('');
			}
		}
	}
</script>
<script>
	$("[cbkul]").on('change',(function() {
		id=$(this).attr('id');
		n= id.split('_');
		if($(this).is(':checked')){
			$("#kul_"+n[1]).val($(this).val());
		}else{
			$("#kul_"+n[1]).val('');
		}
	}))
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script>
	$("#frm_krs").submit(function() {
	  	ajaxSubmit("frm_krs","<?php echo $this->baseUrl;?>","/ajax/updkrsmass","/perwalian/new?nim=<?php echo $this->nim;?>&per=<?php echo $this->per;?>&new=","u");
	  	return false;
	});
</script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/inspwl","/perwalian/new?nim=<?php echo $this->nim;?>&per=<?php echo $this->per;?>&new=","u");
	  return false;
	});
</script>