<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/plugins/select2/select2.min.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/dist/css/AdminLTE.min.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker-bs3.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Filter</h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">Kategori Pengumuman</label>
				<div class="col-sm-4">
					<select id="id_announcement_kategori" class="form-control select2" multiple="multiple" data-placeholder="kategori pengumuman" sel-2>
						<?php foreach ($this->list_Kat as $dataKat) { ?>
						<option value="<?php echo $dataKat['id_announcement_kategori']; ?>"><?php echo $dataKat['announcement_kategori']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Dibuat Dari Tanggal *</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="tgl1" placeholder="dari tanggal" readonly>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Sampai Tanggal *</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="tgl2" placeholder="sampai tanggal" readonly>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="submit" class="btn btn-info pull-right col-sm-2">Search</button>
			</div>
		</div>
	</form>
</div>
<script src="<?php echo $this->baseUrl;?>/public/plugins/select2/select2.full.min.js"></script>
<script>
	$("[sel-2]").select2();
</script>
<script src="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/moment.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker.js"></script>
<script>
	$(function () {
	  $('#tgl1').daterangepicker({singleDatePicker:true,format:'DD MMMM YYYY'});
	  $('#tgl2').daterangepicker({singleDatePicker:true,format:'DD MMMM YYYY'});
	});
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
	    ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ancdsn/ashow","/ancdsn/list","s");
	    return false;
	  });
	});
</script>