<style type='text/css'>
	.h {font-weight : bold ; vertical-align: top; color:red }
	.hl {font-size: 13px; font-weight : bold ; vertical-align: top; color:red }
	.i {font-weight : bold ; vertical-align: top; }
        .desc { display: none; }
</style>
<script type='text/javascript'>
	function hide1() {
	   if (document.getElementById) { // DOM3 = IE5, NS6
		document.getElementById('f9').style.display = 'none';
		document.getElementById('f10').style.display = 'none';
		document.getElementById('f11').style.display = 'table-row';
		//document.getElementById('f12').style.display = 'table-row';
		document.getElementById('f13').style.display = 'table-row';
		document.getElementById('f14').style.display = 'table-row';
		document.getElementById('f15').style.display = 'table-row';
		document.getElementById('f16').style.display = 'table-row';
	   }
	   else {
		if (document.layers) { // Netscape 4
			document.f9.style.display = 'none';
			document.f10.style.display = 'none';
			document.f11.style.display = 'table-row';
			//document.f12.style.display = 'table-row';
			document.f13.style.display = 'table-row';
			document.f14.style.display = 'table-row';
			document.f15.style.display = 'table-row';
			document.f16.style.display = 'table-row';
		}
		else { // IE 4
			document.all.f9.style.display = 'none';
			document.all.f10.style.display = 'none';
			document.all.f11.style.display = 'table-row';
			//document.all.f12.style.display = 'table-row';
			document.all.f13.style.display = 'table-row';
			document.all.f14.style.display = 'table-row';
			document.all.f15.style.display = 'table-row';
			document.all.f16.style.display = 'table-row';
		}
	   }
	}
	function show1() {
	   if (document.getElementById) { // DOM3 = IE5, NS6
		document.getElementById('f9').style.display = 'table-row';
		document.getElementById('f10').style.display = 'table-row';
		document.getElementById('f11').style.display = 'table-row';
		//document.getElementById('f12').style.display = 'table-row';
		document.getElementById('f13').style.display = 'table-row';
		document.getElementById('f14').style.display = 'table-row';
		document.getElementById('f15').style.display = 'table-row';
		document.getElementById('f16').style.display = 'table-row';
	   }
	   else {
		if (document.layers) { // Netscape 4
			document.f9.style.display = 'table-row';
			document.f10.style.display = 'table-row';
			document.f11.style.display = 'table-row';
			//document.f12.style.display = 'table-row';
			document.f13.style.display = 'table-row';
			document.f14.style.display = 'table-row';
			document.f15.style.display = 'table-row';
			document.f16.style.display = 'table-row';
		}
		else { // IE 4
			document.all.f9.style.display = 'table-row';
			document.all.f10.style.display = 'table-row';
			document.all.f11.style.display = 'table-row';
			//document.all.f12.style.display = 'table-row';
			document.all.f13.style.display = 'table-row';
			document.all.f14.style.display = 'table-row';
			document.all.f15.style.display = 'table-row';
			document.all.f16.style.display = 'table-row';
		}
	   }
	}
	function hide2() {
	   if (document.getElementById) { // DOM3 = IE5, NS6
		document.getElementById('f11').style.display = 'none';
		//document.getElementById('f12').style.display = 'none';
		document.getElementById('f13').style.display = 'none';
		document.getElementById('f14').style.display = 'none';
		document.getElementById('f15').style.display = 'none';
		document.getElementById('f16').style.display = 'none';
	   }
	   else {
		if (document.layers) { // Netscape 4
			document.id.display = 'none';
			document.f11.style.display = 'none';
			//document.f12.style.display = 'none';
			document.f13.style.display = 'none';
			document.f14.style.display = 'none';
			document.f15.style.display = 'none';
			document.f16.style.display = 'none';
		}
		else { // IE 4
			document.all.f11.style.display = 'none';
			//document.all.f12.style.display = 'none';
			document.all.f13.style.display = 'none';
			document.all.f14.style.display = 'none';
			document.all.f15.style.display = 'none';
			document.all.f16.style.display = 'none';
		}
	   }
	}
	function show2() {
	   if (document.getElementById) { // DOM3 = IE5, NS6
		document.getElementById('f11').style.display = 'table-row';
		//document.getElementById('f12').style.display = 'table-row';
		document.getElementById('f13').style.display = 'table-row';
		document.getElementById('f14').style.display = 'table-row';
		document.getElementById('f15').style.display = 'table-row';
		document.getElementById('f16').style.display = 'table-row';
	   }
	   else {
		if (document.layers) { // Netscape 4
			document.id.display = 'none';
			document.f11.style.display = 'table-row';
			//document.f12.style.display = 'table-row';
			document.f13.style.display = 'table-row';
			document.f14.style.display = 'table-row';
			document.f15.style.display = 'table-row';
			document.f16.style.display = 'table-row';
		}
		else { // IE 4
			document.all.f11.style.display = 'table-row';
			//document.all.f12.style.display = 'table-row';
			document.all.f13.style.display = 'table-row';
			document.all.f14.style.display = 'table-row';
			document.all.f15.style.display = 'table-row';
			document.all.f16.style.display = 'table-row';
		}
	   }
	}
	function hide3() {
	   if (document.getElementById) { // DOM3 = IE5, NS6
		document.getElementById('f4').style.display = 'none';
		document.getElementById('f5').style.display = 'none';
		document.getElementById('f6').style.display = 'none';
		document.getElementById('f7').style.display = 'none';
		document.getElementById('f7a').style.display = 'none';
	   }
	   else {
		if (document.layers) { // Netscape 4
			document.id.display = 'none';
			document.f4.style.display = 'none';
			document.f5.style.display = 'none';
			document.f6.style.display = 'none';
			document.f7.style.display = 'none';
			document.f7a.style.display = 'none';
		}
		else { // IE 4
			document.all.f4.style.display = 'none';
			document.all.f5.style.display = 'none';
			document.all.f6.style.display = 'none';
			document.all.f7.style.display = 'none';
			document.all.f7a.style.display = 'none';
		}
	   }
	}
	function show3() {
	   if (document.getElementById) { // DOM3 = IE5, NS6
		document.getElementById('f4').style.display = 'table-row';
		document.getElementById('f5').style.display = 'table-row';
		document.getElementById('f6').style.display = 'table-row';
		document.getElementById('f7').style.display = 'table-row';
		document.getElementById('f7a').style.display = 'table-row';
	   }
	   else {
		if (document.layers) { // Netscape 4
			document.id.display = 'none';
			document.f4.style.display = 'table-row';
			document.f5.style.display = 'table-row';
			document.f6.style.display = 'table-row';
			document.f7.style.display = 'table-row';
			document.f7a.style.display = 'table-row';
		}
		else { // IE 4
			document.all.f4.style.display = 'table-row';
			document.all.f5.style.display = 'table-row';
			document.all.f6.style.display = 'table-row';
			document.all.f7.style.display = 'table-row';
			document.all.f7a.style.display = 'table-row';
		}
	   }
	}
</script>
<div class="inqbox-title border-top-danger">
	 <h5>Form Tracer ID</h5>
</div>
<div class="inqbox-content">
<form id="frm" method="post">
<table class='table table-striped table-responsive'>
	<tr>
		<td class='i'>Identitas<br /><span class='h'>f1</span></td>
		<td> Nomor Mahasiswa</td><td>:</td><td><input type='text'  id='nimhsmsmh'  name='nimhsmsmh' value='<?php echo $this->nim_mhs;?>' size='20' readonly="readonly"></td>
	</tr>
	<tr>
		<td class='h'><span class='h'></span></td><td>Kode PT</td>
		<td>:</td><td><input type='text' value='<?php echo $this->kd_pt;?>'  id='kdptimsmh'  name='kdptimsmh' size='20' readonly></td>
	</tr>
	<tr>
		<td class='h'><span class='h'></span></td><td>Tahun Lulus *</td>
		<td>:</td><td><input type='text' value='<?php echo $this->thn_keluar;?>'  id='tahun_lulus'  name='tahun_lulus' size='20' readonly="readonly"></td>
	</tr>
	<tr>
		<td class='h'><span class='h'></span></td>
		<td>Kode Prodi</td><td>:</td><td><input type='text' value='<?php echo $this->kd_prodi;?>'  id='kdpstmsmh'  name='kdpstmsmh' size='20'></td>
	</tr>
	<tr>
		<td class='h'><span class='h'></span></td>
		<td>Nama</td><td>:</td><td><input type='text' value='<?php echo $this->nama_mhs;?>'  id='nmmhsmsmh'  name='nmmhsmsmh' size='20'></td>
	</tr>
	<tr>
		<td class='h'><span class='h'></span></td>
		<td>Nomor Telepon/HP *</td><td>:</td><td><input type='text' value=''  id='telpomsmh'  name='telpomsmh' size='20'></td></tr><tr><td class='h'><span class='h'></span></td><td>Alamat Email *</td><td>:</td><td><input type='text' value=''  id='emailmsmh'  name='emailmsmh' size='40'></td>
	</tr>
</table>
<table>
	<tr id='f2'>
		<td class='h' width="5%">f2</td>
		<td valign='top' width="50%">Menurut anda seberapa besar penekanan pada metode pembelajaran di bawah ini dilaksanakan di program studi anda?</td>
		<td valign='top' width="1%">:</td>
		<td>
        	<table class='table table-striped table-responsive'>
        		<tr><td colspan='2'><b>Perkuliahan</b> <span class='hl'>f21</span></td></tr>
        		<tr>
        			<td>
        				<input type='radio'  class='v21'  name='f21' value='1'  > [1] Sangat Besar<br />
        				<input type='radio'  class='v21'  name='f21' value='2'  > [2] Besar<br />
        				<input type='radio'  class='v21'  name='f21' value='3'  > [3] Cukup Besar<br />
        				<input type='radio'  class='v21'  name='f21' value='4'  > [4] Kurang<br />
        				<input type='radio'  class='v21'  name='f21' value='5'  > [5] Tidak Sama Sekali<br />
        				<input type="hidden" id="v21">
        			</td>
        			<td><span class='hl'>f21</span></td>
        		</tr>
        	</table>
			<table class='table table-striped table-responsive'>
				<tr><td colspan='2'><b>Demonstrasi</b> <span class='hl'>f22</span></td></tr>
				<tr>
					<td>
						<input type='radio'  class='v22'  name='f22' value='1'  > [1] Sangat Besar<br />
				        <input type='radio'  class='v22'  name='f22' value='2'  > [2] Besar<br />
				        <input type='radio'  class='v22'  name='f22' value='3'  > [3] Cukup Besar<br />
				        <input type='radio'  class='v22'  name='f22' value='4'  > [4] Kurang<br />
				        <input type='radio'  class='v22'  name='f22' value='5'  > [5] Tidak Sama Sekali<br />
				        <input type="hidden" id="v22">				
					</td>
					<td><span class='hl'>f22</span></td>
				</tr>
        	</table>
			<table class='table table-striped table-responsive'>
				<tr><td colspan='2'><b>Partisipasi dalam proyek riset</b> <span class='hl'>f23</span></td></tr>
				<tr>
					<td>
	        			<input type='radio'  class='v23'  name='f23' value='1'  > [1] Sangat Besar<br />
	        			<input type='radio'  class='v23'  name='f23' value='2'  > [2] Besar<br />
	        			<input type='radio'  class='v23'  name='f23' value='3'  > [3] Cukup Besar<br />
	        			<input type='radio'  class='v23'  name='f23' value='4'  > [4] Kurang<br />
	        			<input type='radio'  class='v23'  name='f23' value='5'  > [5] Tidak Sama Sekali<br />
	        			<input type="hidden" id="v23">
	        		</td>
	        		<td><span class='hl'>f23</span></td></tr>
	        </table>
			<table class='table table-striped table-responsive'><tr><td colspan='2'><b>Magang</b> <span class='hl'>f24</span></td></tr>
				<tr>
					<td>
				        <input type='radio'  class='v24'  name='f24' value='1'  > [1] Sangat Besar<br />
				        <input type='radio'  class='v24'  name='f24' value='2'  > [2] Besar<br />
				        <input type='radio'  class='v24'  name='f24' value='3'  > [3] Cukup Besar<br />
				        <input type='radio'  class='v24'  name='f24' value='4'  > [4] Kurang<br />
				        <input type='radio'  class='v24'  name='f24' value='5'  > [5] Tidak Sama Sekali<br />
				        <input type="hidden" id="v24">
		        	</td>
		        	<td><span class='hl'>f24</span></td>
		        </tr>
		    </table>
			<table class='table table-striped table-responsive'><tr><td colspan='2'><b>Praktikum</b> <span class='hl'>f25</span></td>
				<tr>
					<td>
		        		<input type='radio'  class='v25'  name='f25' value='1'  > [1] Sangat Besar<br />
		        		<input type='radio'  class='v25'  name='f25' value='2'  > [2] Besar<br />
		        		<input type='radio'  class='v25'  name='f25' value='3'  > [3] Cukup Besar<br />
		        		<input type='radio'  class='v25'  name='f25' value='4'  > [4] Kurang<br />
		        		<input type='radio'  class='v25'  name='f25' value='5'  > [5] Tidak Sama Sekali<br />
		        		<input type="hidden" id="v25">
		        	</td>
		        	<td><span class='hl'>f25</span></td>
		        </tr>
		    </table>
			<table class='table table-striped table-responsive'><tr><td colspan='2'><b>Kerja Lapangan</b> <span class='hl'>f26</span></td>
				<tr>
					<td>
        				<input type='radio'  class='v26'  name='f26' value='1'  > [1] Sangat Besar<br />
        				<input type='radio'  class='v26'  name='f26' value='2'  > [2] Besar<br />
				        <input type='radio'  class='v26'  name='f26' value='3'  > [3] Cukup Besar<br />
				        <input type='radio'  class='v26'  name='f26' value='4'  > [4] Kurang<br />
				        <input type='radio'  class='v26'  name='f26' value='5'  > [5] Tidak Sama Sekali<br />
				        <input type="hidden" id="v26">
			        </td>
			        <td><span class='hl'>f26</span></td>
			   </tr>
        	</table>
			<table class='table table-striped table-responsive'><tr><td colspan='2'><b>Diskusi</b> <span class='hl'>f27</span></td>
				<tr>
					<td>
        				<input type='radio'  class='v27'  name='f27' value='1'  > [1] Sangat Besar<br />
				        <input type='radio'  class='v27'  name='f27' value='2'  > [2] Besar<br />
				        <input type='radio'  class='v27'  name='f27' value='3'  > [3] Cukup Besar<br />
				        <input type='radio'  class='v27'  name='f27' value='4'  > [4] Kurang<br />
				        <input type='radio'  class='v27'  name='f27' value='5'  > [5] Tidak Sama Sekali<br />
				        <input type="hidden" id="v27">
        			</td>
        			<td><span class='hl'>f27</span></td>
        		</tr>
        	</table>
		</td>
	</tr>
	<tr>
		<td id='f3' class='h'>f3</td><td valign='top'>Kapan anda mulai mencari pekerjaan? <i>Mohon pekerjaan sambilan tidak dimasukkan</i></td>
		<td valign='top'>:</td>
		<td>
			<table  class='table table-striped table-responsive'>
				<tr><td><span class='hl'>f301</span>&nbsp;&nbsp;<input class='v301' type='radio'  name='f301' value='1' onclick='show3()' > [1] Kira-kira <input type='text'   id='v302'  name='f302' value='' size='5'> &nbsp;bulan sebelum lulus &nbsp;&nbsp;<span class='hl'>f302</span></td></tr>
				<tr><td><span class='hl'>f301</span>&nbsp;&nbsp;<input class='v301' type='radio'  name='f301' value='2' onclick='show3()' > [2] Kira-kira <input type='text'   id='v303'  name='f303' value='' size='5'> &nbsp;bulan sesudah lulus &nbsp;&nbsp;<span class='hl'>f303</span></td></tr>
				<tr><td><span class='hl'>f301</span>&nbsp;&nbsp;<input class='v301' type='radio'  name='f301' value='3' onclick='hide3()'> [3] Saya tidak mencari kerja (<i>Langsung ke pertanyaan f8</i>)</td></tr>
			</table>
			<input type="hidden" id="v301">
		</td>
	</tr>
	<tr id='f4' >
		<td class='h'>f4</td><td valign='top'>Bagaimana anda mencari pekerjaan tersebut? <i>Jawaban bisa lebih dari satu</i></td>
		<td valign='top'>:</td>
		<td>
			<table class='table table-striped table-responsive' style="padding:5px;">
				<tr>
					<td>
						<input  id='x_v401'  name='f401' type='checkbox' class='cb' value='1' > [1] Melalui iklan di koran/majalah, brosur <span class='hl'>&nbsp;&nbsp;f4-01</span><br />
						<input class="hidden" type="text" id="v401">
						<input  id='x_v402'  name='f402' type='checkbox' class='cb' value='1' > [1] Melamar ke perusahaan tanpa mengetahui lowongan yang ada <span class='hl'>&nbsp;&nbsp;f4-02</span><br />
						<input class="hidden" type="text" id="v402">
						<input  id='x_v403'  name='f403' type='checkbox' class='cb' value='1' > [1] Pergi ke bursa/pameran kerja <span class='hl'>&nbsp;&nbsp;f4-03</span><br />
						<input class="hidden" type="text" id="v403">
						<input  id='x_v404'  name='f404' type='checkbox' class='cb' value='1' > [1] Mencari lewat internet/iklan online/milis <span class='hl'>&nbsp;&nbsp;f4-04</span><br />
						<input class="hidden" type="text" id="v404">
						<input  id='x_v405'  name='f405' type='checkbox' class='cb' value='1' > [1] Dihubungi oleh perusahaan<span class='hl'>&nbsp;&nbsp;f4-05</span><br />
						<input class="hidden" type="text" id="v405">
						<input  id='x_v406'  name='f406' type='checkbox' class='cb' value='1' > [1] Menghubungi Kemenakertrans<span class='hl'>&nbsp;&nbsp;f4-06</span><br />
						<input class="hidden" type="text" id="v406">
						<input  id='x_v407'  name='f407' type='checkbox' class='cb' value='1' > [1] Menghubungi agen tenaga kerja komersial/swasta<span class='hl'>&nbsp;&nbsp;f4-07</span><br />
						<input class="hidden" type="text" id="v407">
						<input  id='x_v408'  name='f408' type='checkbox' class='cb' value='1' > [1] Memeroleh informasi dari pusat/kantor pengembangan karir fakultas/universitas <span class='hl'>&nbsp;&nbsp;f4-08</span><br />
						<input class="hidden" type="text" id="v408">
						<input  id='x_v409'  name='f409' type='checkbox' class='cb' value='1' > [1] Menghubungi kantor kemahasiswaan/hubungan alumni <span class='hl'>&nbsp;&nbsp;f4-09</span><br />
						<input class="hidden" type="text" id="v409">
						<input  id='x_v410'  name='f410' type='checkbox' class='cb' value='1' > [1] Membangun jejaring (<i>network</i>) sejak masih kuliah <span class='hl'>&nbsp;&nbsp;f4-10</span><br />
						<input class="hidden" type="text" id="v410">
						<input  id='x_v411'  name='f411' type='checkbox' class='cb' value='1' > [1] Melalui relasi (misalnya dosen, orang tua, saudara, teman, dll.)<span class='hl'>&nbsp;&nbsp;f4-11</span><br />
						<input class="hidden" type="text" id="v411">
						<input  id='x_v412'  name='f412' type='checkbox' class='cb' value='1' > [1] Membangun bisnis sendiri<span class='hl'>&nbsp;&nbsp;f4-12</span><br />
						<input class="hidden" type="text" id="v412">
						<input  id='x_v413'  name='f413' type='checkbox' class='cb' value='1' > [1] Melalui penempatan kerja atau magang<span class='hl'>&nbsp;&nbsp;f4-13</span><br />
						<input class="hidden" type="text" id="v413">
						<input  id='x_v414'  name='f414' type='checkbox' class='cb' value='1' > [1] Bekerja di tempat yang sama dengan tempat kerja semasa kuliah <span class='hl'>&nbsp;&nbsp;f4-14</span><br />
						<input class="hidden" type="text" id="v414">
						<input  id='x_v415'  name='f415' type='checkbox' class='cb' value='1' > [1] Lainnya:  <span class='hl'>&nbsp;&nbsp;f4-15</span>
						<input class="hidden" type="text" id="v415">
					</td>
					<td><span class='h'></span></td>
				</tr>
				<tr>
					<td>
						<input type='text' size='40'  id='v416'  name='f416' value=''></td><td><span class='hl'>&nbsp;&nbsp;f4-16</span>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr id='f5'>
		<td class='h'>f5</td>
		<td valign='top'>Berapa bulan waktu yang dihabiskan (sebelum dan sesudah kelulusan) untuk memeroleh pekerjaan pertama?</td>
		<td valign='top'>:</td>
		<td>
       		<input type='radio'  class='v501'  name='f501' value='1' >
             [1] Kira-kira <input type='text'  id='v502'  id='f502' size='5' value=''> bulan sebelum lulus ujian &nbsp;&nbsp;<span class='hl'>(f5-01, f5-02)</span><br />
             <input type='radio'  class='v501'  name='f501' value='2' >&nbsp;[2] Kira-kira <input type='text'  id='v503'  name='f503' size='5' value=''> bulan setelah lulus ujian &nbsp;&nbsp;<span class='hl'>(f5-01, f5-03)</span><br />
             <input type="hidden" id="v501">
		</td>
	</tr>
	<tr id='f6'>
		<td class='h'>f6</td>
		<td valign='top'>Berapa perusahaan/instansi/institusi yang sudah anda lamar (lewat surat atau e-mail) sebelum anda memeroleh pekerjaan pertama?</td>
		<td valign='top'>:</td><td><input type='text'  id='v6'  name='f6' size='5' value=''> perusahaan/instansi/institusi</td>
	</tr>
	<tr id='f7'>
		<td class='h'>f7</td>
		<td valign='top'>Berapa banyak perusahaan/instansi/institusi yang merespons lamaran anda? </td>
		<td valign='top'>:</td><td> <input type='text'  id='v7'  name='f7' size='5' value=''> perusahaan/instansi/institusi</td>
	</tr>
	<tr id='f7a'>
		<td class='h'>f7a</td>
		<td valign='top'>Berapa banyak perusahaan/instansi/institusi yang mengundang anda untuk wawancara? </td>
		<td valign='top'>:</td><td> <input type='text'  id='v7a'  name='f7a' size='5' value=''> perusahaan/instansi/institusi</td>
	</tr>
	<tr>
		<td class='h'>f8</td><td valign='top'>Apakah anda bekerja saat ini (termasuk kerja sambilan dan wirausaha)? </td>
		<td valign='top'>:</td>
		<td> 
			<input type='radio' value='1'  class='v8'  name='f8' valuetable table-striped table-responsive='1' onclick='hide1()' > [1] Ya (<i>Jika ya, lanjutkan ke f11</i>)<br/>
			<input type='radio'  class='v8'  name='f8' value='2' onclick='show1()' > [2] Tidak
			<input type="hidden" id="v8">
		</td>
	</tr>
	<tr id='f9'><td class='h'>f9</td><td valign='top'>Bagaimana anda menggambarkan situasi anda saat ini? <i> Jawaban bisa lebih dari satu</i></td>
		<td valign='top'>:</td>
		<td>
				<table class='table table-striped table-responsive'>
					<tr>
						<td>
	        				<input type='checkbox' class='cb'  id='x_v901'  name='f901' value='1' > [1] Saya masih belajar/melanjutkan kuliah profesi atau pascasarjana <span class='hl'>f9-01</span><br />
	        				<input class="hidden" type="text" id="v901">
	        				<input type='checkbox' class='cb'  id='x_v902'  name='f902' value='2' > [2] Saya menikah <span class='hl'>f9-02</span><br />
	        				<input class="hidden" type="text" id="v902">
	        				<input type='checkbox' class='cb'  id='x_v903'  name='f903' value='3' > [3] Saya sibuk dengan keluarga dan anak-anak <span class='hl'>f9-03</span><br />
	        				<input class="hidden" type="text" id="v903">
	        				<input type='checkbox' class='cb'  id='x_v904'  name='f904' value='4' > [4] Saya sekarang sedang mencari pekerjaan <span class='hl'>f9-04</span><br />
	        				<input class="hidden" type="text" id="v904">
	        				<input type='checkbox' class='cb'  id='x_v905'  name='f905' value='5' > [5] Lainnya <span class='hl'>f9-05</span><br />
	        				<input class="hidden" type="text" id="v905">
						</td>
					</tr>
					<tr>
						<td><input type='text'  id='v906'  name='f906' size='60' maxlength='80' value=''> <span class='hl'>f9-06</span></td>
					</tr>
				</table>
		</td>
	</tr>
	<tr id='f10'><td class='h'>f10</td><td valign='top'>Apakah anda aktif mencari pekerjaan dalam 4 minggu terakhir? <i> Pilihlah Satu Jawaban. KEMUDIAN LANJUT KE f17 </i></td>
		<td valign='top'>:</td>
		<td>
			<table class='table table-striped table-responsive'>
				<tr>
					<td>
				        <input type='radio'  class='v1001'  name='f1001' value='1'  onclick='hide2()'> [1] Tidak<br />
				        <input type='radio'  class='v1001'  name='f1001' value='2'   onclick='hide2()'> [2] Tidak, tapi saya sedang menunggu hasil lamaran kerja<br />
				        <input type='radio'  class='v1001'  name='f1001' value='3'  onclick='hide2()'> [3] Ya, saya akan mulai bekerja dalam 2 minggu ke depan<br />
				        <input type='radio'  class='v1001'  name='f1001' value='4'  onclick='hide2()'> [4] Ya, tapi saya belum pasti akan bekerja dalam 2 minggu ke depan<br />
				        <input type='radio'  class='v1001'  name='f1001' value='5' > [5] Lainnya<br />
				        <input type="hidden" id="v1001">
					</td>
					<td><span class='hl'>f10-01</span></td>
				</tr>
				<tr>
					<td><input type='text'  id='v1002'  name='f1002' size='60' maxlength='80' value=''></td><td><span class='hl'>f10-02</span></td></tr>
			</table>
		</td>
	</tr>
	<tr id='f11'>
		<td class='h'>f11</td>
		<td valign='top'>Apa jenis perusahaan/instansi/institusi tempat anda bekerja sekarang?</td>
		<td valign='top'>:</td>
		<td> 
			<table class='table table-striped table-responsive'>
				<tr>
					<td>
						<input type='radio'  class='v1101'  name='f1101'  value='1' > [1] Instansi pemerintah (termasuk BUMN)<br />
						<input type='radio'  class='v1101'  name='f1101'  value='2' > [2] Organisasi non-profit/Lembaga Swadaya Masyarakat<br />
						<input type='radio'  class='v1101'  name='f1101'  value='3' > [3] Perusahaan swasta<br />
						<input type='radio'  class='v1101'  name='f1101'  value='4' > [4] Wiraswasta/perusahaan sendiri<br />
						<input type='radio'  class='v1101'  name='f1101'  value='5'> [5] Lainnya, tuliskan:
						<input type="hidden" id="v1101">
					</td>
					<td><span class='hl'>(f11-01)</span></td>
				</tr>
				<tr>
					<td><input type='text'  id='v1102'  name='f1102' value='' size='50'></td>
					<td><span class='hl'>(f11-02)</span></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr id='f12'>
		<td class='h'>f12</td>
		<td valign='top'>Sebutkan sumberdana dalam pembiayaan kuliah?</td>
		<td valign='top'>:</td>
		<td> 
			<table class='table table-striped table-responsive'>
				<tr>
					<td>
						<input type='radio'  class='v1201'  name='f1201'  value='1' > [1] Biaya Sendiri / Keluarga<br />
						<input type='radio'  class='v1201'  name='f1201'  value='2' > [2] Beasiswa ADIK<br />
						<input type='radio'  class='v1201'  name='f1201'  value='3' > [3] Beasiswa BIDIKMISI<br />
						<input type='radio'  class='v1201'  name='f1201'  value='4' > [4] Beasiswa PPA<br />
						<input type='radio'  class='v1201'  name='f1201'  value='5' > [5] Beasiswa AFIRMASI<br />
						<input type='radio'  class='v1201'  name='f1201'  value='6' > [6] Beasiswa Perusahaan/Swasta<br />
						<input type='radio'  class='v1201'  name='f1201'  value='7' > [7] Lainnya, tuliskan:<br />
						<input type="hidden" id="v1201">
					</td>
					<td><span class='hl'>(f12-01)</span></td>
				</tr>
				<tr>
					<td><input type='text'  id='v1202'  name='f1202' value='' size='50'></td>
					<td><span class='hl'>(f12-02)</span></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr id='f13'><td class='h'>f13</td><td valign='top'>Kira-kira berapa pendapatan anda setiap bulannya? </td>
		<td valign='top'>:</td>
		<td>
			<table class='table table-striped table-responsive'>
				<tr>
					<td>
						Dari Pekerjaan Utama</td><td> Rp. &nbsp;
		        		<input type='text'  id='v1301'  name='f1301' value='0' size='20'><span class='hl'>(f13-01)</span> (Isilah dengan ANGKA saja, tanpa tanda Titik atau Koma)
		        	</td>
		        </tr>
				<tr>
					<td>
						Dari Lembur dan Tips</td><td> Rp. &nbsp;
		        		<input type='text'  id='v1302'  name='f1302' value='0' size='20'><span class='hl'>(f13-02)</span> (Isilah dengan ANGKA saja, tanpa tanda Titik atau Koma)
		        	</td>
		        </tr>
				<tr>
					<td>
						Dari Pekerjaan Lainnya</td><td> Rp. &nbsp;
		        		<input type='text'  id='v1303'  name='f1303' value='0' size='20'><span class='hl'>(f13-03)</span> (Isilah dengan ANGKA saja, tanpa tanda Titik atau Koma)
		        	</td>
		        </tr>
			</table>
		</td>
	</tr>
	<tr id='f14'>
		<td class='h'>f14</td><td valign='top'>Seberapa erat hubungan antara bidang studi dengan pekerjaan anda?</td>
		<td valign='top'>:</td>
		<td>
			<span >
				<input type='radio'  class='v14'  name='f14' value='1' > [1] Sangat Erat<br />
				<input type='radio'  class='v14'  name='f14' value='2' > [2] Erat<br />
				<input type='radio'  class='v14'  name='f14' value='3' > [3] Cukup Erat<br />
				<input type='radio'  class='v14'  name='f14' value='4' > [4] Kurang Erat<br />
				<input type='radio'  class='v14'  name='f14' value='5' > [5] Tidak Sama Sekali <br />
				<input type="hidden" id="v14">
			</span>
		</td>
	</tr>
	<tr id='f15'><td class='h'>f15</td><td valign='top'>Tingkat pendidikan apa yang paling tepat/sesuai untuk pekerjaan anda saat ini?</td>
		<td valign='top'>:</td>
		<td>
			<span >
				<input type='radio'  class='v15'  name='f15' value='1' > [1] Setingkat Lebih Tinggi<br />
				<input type='radio'  class='v15'  name='f15' value='2' > [2] Tingkat yang Sama<br />
				<input type='radio'  class='v15'  name='f15' value='3' > [3] Setingkat Lebih Rendah<br />
				<input type='radio'  class='v15'  name='f15' value='4' > [4] Tidak Perlu Pendidikan Tinggi<br />
				<input type="hidden" id="v15">
			</span>
		</td>
	</tr>
	<tr id='f16'><td class='h'>f16</td><td valign='top'>Jika menurut anda pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?  Jawaban bisa lebih dari satu</td><td valign='top'>:</td>
		<td>
			<span >
	    	    <input type='checkbox' class='cb'  id='x_v1601'  name='f1601'   value='1'> [1] Pertanyaan tidak sesuai; pekerjaan saya sekarang sudah sesuai dengan pendidikan saya. <span class='hl'>f16-01</span><br />
	    	    <input class="hidden" type="text" id="v1601">
	        	<input type='checkbox' class='cb'  id='x_v1602'  name='f1602'   value='2'> [2] Saya belum mendapatkan pekerjaan yang lebih sesuai.<span class='hl'>f16-02</span><br />
	        	<input class="hidden" type="text" id="v1602">
	        	<input type='checkbox' class='cb'  id='x_v1603'  name='f1603'   value='3'> [3] Di pekerjaan ini saya memeroleh prospek karir yang baik. <span class='hl'>f16-03</span><br />
	        	<input class="hidden" type="text" id="v1603">
	        	<input type='checkbox' class='cb'  id='x_v1604'  name='f1604'   value='4'> [4] Saya lebih suka bekerja di area pekerjaan yang tidak ada hubungannya dengan pendidikan saya. <span class='hl'>f16-04</span><br />
	        	<input class="hidden" type="text" id="v1604">
	        	<input type='checkbox' class='cb'  id='x_v1605'  name='f1605'   value='5'> [5] Saya dipromosikan ke posisi yang kurang berhubungan dengan pendidikan saya dibanding posisi sebelumnya.<span class='hl'>f16-05</span><br />
	        	<input class="hidden" type="text" id="v1605">
	        	<input type='checkbox' class='cb'  id='x_v1606'  name='f1606'   value='6'> [6] Saya dapat memeroleh pendapatan yang lebih tinggi di pekerjaan ini.  <span class='hl'>f16-06</span><br />
	        	<input class="hidden" type="text" id="v1606">
	        	<input type='checkbox' class='cb'  id='x_v1607'  name='f1607'   value='7'> [7] Pekerjaan saya saat ini lebih aman/terjamin/secure <span class='hl'>f16-07</span><br />
	        	<input class="hidden" type="text" id="v1607">
	        	<input type='checkbox' class='cb'  id='x_v1608'  name='f1608'   value='8'> [8] Pekerjaan saya saat ini lebih menarik <span class='hl'>f16-08</span><br />
	        	<input class="hidden" type="text" id="v1608">
	        	<input type='checkbox' class='cb'  id='x_v1609'  name='f1609'   value='9'> [9] Pekerjaan saya saat ini lebih memungkinkan saya mengambil pekerjaan tambahan/jadwal yang fleksibel, dll.<span class='hl'>f16-09</span><br />
	        	<input class="hidden" type="text" id="v1609">
	        	<input type='checkbox' class='cb'  id='x_v1610'  name='f1610'   value='10'> [10] Pekerjaan saya saat ini lokasinya lebih dekat dari rumah saya. <span class='hl'>f16-10</span><br />
	        	<input class="hidden" type="text" id="v1610">
	        	<input type='checkbox' class='cb'  id='x_v1611'  name='f1611'   value='11'> [11] Pekerjaan saya saat ini dapat lebih menjamin kebutuhan keluarga saya. <span class='hl'>f16-11</span><br />
	        	<input class="hidden" type="text" id="v1611">
	        	<input type='checkbox' class='cb'  id='x_v1612'  name='f1612'   value='12'> [12] Pada awal meniti karir ini, saya harus menerima pekerjaan yang tidak berhubungan dengan pendidikan saya. <span class='hl'>f16-12</span><br />
	        	<input class="hidden" type="text" id="v1612">
	        	<input type='checkbox' class='cb'  id='x_v1613'  name='f1613'   value='13'> [13] Lainnya:  <span class='hl'>f16-13</span><br />
	        	<input class="hidden" type="text" id="v1613">
	        	<input type='text'  id='v1614'  name='f1614' size='60' value='' maxlength='80'><span class='hl'>f16-14</span>
			</span>
		</td>
	</tr>
	<tr>
		<td class='h'>f17</td><td valign='top'>
			Pada saat lulus, pada tingkat mana kompetensi di bawah ini anda kuasai?  (<b>A</b>) <br />
			Pada saat ini, pada tingkat mana kompetensi di bawah ini diperlukan dalam pekerjaan? (<b>B</b>)
		</td>
		<td valign='top'>:</td>
		<td>
			<table class='table table-striped table-responsive'>
			<tr><th colspan='5' style='align:center;'>A</th><th>&nbsp;<th colspan='5'>B</th></tr>
			<tr><th colspan='2'>Sangat Rendah</th><th>&nbsp;</th><th colspan='2'>Sangat Tinggi</th>
		    	<th>&nbsp;</th>
		    	<th colspan='2'>Sangat Rendah</th><th>&nbsp;</th><th colspan='2'>Sangat Tinggi</th>
			</tr>
			<tr>
				<th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>&nbsp;
				<th>1</th><th>2</th><th>3</th><th>4</th><th>5</th>
			</tr>
			<tr>
		   		<td><input type='radio'  class='v1701'  name='f1701'   value='1'></td>
		   		<td><input type='radio'  class='v1701'  name='f1701'   value='2'></td>
		   		<td><input type='radio'  class='v1701'  name='f1701'   value='3'></td>
		   		<td><input type='radio'  class='v1701'  name='f1701'   value='4'></td>
		   		<td><input type='radio'  class='v1701'  name='f1701'   value='5'></td>
		   		<td>
		   			Pengetahuan di bidang atau disiplin ilmu anda <span class='hl'>f17-1 f17-2b</span>
		   			<input type="hidden" id="v1701">
		   			<input type="hidden" id="v1702b">
		   		</td>
		   		<td><input type='radio'  class='v1702b'  name='f1702b'   value='1'></td>
		   		<td><input type='radio'  class='v1702b'  name='f1702b'   value='2'></td>
		   		<td><input type='radio'  class='v1702b'  name='f1702b'   value='3'></td>
		   		<td><input type='radio'  class='v1702b'  name='f1702b'   value='4'></td>
		   		<td><input type='radio'  class='v1702b'  name='f1702b'   value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1703'  name='f1703'   value='1'></td>
		   		<td><input type='radio'  class='v1703'  name='f1703'   value='2'></td>
		   		<td><input type='radio'  class='v1703'  name='f1703'   value='3'></td>
		   		<td><input type='radio'  class='v1703'  name='f1703'   value='4'></td>
			   <td><input type='radio'  class='v1703'  name='f1703'   value='5'></td>
			   <td>
			   		Pengetahuan di luar bidang atau disiplin ilmu anda <span class='hl'>f17-3 f17-4b</span>
			   		<input type="hidden" id="v1703">
		   			<input type="hidden" id="v1704b">
			   </td>
		   		<td><input type='radio'  class='v1704b'  name='f1704b'   value='1'></td>
		   		<td><input type='radio'  class='v1704b'  name='f1704b'   value='2'></td>
		   		<td><input type='radio'  class='v1704b'  name='f1704b'   value='3'></td>
		   		<td><input type='radio'  class='v1704b'  name='f1704b'   value='4'></td>
				<td><input type='radio'  class='v1704b'  name='f1704b'   value='5'></td>
			</tr>
			<tr>
		   		<td><input type='radio'  class='v1705'  name='f1705'   value='1'></td>
		   		<td><input type='radio'  class='v1705'  name='f1705'   value='2'></td>
		   		<td><input type='radio'  class='v1705'  name='f1705'   value='3'></td>
		   		<td><input type='radio'  class='v1705'  name='f1705'   value='4'></td>
		   		<td><input type='radio'  class='v1705'  name='f1705'   value='5'></td>
		   		<td>
		   			Pengetahuan umum <span class='hl'>f17-5 f17-6b</span>
		   			<input type="hidden" id="v1705">
		   			<input type="hidden" id="v1706b">
		   		</td>
		   		<td><input type='radio'  class='v1706b'  name='f1706b'   value='1'></td>
		   		<td><input type='radio'  class='v1706b'  name='f1706b'   value='2'></td>
		   		<td><input type='radio'  class='v1706b'  name='f1706b'   value='3'></td>
		   		<td><input type='radio'  class='v1706b'  name='f1706b'   value='4'></td>
		   		<td><input type='radio'  class='v1706b'  name='f1706b'   value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1705a'  name='f1705a'   value='1'></td>
                <td><input type='radio'  class='v1705a'  name='f1705a'   value='2'></td>
                <td><input type='radio'  class='v1705a'  name='f1705a'   value='3'></td>
                <td><input type='radio'  class='v1705a'  name='f1705a'   value='4'></td>
                <td><input type='radio'  class='v1705a'  name='f1705a'   value='5'></td>
                <td>
                	Bahasa Inggris <span class='hl'>f17-5a f17-6ba</span>
                	<input type="hidden" id="v1705a">
		   			<input type="hidden" id="v1706ba">
                </td>
                <td><input type='radio'  class='v1706ba'  name='f1706ba'   value='1'></td>
                <td><input type='radio'  class='v1706ba'  name='f1706ba'   value='2'></td>
                <td><input type='radio'  class='v1706ba'  name='f1706ba'   value='3'></td>
                <td><input type='radio'  class='v1706ba'  name='f1706ba'   value='4'></td>
                <td><input type='radio'  class='v1706ba'  name='f1706ba'   value='5'></td>
            </tr>
            <tr>		
                <td><input type='radio'  class='v1707'  name='f1707'   value='1'></td>
                <td><input type='radio'  class='v1707'  name='f1707'   value='2'></td>
                <td><input type='radio'  class='v1707'  name='f1707'   value='3'></td>
                <td><input type='radio'  class='v1707'  name='f1707'   value='4'></td>
                <td><input type='radio'  class='v1707'  name='f1707'   value='5'></td>
                <td>
                	Ketrampilan internet <span class='hl'>f17-7 f17-8b</span>
                	<input type="hidden" id="v1707">
		   			<input type="hidden" id="v1708b">
                </td>
                <td><input type='radio'  class='v1708b'  name='f1708b'   value='1'></td>
                <td><input type='radio'  class='v1708b'  name='f1708b'   value='2'></td>
                <td><input type='radio'  class='v1708b'  name='f1708b'   value='3'></td>
                <td><input type='radio'  class='v1708b'  name='f1708b'   value='4'></td>
                <td><input type='radio'  class='v1708b'  name='f1708b'   value='5'></td>
             </tr>
             <tr>
                <td><input type='radio'  class='v1709'  name='f1709'   value='1'></td>
                <td><input type='radio'  class='v1709'  name='f1709'   value='2'></td>
                <td><input type='radio'  class='v1709'  name='f1709'   value='3'></td>
                <td><input type='radio'  class='v1709'  name='f1709'   value='4'></td>
                <td><input type='radio'  class='v1709'  name='f1709'   value='5'></td>
                <td>
                	Ketrampilan komputer <span class='hl'>f17-9 f17-10b</span>
                	<input type="hidden" id="v1709">
		   			<input type="hidden" id="v1710b">
                </td>
                <td><input type='radio'  class='v1710b'  name='f1710b'   value='1'></td>
                <td><input type='radio'  class='v1710b'  name='f1710b'   value='2'></td>
                <td><input type='radio'  class='v1710b'  name='f1710b'   value='3'></td>
                <td><input type='radio'  class='v1710b'  name='f1710b'   value='4'></td>
                <td><input type='radio'  class='v1710b'  name='f1710b'   value='5'></td>
            </tr>
            <tr>
                <td><input type='radio'  class='v1711'  name='f1711'   value='1'></td>
                <td><input type='radio'  class='v1711'  name='f1711'   value='2'></td>
                <td><input type='radio'  class='v1711'  name='f1711'   value='3'></td>
                <td><input type='radio'  class='v1711'  name='f1711'   value='4'></td>
                <td><input type='radio'  class='v1711'  name='f1711'   value='5'></td>
                <td>
                	Berpikir kritis <span class='hl'>f17-11 f17-12b</span>
                	<input type="hidden" id="v1711">
		   			<input type="hidden" id="v1712b">
                </td>
                <td><input type='radio'  class='v1712b'  name='f1712b'   value='1'></td>
                <td><input type='radio'  class='v1712b'  name='f1712b'   value='2'></td>
                <td><input type='radio'  class='v1712b'  name='f1712b'   value='3'></td>
                <td><input type='radio'  class='v1712b'  name='f1712b'   value='4'></td>
                <td><input type='radio'  class='v1712b'  name='f1712b'   value='5'></td>
             </tr>
             <tr>
		   		<td><input type='radio'  class='v1713'  name='f1713'   value='1'></td>
		   		<td><input type='radio'  class='v1713'  name='f1713'   value='2'></td>
		   		<td><input type='radio'  class='v1713'  name='f1713'   value='3'></td>
		   		<td><input type='radio'  class='v1713'  name='f1713'   value='4'></td>
		   		<td><input type='radio'  class='v1713'  name='f1713'   value='5'></td>
		   		<td>
		   			Ketrampilan riset <span class='hl'>f17-13 f17-14b</span>
		   			<input type="hidden" id="v1713">
		   			<input type="hidden" id="v1714b">
		   		</td>
		   		<td><input type='radio'  class='v1714b'  name='f1714b'   value='1'></td>
		   		<td><input type='radio'  class='v1714b'  name='f1714b'   value='2'></td>
		   		<td><input type='radio'  class='v1714b'  name='f1714b'   value='3'></td>
		   		<td><input type='radio'  class='v1714b'  name='f1714b'   value='4'></td>
		   		<td><input type='radio'  class='v1714b'  name='f1714b'   value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1715'  name='f1715'   value='1'></td>
		   		<td><input type='radio'  class='v1715'  name='f1715'   value='2'></td>
		   		<td><input type='radio'  class='v1715'  name='f1715'   value='3'></td>
			   	<td><input type='radio'  class='v1715'  name='f1715'   value='4'></td>
		   		<td><input type='radio'  class='v1715'  name='f1715'   value='5'></td>
		   		<td>
		   			Kemampuan belajar <span class='hl'>f17-15 f17-16b</span>
		   			<input type="hidden" id="v1715">
		   			<input type="hidden" id="v1716b">
		   		</td>
			   	<td><input type='radio'  class='v1716b'  name='f1716b'   value='1'></td>
		   		<td><input type='radio'  class='v1716b'  name='f1716b'   value='2'></td>
		   		<td><input type='radio'  class='v1716b'  name='f1716b'   value='3'></td>
		   		<td><input type='radio'  class='v1716b'  name='f1716b'   value='4'></td>
		   		<td><input type='radio'  class='v1716b'  name='f1716b'   value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1717'  name='f1717'   value='1'></td>
		   		<td><input type='radio'  class='v1717'  name='f1717'   value='2'></td>
			   	<td><input type='radio'  class='v1717'  name='f1717'   value='3'></td>
				<td><input type='radio'  class='v1717'  name='f1717'   value='4'></td>
		   		<td><input type='radio'  class='v1717'  name='f1717'   value='5'></td>
		   		<td>
		   			Kemampuan berkomunikasi <span class='hl'>f17-17 f17-18b</span>
		   			<input type="hidden" id="v1717">
		   			<input type="hidden" id="v1718b">
		   		</td>
		   		<td><input type='radio'  class='v1718b'  name='f1718b'   value='1'></td>
		   		<td><input type='radio'  class='v1718b'  name='f1718b'   value='2'></td>
		   		<td><input type='radio'  class='v1718b'  name='f1718b'   value='3'></td>
		   		<td><input type='radio'  class='v1718b'  name='f1718b'   value='4'></td>
				<td><input type='radio'  class='v1718b'  name='f1718b'   value='5'></td>
			</tr>
			<tr>
		   		<td><input type='radio'  class='v1719'  name='f1719'   value='1'></td>
		   		<td><input type='radio'  class='v1719'  name='f1719'   value='2'></td>
		   		<td><input type='radio'  class='v1719'  name='f1719'   value='3'></td>
		   		<td><input type='radio'  class='v1719'  name='f1719'   value='4'></td>
		   		<td><input type='radio'  class='v1719'  name='f1719'   value='5'></td>
		   		<td>
		   			Bekerja di bawah tekanan <span class='hl'>f17-19 f17-20b</span>
		   			<input type="hidden" id="v1719">
		   			<input type="hidden" id="v1720b">
		   		</td>
		   		<td><input type='radio'  class='v1720b'  name='f1720b'   value='1'></td>
		   		<td><input type='radio'  class='v1720b'  name='f1720b'   value='2'></td>
		   		<td><input type='radio'  class='v1720b'  name='f1720b'   value='3'></td>
		   		<td><input type='radio'  class='v1720b'  name='f1720b'   value='4'></td>
		   		<td><input type='radio'  class='v1720b'  name='f1720b'   value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1721'  name='f1721'    value='1'></td>
		   		<td><input type='radio'  class='v1721'  name='f1721'    value='2'></td>
		   		<td><input type='radio'  class='v1721'  name='f1721'    value='3'></td>
		   		<td><input type='radio'  class='v1721'  name='f1721'    value='4'></td>
		   		<td><input type='radio'  class='v1721'  name='f1721'    value='5'></td>
		   		<td>
		   			Manajemen waktu <span class='hl'>f17-21 f17-22b</span>
		   			<input type="hidden" id="v1721">
		   			<input type="hidden" id="v1722b">
		   		</td>
		   		<td><input type='radio'  class='v1722b'  name='f1722b'    value='1'></td>
		   		<td><input type='radio'  class='v1722b'  name='f1722b'    value='2'></td>
		   		<td><input type='radio'  class='v1722b'  name='f1722b'    value='3'></td>
		   		<td><input type='radio'  class='v1722b'  name='f1722b'    value='4'></td>
		   		<td><input type='radio'  class='v1722b'  name='f1722b'    value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1723'  name='f1723'    value='1'></td>
		   		<td><input type='radio'  class='v1723'  name='f1723'    value='2'></td>
		   		<td><input type='radio'  class='v1723'  name='f1723'    value='3'></td>
		   		<td><input type='radio'  class='v1723'  name='f1723'    value='4'></td>
		   		<td><input type='radio'  class='v1723'  name='f1723'    value='5'></td>
		   		<td>
		   			Bekerja secara mandiri <span class='hl'>f17-23 f17-24b</span>
		   			<input type="hidden" id="v1723">
		   			<input type="hidden" id="v1724b">
		   		</td>
		   		<td><input type='radio'  class='v1724b'  name='f1724b'    value='1'></td>
		   		<td><input type='radio'  class='v1724b'  name='f1724b'    value='2'></td>
		   		<td><input type='radio'  class='v1724b'  name='f1724b'    value='3'></td>
		   		<td><input type='radio'  class='v1724b'  name='f1724b'    value='4'></td>
		   		<td><input type='radio'  class='v1724b'  name='f1724b'    value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1725'  name='f1725'    value='1'></td>
		   		<td><input type='radio'  class='v1725'  name='f1725'    value='2'></td>
		   		<td><input type='radio'  class='v1725'  name='f1725'    value='3'></td>
		   		<td><input type='radio'  class='v1725'  name='f1725'    value='4'></td>
		   		<td><input type='radio'  class='v1725'  name='f1725'    value='5'></td>
		   		<td>
		   			Bekerja dalam tim/bekerjasama dengan orang lain <span class='hl'>f17-25 f17-26b</span>
		   			<input type="hidden" id="v1725">
		   			<input type="hidden" id="v1726b">
		   		</td>
		   		<td><input type='radio'  class='v1726b'  name='f1726b'    value='1'></td>
		   		<td><input type='radio'  class='v1726b'  name='f1726b'    value='2'></td>
		   		<td><input type='radio'  class='v1726b'  name='f1726b'    value='3'></td>
		   		<td><input type='radio'  class='v1726b'  name='f1726b'    value='4'></td>
		   		<td><input type='radio'  class='v1726b'  name='f1726b'    value='5'></td>
		   </tr>
		   <tr>
		   		<td><input type='radio'  class='v1727'  name='f1727'    value='1'></td>
		   		<td><input type='radio'  class='v1727'  name='f1727'    value='2'></td>
		   		<td><input type='radio'  class='v1727'  name='f1727'    value='3'></td>
		   		<td><input type='radio'  class='v1727'  name='f1727'    value='4'></td>
		   		<td><input type='radio'  class='v1727'  name='f1727'    value='5'></td>
		   		<td>
		   			Kemampuan dalam memecahkan masalah <span class='hl'>f17-27 f17-28b</span>
		   			<input type="hidden" id="v1727">
		   			<input type="hidden" id="v1728b">
		   		</td>
		   		<td><input type='radio'  class='v1728b'  name='f1728b'    value='1'></td>
		   		<td><input type='radio'  class='v1728b'  name='f1728b'    value='2'></td>
		   		<td><input type='radio'  class='v1728b'  name='f1728b'    value='3'></td>
		   		<td><input type='radio'  class='v1728b'  name='f1728b'    value='4'></td>
		   		<td><input type='radio'  class='v1728b'  name='f1728b'    value='5'></td>
		   	</tr>
			<tr>
		   		<td><input type='radio'  class='v1729'  name='f1729'    value='1'></td>
		   		<td><input type='radio'  class='v1729'  name='f1729'    value='2'></td>
		   		<td><input type='radio'  class='v1729'  name='f1729'    value='3'></td>
		   		<td><input type='radio'  class='v1729'  name='f1729'    value='4'></td>
		   		<td><input type='radio'  class='v1729'  name='f1729'    value='5'></td>
		   		<td>
		   			Negosiasi <span class='hl'>f17-29 f17-30b</span>
		   			<input type="hidden" id="v1729">
		   			<input type="hidden" id="v1730b">
		   		</td>
		   		<td><input type='radio'  class='v1730b'  name='f1730b'    value='1'></td>
		   		<td><input type='radio'  class='v1730b'  name='f1730b'    value='2'></td>
		   		<td><input type='radio'  class='v1730b'  name='f1730b'    value='3'></td>
		   		<td><input type='radio'  class='v1730b'  name='f1730b'    value='4'></td>
		   		<td><input type='radio'  class='v1730b'  name='f1730b'    value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1731'  name='f1731'    value='1'></td>
		   		<td><input type='radio'  class='v1731'  name='f1731'    value='2'></td>
		   		<td><input type='radio'  class='v1731'  name='f1731'    value='3'></td>
		   		<td><input type='radio'  class='v1731'  name='f1731'    value='4'></td>
		   		<td><input type='radio'  class='v1731'  name='f1731'    value='5'></td>
		   		<td>
		   			Kemampuan analisis <span class='hl'>f17-31 f17-32b</span>
		   			<input type="hidden" id="v1731">
		   			<input type="hidden" id="v1732b">
		   		</td>
		   		<td><input type='radio'  class='v1732b'  name='f1732b'    value='1'></td>
		   		<td><input type='radio'  class='v1732b'  name='f1732b'    value='2'></td>
		   		<td><input type='radio'  class='v1732b'  name='f1732b'    value='3'></td>
		   		<td><input type='radio'  class='v1732b'  name='f1732b'    value='4'></td>
		   		<td><input type='radio'  class='v1732b'  name='f1732b'    value='5'></td>
		   	</tr>
		   	<tr>
			   <td><input type='radio'  class='v1733'  name='f1733'    value='1'></td>
			   <td><input type='radio'  class='v1733'  name='f1733'    value='2'></td>
			   <td><input type='radio'  class='v1733'  name='f1733'    value='3'></td>
			   <td><input type='radio'  class='v1733'  name='f1733'    value='4'></td>
			   <td><input type='radio'  class='v1733'  name='f1733'    value='5'></td>
			   <td>
			   		Toleransi <span class='hl'>f17-33 f17-34b</span>
			   		<input type="hidden" id="v1733">
		   			<input type="hidden" id="v1734b">
			   </td>
			   <td><input type='radio'  class='v1734b'  name='f1734b'    value='1'></td>
			   <td><input type='radio'  class='v1734b'  name='f1734b'    value='2'></td>
			   <td><input type='radio'  class='v1734b'  name='f1734b'    value='3'></td>
			   <td><input type='radio'  class='v1734b'  name='f1734b'    value='4'></td>
			   <td><input type='radio'  class='v1734b'  name='f1734b'    value='5'></td>
			</tr>
			<tr>
			   <td><input type='radio'  class='v1735'  name='f1735'    value='1'></td>
			   <td><input type='radio'  class='v1735'  name='f1735'    value='2'></td>
			   <td><input type='radio'  class='v1735'  name='f1735'    value='3'></td>
			   <td><input type='radio'  class='v1735'  name='f1735'    value='4'></td>
			   <td><input type='radio'  class='v1735'  name='f1735'    value='5'></td>
			   <td>
			   		Kemampuan adaptasi <span class='hl'>f17-35 f17-36b</span>
			   		<input type="hidden" id="v1735">
		   			<input type="hidden" id="v1736b">
			   </td>
			   <td><input type='radio'  class='v1736b'  name='f1736b'    value='1'></td>
			   <td><input type='radio'  class='v1736b'  name='f1736b'    value='2'></td>
			   <td><input type='radio'  class='v1736b'  name='f1736b'    value='3'></td>
			   <td><input type='radio'  class='v1736b'  name='f1736b'    value='4'></td>
			   <td><input type='radio'  class='v1736b'  name='f1736b'    value='5'></td>
			</tr>
			<tr>
			   <td><input type='radio'  class='v1737'  name='f1737'    value='1'></td>
			   <td><input type='radio'  class='v1737'  name='f1737'    value='2'></td>
			   <td><input type='radio'  class='v1737'  name='f1737'    value='3'></td>
			   <td><input type='radio'  class='v1737'  name='f1737'    value='4'></td>
			   <td><input type='radio'  class='v1737'  name='f1737'    value='5'></td>
			   <td>
			   		Loyalitas<span class='hl'>f17-37 f17-38b</span>
			   		<input type="hidden" id="v1737">
		   			<input type="hidden" id="v1738b">
			   </td>
			   <td><input type='radio'  class='v1738b'  name='f1738b'    value='1'></td>
			   <td><input type='radio'  class='v1738b'  name='f1738b'    value='2'></td>
			   <td><input type='radio'  class='v1738b'  name='f1738b'    value='3'></td>
			   <td><input type='radio'  class='v1738b'  name='f1738b'    value='4'></td>
			   <td><input type='radio'  class='v1738b'  name='f1738b'    value='5'></td>
			</tr>
			<tr>
		       <td><input type='radio'  class='v1737a'  name='f1737a'    value='1'></td>
               <td><input type='radio'  class='v1737a'  name='f1737a'    value='2'></td>
               <td><input type='radio'  class='v1737a'  name='f1737a'    value='3'></td>
               <td><input type='radio'  class='v1737a'  name='f1737a'    value='4'></td>
               <td><input type='radio'  class='v1737a'  name='f1737a'    value='5'></td>
               <td>
	               	Integritas <span class='hl'>f17-37A f17-38ba</span>
	               	<input type="hidden" id="v1737a">
		   			<input type="hidden" id="v1738ba">
	           </td>
               <td><input type='radio'  class='v1738ba'  name='f1738ba'    value='1'></td>
               <td><input type='radio'  class='v1738ba'  name='f1738ba'    value='2'></td>
               <td><input type='radio'  class='v1738ba'  name='f1738ba'    value='3'></td>
               <td><input type='radio'  class='v1738ba'  name='f1738ba'    value='4'></td>
               <td><input type='radio'  class='v1738ba'  name='f1738ba'    value='5'></td>
            </tr>
            <tr>
		   		<td><input type='radio'  class='v1739'  name='f1739'    value='1'></td>
		   		<td><input type='radio'  class='v1739'  name='f1739'    value='2'></td>
		   		<td><input type='radio'  class='v1739'  name='f1739'    value='3'></td>
		   		<td><input type='radio'  class='v1739'  name='f1739'    value='4'></td>
		   		<td><input type='radio'  class='v1739'  name='f1739'    value='5'></td>
		   		<td>
		   			Bekerja dengan orang yang berbeda budaya maupun latar belakang <span class='hl'>f17-39 f17-40b</span>
		   			<input type="hidden" id="v1739">
		   			<input type="hidden" id="v1740b">
		   		</td>
		   		<td><input type='radio'  class='v1740b'  name='f1740b'    value='1'></td>
		   		<td><input type='radio'  class='v1740b'  name='f1740b'    value='2'></td>
		   		<td><input type='radio'  class='v1740b'  name='f1740b'    value='3'></td>
		   		<td><input type='radio'  class='v1740b'  name='f1740b'    value='4'></td>
		   		<td><input type='radio'  class='v1740b'  name='f1740b'    value='5'></td>
		   	</tr>
			<tr>
		   		<td><input type='radio'  class='v1741'  name='f1741'    value='1'></td>
		   		<td><input type='radio'  class='v1741'  name='f1741'    value='2'></td>
		   		<td><input type='radio'  class='v1741'  name='f1741'    value='3'></td>
		   		<td><input type='radio'  class='v1741'  name='f1741'    value='4'></td>
		   		<td><input type='radio'  class='v1741'  name='f1741'    value='5'></td>
		   		<td>
		   			Kepemimpinan <span class='hl'>f17-41 f17-42b</span>
		   			<input type="hidden" id="v1741">
		   			<input type="hidden" id="v1742b">
		   		</td>
			   	<td><input type='radio'  class='v1742b'  name='f1742b'    value='1'></td>
			   	<td><input type='radio'  class='v1742b'  name='f1742b'    value='2'></td>
		   		<td><input type='radio'  class='v1742b'  name='f1742b'    value='3'></td>
		   		<td><input type='radio'  class='v1742b'  name='f1742b'    value='4'></td>
		   		<td><input type='radio'  class='v1742b'  name='f1742b'    value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1743'  name='f1743'    value='1'></td>
		   		<td><input type='radio'  class='v1743'  name='f1743'    value='2'></td>
		   		<td><input type='radio'  class='v1743'  name='f1743'    value='3'></td>
		   		<td><input type='radio'  class='v1743'  name='f1743'    value='4'></td>
		   		<td><input type='radio'  class='v1743'  name='f1743'    value='5'></td>
		   		<td>
		   			Kemampuan dalam memegang tanggungjawab <span class='hl'>f17-43 f17-44b</span>
		   			<input type="hidden" id="v1743">
		   			<input type="hidden" id="v1744b">
		   		</td>
		   		<td><input type='radio'  class='v1744b'  name='f1744b'    value='1'></td>
		   		<td><input type='radio'  class='v1744b'  name='f1744b'    value='2'></td>
		   		<td><input type='radio'  class='v1744b'  name='f1744b'    value='3'></td>
				<td><input type='radio'  class='v1744b'  name='f1744b'    value='4'></td>
		   		<td><input type='radio'  class='v1744b'  name='f1744b'    value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1745'  name='f1745'   value='1'></td>
		   		<td><input type='radio'  class='v1745'  name='f1745'   value='2'></td>
		   		<td><input type='radio'  class='v1745'  name='f1745'   value='3'></td>
		   		<td><input type='radio'  class='v1745'  name='f1745'   value='4'></td>
		   		<td><input type='radio'  class='v1745'  name='f1745'   value='5'></td>
		   		<td>
		   			Inisiatif <span class='hl'>f17-45 f17-46b</span>
		   			<input type="hidden" id="v1745">
		   			<input type="hidden" id="v1746b">
		   		</td>
		   		<td><input type='radio'  class='v1746b'  name='f1746b'   value='1'></td>
		   		<td><input type='radio'  class='v1746b'  name='f1746b'   value='2'></td>
		   		<td><input type='radio'  class='v1746b'  name='f1746b'   value='3'></td>
		   		<td><input type='radio'  class='v1746b'  name='f1746b'   value='4'></td>
		   		<td><input type='radio'  class='v1746b'  name='f1746b'   value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1747'  name='f1747'   value='1'></td>
		   		<td><input type='radio'  class='v1747'  name='f1747'   value='2'></td>
		   		<td><input type='radio'  class='v1747'  name='f1747'   value='3'></td>
		   		<td><input type='radio'  class='v1747'  name='f1747'   value='4'></td>
		   		<td><input type='radio'  class='v1747'  name='f1747'   value='5'></td>
		   		<td>
		   			Manajemen proyek/program <span class='hl'>f17-47 f17-48b</span>
		   			<input type="hidden" id="v1747">
		   			<input type="hidden" id="v1748b">
		   		</td>
		   		<td><input type='radio'  class='v1748b'  name='f1748b'   value='1'></td>
		   		<td><input type='radio'  class='v1748b'  name='f1748b'   value='2'></td>
		   		<td><input type='radio'  class='v1748b'  name='f1748b'   value='3'></td>
		   		<td><input type='radio'  class='v1748b'  name='f1748b'   value='4'></td>
		   		<td><input type='radio'  class='v1748b'  name='f1748b'   value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1749'  name='f1749'   value='1'></td>
		   		<td><input type='radio'  class='v1749'  name='f1749'   value='2'></td>
		   		<td><input type='radio'  class='v1749'  name='f1749'   value='3'></td>
		   		<td><input type='radio'  class='v1749'  name='f1749'   value='4'></td>
		   		<td><input type='radio'  class='v1749'  name='f1749'   value='5'></td>
		   		<td>
		   			Kemampuan untuk memresentasikan ide/produk/laporan <span class='hl'>f17-49 f17-50b</span>
		   			<input type="hidden" id="v1749">
		   			<input type="hidden" id="v1750b">
		   		</td>
		   		<td><input type='radio'  class='v1750b'  name='f1750b'   value='1'></td>
		   		<td><input type='radio'  class='v1750b'  name='f1750b'   value='2'></td>
		   		<td><input type='radio'  class='v1750b'  name='f1750b'   value='3'></td>
		   		<td><input type='radio'  class='v1750b'  name='f1750b'   value='4'></td>
		   		<td><input type='radio'  class='v1750b'  name='f1750b'   value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1751'  name='f1751'   value='1'></td>
		   		<td><input type='radio'  class='v1751'  name='f1751'   value='2'></td>
		   		<td><input type='radio'  class='v1751'  name='f1751'   value='3'></td>
		   		<td><input type='radio'  class='v1751'  name='f1751'   value='4'></td>
		   		<td><input type='radio'  class='v1751'  name='f1751'   value='5'></td>
		   		<td>
		   			Kemampuan dalam menulis laporan, memo dan dokumen <span class='hl'>f17-51 f17-52b</span>
		   			<input type="hidden" id="v1751">
		   			<input type="hidden" id="v1752b">
		   		</td>
		   		<td><input type='radio'  class='v1752b'  name='f1752b'   value='1'></td>
		   		<td><input type='radio'  class='v1752b'  name='f1752b'   value='2'></td>
		   		<td><input type='radio'  class='v1752b'  name='f1752b'   value='3'></td>
		   		<td><input type='radio'  class='v1752b'  name='f1752b'   value='4'></td>
		   		<td><input type='radio'  class='v1752b'  name='f1752b'   value='5'></td>
		   	</tr>
		   	<tr>
		   		<td><input type='radio'  class='v1753'  name='f1753'   value='1'></td>
		   		<td><input type='radio'  class='v1753'  name='f1753'   value='2'></td>
		   		<td><input type='radio'  class='v1753'  name='f1753'   value='3'></td>
		   		<td><input type='radio'  class='v1753'  name='f1753'   value='4'></td>
		   		<td><input type='radio'  class='v1753'  name='f1753'   value='5'></td>
		   		<td>
		   			Kemampuan untuk terus belajar sepanjang hayat <span class='hl'>f17-53 f17-54b</span>
		   			<input type="hidden" id="v1753">
		   			<input type="hidden" id="v1754b">
		   		</td>
		   		<td><input type='radio'  class='v1754b'  name='f1754b'   value='1'></td>
		   		<td><input type='radio'  class='v1754b'  name='f1754b'   value='2'></td>
		   		<td><input type='radio'  class='v1754b'  name='f1754b'   value='3'></td>
		   		<td><input type='radio'  class='v1754b'  name='f1754b'   value='4'></td>
		   		<td><input type='radio'  class='v1754b'  name='f1754b'   value='5'></td>
		  	</tr>
		</table>
	</td>
</tr>
<tr>
<td width="100%" colspan="4">
	<div class="col-sm-12 col-sm-offset-2">
 		<button class="btn btn-primary" type="submit">KIRIM</button>
 	</div>
</td>
</tr>
</table>
</form>
</div>
<script>
	$(".cb").on('change',(function() {
		id=$(this).attr('id');
		n= id.split('_');
		if($(this).is(':checked')){
			$("#"+n[1]).val($(this).val());
		}else{
			$("#"+n[1]).val('');
		}
	}))
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script>
	$("#frm").submit(function() {
	  $("#v21").val($(".v21:checked").val());
	  $("#v22").val($(".v22:checked").val());
	  $("#v23").val($(".v23:checked").val());
	  $("#v24").val($(".v24:checked").val());
	  $("#v25").val($(".v25:checked").val());
	  $("#v26").val($(".v26:checked").val());
	  $("#v27").val($(".v27:checked").val());
	  $("#v301").val($(".v301:checked").val());
	  $("#v501").val($(".v501:checked").val());
	  $("#v8").val($(".v8:checked").val());
	  $("#v1001").val($(".v1001:checked").val());
	  $("#v1101").val($(".v1101:checked").val());
	  $("#v1201").val($(".v1201:checked").val());
	  $("#v14").val($(".v14:checked").val());
	  $("#v15").val($(".v15:checked").val());
	  
	  $("#v1701").val($(".v1701:checked").val());
	  $("#v1702b").val($(".v1702b:checked").val());
	  
	  $("#v1703").val($(".v1703:checked").val());
	  $("#v1704b").val($(".v1704b:checked").val());
	  
	  $("#v1705").val($(".v1705:checked").val());
	  $("#v1706b").val($(".v1706b:checked").val());
	  
	  $("#v1705a").val($(".v1705a:checked").val());
	  $("#v1706ba").val($(".v1706ba:checked").val());
	  
	  $("#v1707").val($(".v1707:checked").val());
	  $("#v1708b").val($(".v1708b:checked").val());

	  $("#v1709").val($(".v1709:checked").val());
	  $("#v1710b").val($(".v1710b:checked").val());

	  $("#v1711").val($(".v1711:checked").val());
	  $("#v1712b").val($(".v1712b:checked").val());

	  $("#v1713").val($(".v1713:checked").val());
	  $("#v1714b").val($(".v1714b:checked").val());

	  $("#v1715").val($(".v1715:checked").val());
	  $("#v1716b").val($(".v1716b:checked").val());

	  $("#v1717").val($(".v1717:checked").val());
	  $("#v1718b").val($(".v1718b:checked").val());

	  $("#v1719").val($(".v1719:checked").val());
	  $("#v1720b").val($(".v1720b:checked").val());

	  $("#v1721").val($(".v1721:checked").val());
	  $("#v1722b").val($(".v1722b:checked").val());

	  $("#v1723").val($(".v1723:checked").val());
	  $("#v1724b").val($(".v1724b:checked").val());

	  $("#v1725").val($(".v1725:checked").val());
	  $("#v1726b").val($(".v1726b:checked").val());

	  $("#v1727").val($(".v1727:checked").val());
	  $("#v1728b").val($(".v1728b:checked").val());

	  $("#v1729").val($(".v1729:checked").val());
	  $("#v1730b").val($(".v1730b:checked").val());

	  $("#v1731").val($(".v1731:checked").val());
	  $("#v1732b").val($(".v1732b:checked").val());

	  $("#v1733").val($(".v1733:checked").val());
	  $("#v1734b").val($(".v1734b:checked").val());

	  $("#v1735").val($(".v1735:checked").val());
	  $("#v1736b").val($(".v1736b:checked").val());

	  $("#v1737").val($(".v1737:checked").val());
	  $("#v1738b").val($(".v1738b:checked").val());

	  $("#v1737a").val($(".v1737a:checked").val());
	  $("#v1738ba").val($(".v1738ba:checked").val());

	  $("#v1739").val($(".v1739:checked").val());
	  $("#v1740b").val($(".v1740b:checked").val());

	  $("#v1741").val($(".v1741:checked").val());
	  $("#v1742b").val($(".v1742b:checked").val());

	  $("#v1743").val($(".v1743:checked").val());
	  $("#v1744b").val($(".v1744b:checked").val());

	  $("#v1745").val($(".v1745:checked").val());
	  $("#v1746b").val($(".v1746b:checked").val());

	  $("#v1747").val($(".v1747:checked").val());
	  $("#v1748b").val($(".v1748b:checked").val());

	  $("#v1749").val($(".v1749:checked").val());
	  $("#v1750b").val($(".v1750b:checked").val());

	  $("#v1751").val($(".v1751:checked").val());
	  $("#v1752b").val($(".v1752b:checked").val());

	  $("#v1753").val($(".v1753:checked").val());
	  $("#v1754b").val($(".v1754b:checked").val());

	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/inskuis","/tracerid/index?new=","u");
	  return false;
	});
</script>