<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker-bs3.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Periode Akademik</h3>
	</div>
	<div class="box-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="box-body">
				<div class="form-group">
					<label class="col-sm-2 control-label">Rentang Periode</label>
					<div class="col-sm-4">
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<input type="hidden" id="kd_per" value="<?php echo $this->kd_per;?>">
							<input type="text" class="form-control pull-right" id="tgl" placeholder="rentang periode" value="<?php echo $this->rangeTgl;?>" readonly>
						</div>
					</div>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
					<button type="submit" class="btn btn-info pull-right col-sm-2">Simpan</button>
				</div>
			</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/moment.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker.js"></script>
<script>
	$(function () {
		$('#tgl').daterangepicker({showDropdowns: true, format:"DD MMMM YYYY"});
	});
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax2/updper","/periode?new=","u");
	  return false;
	});
</script>