<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/plugins/select2/select2.min.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/dist/css/AdminLTE.min.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Filter</h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">Program Studi</label>
				<div class="col-sm-4">
					<select id="prodi" class="form-control select2" multiple="multiple" data-placeholder="prodi" sel-2>
						<?php foreach ($this->listProdi as $dtProdi){?>
						<option value="<?php echo $dtProdi['kd_prodi']?>"><?php echo $dtProdi['nm_prodi'];?></option>
						<?php }?>
					</select>
				</div>
			</div>
            		<div class="form-group">
				<label class="col-sm-2 control-label">Angkatan</label>
				<div class="col-sm-4">
					<select id="angkatan" class="form-control select2" multiple="multiple" data-placeholder="angkatan" sel-2>
						<?php foreach ($this->listAngkatan as $dtAngkatan){?>
						<option value="<?php echo $dtAngkatan['id_angkatan']?>"><?php echo $dtAngkatan['id_angkatan'];?></option>
						<?php }?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Parameter</label>
				<div class="col-sm-4">
					<select id="jns" class="form-control">
						<option value="JENIS KELAMIN">JENIS KELAMIN</option>
						<option value="AGAMA">AGAMA</option>
						<option value="STATUS MAHASISWA">STATUS MAHASISWA</option>
						<option value="STATUS MASUK MAHASISWA">STATUS MASUK MAHASISWA</option>
						<option value="KOTA">ASAL (KOTA)</option>
						<option value="PROVINSI">ASAL (PROVINSI)</option>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="submit" class="btn btn-info pull-right col-sm-2">Show</button>
			</div>
		</div>
	</form>
</div>

<script src="<?php echo $this->baseUrl;?>/public/plugins/select2/select2.full.min.js"></script>
<script>
	$("[sel-2]").select2();
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
	    ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/rekapmhs","/mahasiswa/prekap","s");
	    return false;
	  });
	});
</script>