<div class="row">
	<div class="col-sm-8">
		<div class="col-sm-4">Nama (NIM)</div>
		<div class="col-sm-8">: <?php echo $this->nm_mhs." (".$this->nim.")";?></div>
		<div class="col-sm-4">Program Studi</div>
		<div class="col-sm-8">: <?php echo $this->nm_prd;?></div>
		<div class="col-sm-4">Angkatan</div>
		<div class="col-sm-8">: <?php echo $this->akt;?></div>
		<div class="col-sm-4">Status Masuk</div>
		<div class="col-sm-8">: <?php echo $this->stat_msk;?></div>
	</div>
</div>
<form class="form-horizontal" role="form" id="frm">
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Gelombang Masuk </label>
		<div class="col-sm-9">
			<input type="hidden" value="<?php echo $this->nim;?>" id="nim">
			<select class="col-xs-10 col-sm-5" id="gel">
				<option value="">&lt;Pilih Gelombang&gt;</option>
				<?php foreach ($this->listGel as $dtGel) { ?>
				<?php 
					if($dtGel['id_gelombang']==$this->id_gel){
						$selGel="selected='selected'";
					}else{
						$selGel="";
					}
				?>
				<option value="<?php echo $dtGel['id_gelombang'];?>" <?php echo $selGel;?>><?php echo $dtGel['nm_gelombang'];?></option>					
				<?php }?>
			</select>
		</div>
	</div>
	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<button class="btn btn-info" type="submit"><i class="ace-icon fa fa-check bigger-110"></i>Submit</button>
			&nbsp; &nbsp; &nbsp;
			<button class="btn" type="reset"><i class="ace-icon fa fa-undo bigger-110"></i>Reset</button>
		</div>
	</div>
</form>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/insgelmhs","/gelmhs/new?nim=<?php echo $this->nim;?>&src=<?php echo $this->src;?>&new=","u");
	  return false;
	});
</script>