<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="box  box-info">
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbprd" class="table table-bordered table-hover">
				<thead align="center">
					<tr>
						<th>NO</th>
						<th>KODE PROGRAM STUDI</th>
						<th>PROGRAM STUDI</th>
						<?php foreach ($this->listJnsKelas as $dtJnsKelas) {?>
						<th><?php echo $dtJnsKelas['jns_kelas']; ?></th>
						<?php } ?>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listProdi as $dataProdi) { ?>
					<tr>
						<td><?php echo $i; ?></td>
						<td><?php echo $dataProdi['kd_prodi'];?></td>
						<td><?php echo $dataProdi['nm_prodi']; ?></td>
						<?php $j=1;foreach ($this->listJnsKelas as $dtJnsKelas) {?>
						<td align="center">
							<form id="frm<?php echo $i.$j;?>" method="post">
								<input type="hidden" id="prd<?php echo $i.$j;?>" value="<?php echo $dataProdi['kd_prodi'];?>">
								<input type="hidden" id="jns<?php echo $i.$j;?>" value="<?php echo $dtJnsKelas['id_jns_kelas'];?>">
								<select id="per<?php echo $i.$j;?>" class="form-control">
									<?php foreach ($this->listPeriode as $dtPer) { ?>
									<?php
										if($this->per_aktif==$dtPer['kd_periode']){
											$sel_per="selected";
										}else{
											$sel_per="";
										}
										?>
									<option value="<?php echo $dtPer['kd_periode'];?>" <?php echo $sel_per;?> ><?php echo $dtPer['kd_periode'];?></option>
									<?php } ?>
								</select>
								<button id="sb" type="button" class="btn btn-primary btn-sm" sb value="<?php echo $i.$j;?>"><i class="fa fa-eye"></i></button>
							</form>
						</td>
						<?php $j++;} ?>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<!-- DataTables -->
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbprd',true,true,true,true,true,false);});</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("[sb]").on('click',(function() {
	 x=$(this).val();
	 ajaxSubmit("frm"+x,"<?php echo $this->baseUrl;?>","/ajax2/showkls?frm="+x,"/kelas/list","s");
	  return false;
	}));
</script>