<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="box  box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Autentifikasi</h3>
	</div>
	<div class="box-body">
		<div class="col-md-6">
			<div class="col-sm-4">Username</div>
			<div class="col-sm-8">: <?php echo $this->uname;?></div>
			<div class="col-sm-4">Nama</div>
			<div class="col-sm-8">: <?php echo $this->nm;?></div>
			<div class="col-sm-4">Email</div>
			<div class="col-sm-8">: <?php echo $this->email;?></div>
			<div class="col-sm-4">SUPERADMIN ?</div>
			<div class="col-sm-8">: <?php echo $this->superadmin;?></div>
		</div>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<input type="hidden" id="uname" value="<?php echo $this->uname;?>">
				<label class="col-sm-2 control-label">Password Lama (Encrypted)</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="oldpwd" value="<?php echo $this->pwd;?>" readonly>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Password Baru</label>
				<div class="col-sm-4">
					<input type="password" class="form-control" id="pwd1" placeholder="password" maxlength="30">
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Password Sekali Lagi</label>
				<div class="col-sm-4">
					<input type="password" class="form-control" id="pwd2" placeholder="password" maxlength="30">
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="submit" class="btn btn-danger pull-right col-sm-4" id="btnres">GANTI PASSWORD</button>
			</div>
		</div>
	</form>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax4/upduserpwd","/user/password?id=<?php echo $this->uname;?>&new=","u");
	  return false;
	});
</script>