<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="box  box-info">
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbper" class="table table-bordered table-hover">
				<thead align="center">
					<tr>
						<th>KODE PERIODE</th>
						<th>STATUS PERIODE</th>
						<th>TANGGAL DIMULAI</th>
						<th>TANGGAL SELESAI</th>
						<th>UTS</th>
						<th>UAS</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->listPeriode as $dataPer) { ?>
					<?php 
						if ($dataPer['id_status_periode']==0){
							$warna='lightgreen';
						}else if($dataPer['id_status_periode']==1){
							$warna='yellow';
						}else{
							$warna='lightblue';
						}
						?>
					<tr bgcolor="<?php echo $warna;?>">
						<td><?php echo $dataPer['kd_periode']; ?></td>
						<td><?php echo $dataPer['status_periode_akademik']; ?></td>
						<td><?php echo $dataPer['tanggal_mulai_fmt']; ?></td>
						<td><?php echo $dataPer['tanggal_selesai_fmt']; ?></td>
						<td align="center"><button type="button" class="btn btn-info btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/jadwalujian/list?id=<?php echo $dataPer['kd_periode'];?>&u=1')"><i class="fa fa-eye"></i></button></td>
						<td align="center"><button type="button" class="btn btn-info btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/jadwalujian/list?id=<?php echo $dataPer['kd_periode'];?>&u=2')"><i class="fa fa-eye"></i></button></td>
					</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<!-- DataTables -->
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbper',true,true,true,false,true,false);});</script>