<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker-bs3.css">
<div class="box  box-info">
	<div class="box-header">
		<strong>ENTRI DATA JADWAL UJIAN</strong>
	</div>
	<div class="box-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="box-body">
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label">Program Studi</label>
						<div class="col-sm-8">
							<input type="hidden" id="jns" value="<?php echo $this->u;?>">
							<input type="text" id="kd_pkt" style="display:none;">
							<input type="hidden" id="per" value="<?php echo $this->per;?>">
							<select id="prd" class="form-control">
								<option disabled selected value="">pilih program studi</option>
								<?php foreach ($this->listProdi as $dataProdi) { ?>
								<option value="<?php echo $dataProdi['kd_prodi'] ?>"><?php echo $dataProdi['nm_prodi']; ?></option>
								<?php } ?>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Nama Kelas</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="nm_mk" placeholder="Klik untuk memilih paket kelas dari prodi di atas" readonly onclick="hbox('<?php echo $this->baseUrl;?>','helper/paketkelas',new Array('kd_pkt','nm_mk','dsn','mk'),new Array('per','prd'))">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Dosen</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="dsn" placeholder="terisi otomatis dari pilihan paket kelas" readonly>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label">Mata Kuliah</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="mk" placeholder="terisi otomatis dari pilihan paket kelas" readonly>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Tanggal</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="tgl" placeholder="tanggal" readonly >
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Ruangan</label>
						<div class="col-sm-8">
							<input type="text" id="id_room" style="display:none;">
							<input type="text" class="form-control" id="nm_room" placeholder="Klik untuk memilih ruangan" readonly onclick="hbox('<?php echo $this->baseUrl;?>','helper/ruangan',new Array('id_room','nm_room'))">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label"> Slot Ujian</label>
						<div class="col-sm-8">
							<input type="text" id="id_slot" style="display:none;">
							<input type="text" class="form-control" id="slot" placeholder="Klik untuk memilih slot jadwal" readonly onclick="hbox('<?php echo $this->baseUrl;?>','helper/slotujian',new Array('id_slot','slot'))">
						</div>
					</div>
				</div>
			</div>
			<div class="box-body">
				<div class="box-footer col-sm-6">
					<button type="submit" class="btn btn-primary pull-right col-sm-4" sb>Tambah</button>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-4">Reset</button>
				</div>
			</div>
		</form>
		<div class="box-body">
			<div class="box-body">
				<?php foreach ($this->arrTgl as $dtTgl){ ?>
				<?php $arrDtTgl=explode(",", $dtTgl);?>
				<?php 
					$disTgl="";
					if(trim($arrDtTgl[1])==$this->tgl){
						$disTgl="disabled='disabled'";
					}
				?>
				<button class="btn bg-blue btn-flat btn-sm" onclick="nav('<?php echo $this->baseUrl;?>/jadwalujian/list?id=<?php echo $this->per;?>&u=<?php echo $this->u;?>&t=<?php echo trim($arrDtTgl[1]);?>')" <?php echo $disTgl;?> ><?php echo $dtTgl;?></button>
				<?php }?>
			</div>
			<?php if($this->tgl!="f"){?>
			<div class="table-responsive">
				<table id="tbjdwl" class="table table-bordered table-hover">
					<thead>
						<tr>
							<th width="12%">Slot Waktu</th>
							<th>Ruangan</th>
							<th>Kelas</th>
							<th>Dosen</th>
							<th>Kode MK</th>
							<th>Nama MK</th>
							<th>Prodi</th>
							<th width="7%">Aksi</th>
						</tr>
					</thead>
					<tbody>
					<?php foreach ($this->listJadwal as $dataJadwal){ ?>
					<?php if(date('d F Y',strtotime($this->tgl))==date('d F Y',strtotime(trim($dataJadwal['tanggal_fmt'])))){?>
					<tr>
						<td><?php echo $dataJadwal['start_time']." s/d ".$dataJadwal['end_time'];?></td>
						<td><?php echo $dataJadwal['nm_ruangan'];?></td>
						<td><?php echo $dataJadwal['nm_kelas'];?></td>
						<td><?php echo $dataJadwal['nm_dosen'];?></td>
						<td><?php echo $dataJadwal['kode_mk'];?></td>
						<td><?php echo $dataJadwal['nm_mk'];?></td>
						<td><?php echo $dataJadwal['nm_prodi_kur'];?></td>
						<td align="center">
							<button type="button" class="btn btn-warning btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/jadwalujian/edit?tgl=<?php echo $dataJadwal['tanggal'];?>&sl=<?php echo $dataJadwal['id_slot_ujian'];?>&ro=<?php echo $dataJadwal['kd_ruangan'];?>&per=<?php echo $this->per;?>&u=<?php echo $this->u;?>')"><i class="fa fa-retweet"></i></button>
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah anda yakin ingin menghapus jadwal kuliah ini? Kelas : <?php echo $dataJadwal['nm_kelas'];?>, Dosen : <?php echo str_replace("'","\'",$dataJadwal['nm_dosen']);?>, Mata Kuliah : <?php echo str_replace("'","\'",$dataJadwal['nm_mk']);?>','<?php echo $this->baseUrl;?>','/ajax2/deljdwlujian', new Array('<?php echo $this->per;?>','<?php echo $dataJadwal['tanggal']?>','<?php echo $dataJadwal['id_slot_ujian']?>','<?php echo $dataJadwal['kd_ruangan']?>'))"><i class="fa fa-remove"></i></button>
						</td>
					</tr>
					<?php }?>
					<?php }?>
					</tbody>	
				</table>
			</div>
			<?php }?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/moment.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/plugins/daterangepicker/daterangepicker.js"></script>
<script>
	$(function () {
	  $('#tgl').daterangepicker({singleDatePicker:true,format:'DD MMMM YYYY'});
	});
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("[sb]").on('click',(function() {
	  var tgl=$('#tgl').val();
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax2/insjdwlujian","/jadwalujian/list?id=<?php echo $this->per;?>&u=<?php echo $this->u;?>&t="+tgl+"&new=","u");
	  return false;
	}));
</script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>
	$(function () {
		tabel('tbjdwl',true,true,true,true,true,false);
	});
</script>