<link href="<?php echo $this->baseUrl;?>/public/css/plugins/datapicker/datepicker3.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/timepicker/bootstrap-timepicker.min.css" rel="stylesheet">
<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Data Perkuliahan</h3>
</div>
<div class="inqbox-content">
	<div class="panel panel-primary">
		<div class="panel-body">
			<div class="col-sm-4">Program Studi</div>
			<div class="col-sm-8">: <?php echo $this->nm_prodi;?></div>
			<div class="col-sm-4">Periode Akademik</div>
			<div class="col-sm-8">: <?php echo $this->kd_per;?></div>
			<div class="col-sm-4">Nama Kelas</div>
			<div class="col-sm-8">: <?php echo $this->nm_kelas." (".$this->jns_kelas.")";?></div>
			<div class="col-sm-4">Dosen</div>
			<div class="col-sm-8">: <?php echo $this->nm_dsn;?></div>
			<div class="col-sm-4">Mata Kuliah</div>
			<div class="col-sm-8">: <?php echo $this->nm_mk." (".$this->kd_mk.") - ".$this->sks." SKS";?></div>
		</div>
	</div>
	<div class="panel-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="box-body">
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label">Tanggal</label>
						<div class="col-sm-8">
							<input type="hidden" id="id_perkuliahan" value="<?php echo $this->id_perkuliahan;?>">
							<input type="text" class="form-control" id="tgl" placeholder="tanggal" value="<?php echo $this->tgl;?>" readonly>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Tempat</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="tempat" placeholder="tempat perkuliahan" value="<?php echo $this->tempat;?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Waktu Mulai</label>
						<div class="col-sm-8">
							<div class="bootstrap-timepicker">
								<input type="text" id="start" class="form-control timepicker" placeholder="waktu mulai" value="<?php echo $this->start;?>">
							</div>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Waktu Selesai</label>
						<div class="col-sm-8">
							<div class="bootstrap-timepicker">
								<input type="text" id="end" class="form-control timepicker" placeholder="waktu selesai" value="<?php echo $this->end;?>">
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label">Media Digunakan</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="media" placeholder="media digunakan" value="<?php echo $this->media;?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Materi</label>
						<div class="col-sm-8">
							<textarea class="form-control" rows="2" placeholder="materi" id="materi"><?php echo $this->materi;?></textarea>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Kejadian Selama Perkuliahan</label>
						<div class="col-sm-8">
							<textarea class="form-control" rows="2" id="kejadian" placeholder="kejadian selama perkuliahan"><?php echo $this->kejadian;?></textarea>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="box-footer col-sm-6">
					<button type="submit" class="btn btn-primary pull-right col-sm-4" id="btnsbm">Simpan</button>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-4" id="btnres">Reset</button>
				</div>
			</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/plugins/moment/moment.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/js/plugins/datapicker/bootstrap-datepicker.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/js/plugins/timepicker/bootstrap-timepicker.min.js"></script>
<script>
	$(function () {
	  $('#tgl').datepicker({ format: 'dd MM yyyy', autoclose:true, todayHighlight:true});
	  $(".timepicker").timepicker({
	    showInputs: false,
	    showMeridian:false,
	    minuteStep:5
	  });
	});
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/updkbm","/kbm/index?id=<?php echo $this->kd_paket;?>&new=","u");
	  return false;
	});
</script>