<div class="table-header">
	Daftar User Sistem Informasi
</div>
<div>
	<table id="tbl" class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th class="center" width="15%">Username</th>
				<th class="center">Nama</th>
				<th class="center" width="20%">Email</th>
				<th class="center" width="12%">SuperAdmin ?</th>
				<th class="center" width="15%">Ubah Password</th>
				<th class="center" width="15%">Aksi</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->listUser as $dt){?>
			<tr>
				<td><?php echo $dt['username'];?></td>
				<td><?php echo $dt['nama'];?></td>
				<td class="center"><?php echo $dt['email'];?></td>
				<?php 
					if($dt['superadmin']=='t'){
						$superadmin="YA";
					}else{
						$superadmin="TIDAK";
					}
				?>
				<td class="center"><?php echo $superadmin;?></td>
				<td class="center">
					<a class="btn btn-primary btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/user/password?id=<?php echo $dt['username'];?>')"><i class="ace-icon fa fa-eye"></i></a>
				</td>
				<td class="center">
					<div class="hidden-sm hidden-xs action-buttons">
						<a class="green" onclick="nav('<?php echo $this->baseUrl;?>/user/edit?id=<?php echo $dt['username'];?>')"><i class="ace-icon fa fa-pencil bigger-130"></i></a>
						<a class="red" onclick="confirm('Apakah Anda yakin akan menghapus user ini ? <strong><?php echo str_replace("'", "\'", $dt['nama']);?></strong>','<?php echo $this->baseUrl;?>','/ajax/deluser',new Array('<?php echo $dt['username'];?>'))"><i class="ace-icon fa fa-trash-o bigger-130"></i></a>
					</div>
				</td>
			</tr>
			<?php }?>
		</tbody>
	</table>
</div>
<script src="<?php echo $this->baseUrl;?>/public/assets/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/assets/js/jquery.dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/js/tabel.js"></script>
<script>
	$(function(){tabel('tbl')});
</script>