<form class="form-horizontal" role="form" id="frm">
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Username </label>
		<div class="col-sm-9">
			<input type="text" id="uname" placeholder="username" class="col-xs-10 col-sm-5" value="<?php echo $this->uname;?>" readonly="readonly" />
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nama </label>
		<div class="col-sm-9">
			<input type="text" id="nm" placeholder="Nama" class="col-xs-10 col-sm-5" value="<?php echo $this->nm;?>" readonly="readonly"/>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Password Baru </label>
		<div class="col-sm-9">
			<input type="password" id="pwd1" placeholder="password" class="col-xs-10 col-sm-5" />
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Ketik Ulang Password Baru </label>
		<div class="col-sm-9">
			<input type="password" id="pwd2" placeholder="ketik ulang password" class="col-xs-10 col-sm-5" />
		</div>
	</div>
	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<button class="btn btn-info" type="submit"><i class="ace-icon fa fa-check bigger-110"></i>Submit</button>
			&nbsp; &nbsp; &nbsp;
			<button class="btn" type="reset"><i class="ace-icon fa fa-undo bigger-110"></i>Reset</button>
		</div>
	</div>
</form>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/upduserpwd","/user?new=","u");
	  return false;
	});
</script>