<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Dosen Pembimbing</h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">Periode Akademik</label>
				<div class="col-sm-4">
					<input type="text" id="per" class="form-control" value="<?php echo $this->kd_periode;?>" readonly>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Program Studi</label>
				<div class="col-sm-4">
					<input type="hidden" id="prd" value="<?php echo $this->kd_prodi;?>">
					<input type="text" class="form-control" value="<?php echo $this->nm_prodi;?>" readonly>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Kode Dosen</label>
				<div class="col-sm-4">
					<input type="hidden" id="stdsn" value="1">
					<input type="text" class="form-control" id="kd_dsn" placeholder="klik untuk memilih dosen" onclick="hbox('<?php echo $this->baseUrl;?>','helper/dosen',new Array('kd_dsn','nm_dsn'),new Array('stdsn'))" readonly>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Nama Dosen</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="nm_dsn" placeholder="terisi otomatis dari pilihan dosen" readonly>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">SK Pembimbing</label>
				<div class="col-sm-4">
					<input type="file" class="form-control" id="file2" name="file2" accept="application/pdf" required="required">
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
				<button type="submit" class="btn btn-primary pull-right col-sm-2">Tambah</button>
			</div>
		</div>
	</form>
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbdsbm" class="table table-bordered table-hover">
				<thead align="center">
					<tr>
						<th>NO</th>
						<th>KODE DOSEN</th>
						<th>NAMA DOSEN</th>
						<th>SK PEMBIMBING</th>
						<th>MAHASISWA</th>
						<th>AKSI</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listDosbim as $dataDsbm) { ?>
					<tr>
						<td><?php echo $i; ?></td>
						<td><?php echo $dataDsbm['kd_dosen']; ?></td>
						<td><?php echo $dataDsbm['nm_dosen']; ?></td>
						<td align="center">
							<a class="btn btn-success btn-xs" href="<?php echo $this->baseUrl;?>/image/anyfile?url=public/file/sk/dosbim/<?php echo strtolower(str_replace('.','',$dataDsbm['kd_dosen']).str_replace('/','',$dataDsbm['kd_periode']).$dataDsbm['kd_prodi']).".pdf";?>&newname=<?php echo $dataDsbm['kd_dosen'].".pdf";?>"><i class="fa fa-download">&nbsp;</i>Download</a>
						</td>
						<td align="center">
							<button type="button" class="btn btn-info btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/dosbim/detil?kd=<?php echo $dataDsbm['kd_dosen'];?>&per=<?php echo $this->kd_periode;?>&prd=<?php echo $this->kd_prodi;?>')"><i class="fa fa-eye"></i></button>
						</td>
						<td align="center">
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan menghapus dosen pembimbing ini? <strong><?php echo str_replace("'", "\'", $dataDsbm['nm_dosen']);?></strong>','<?php echo $this->baseUrl;?>','/ajax3/deldsbm',new Array('<?php echo $dataDsbm['kd_dosen'];?>','<?php echo $this->kd_periode;?>','<?php echo $this->kd_prodi;?>'))"><i class="fa fa-remove"></i></button>
						</td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<!-- DataTables -->
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbkls',false,true,true,true,true,false);});</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form2.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmitUpload("frm",["file2"],"","/ajax3/insdsbm","/dosbim/list?new=","u");
	  return false;
	});
</script>