<div class="row">
	<div class="col-sm-8">
		<div class="col-sm-4">Nama (NIM)</div>
		<div class="col-sm-8">: <?php echo $this->nm_mhs." (".$this->nim.")";?></div>
		<div class="col-sm-4">Program Studi</div>
		<div class="col-sm-8">: <?php echo $this->nm_prd;?></div>
		<div class="col-sm-4">Angkatan</div>
		<div class="col-sm-8">: <?php echo $this->akt;?></div>
		<div class="col-sm-4">Status Masuk</div>
		<div class="col-sm-8">: <?php echo $this->stat_msk;?></div>
		<div class="col-sm-4">Gelombang Masuk</div>
		<div class="col-sm-8">: <?php echo $this->nm_gel;?></div>
	</div>
</div>
<form class="form-horizontal" role="form" id="frm">
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Komponen Biaya Sumbangan </label>
		<div class="col-sm-9">
			<input type="hidden" value="<?php echo $this->nim;?>" id="nim">
			<select class="col-xs-10 col-sm-5" id="komp">
				<option value="">&lt;Pilih Komponen Biaya&gt;</option>
				<?php foreach ($this->listKomp as $dtKomp) { ?>
				<option value="<?php echo $dtKomp['id_komp'];?>" ><?php echo $dtKomp['nm_komp'];?></option>					
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Periode Akademik </label>
		<div class="col-sm-9">
			<select class="col-xs-10 col-sm-5" id="per">
				<option value="">&lt;Pilih Periode Akademik&gt;</option>
				<?php foreach ($this->listPer as $dtPer) { ?>
				<?php 
					$arrPer=explode("-",$dtPer['kd_periode']);
					$thn=$arrPer[0];
				?>
				<?php //if($this->akt<=$thn){?>
				<option value="<?php echo $dtPer['kd_periode'];?>" ><?php echo $dtPer['kd_periode'];?></option>
				<?php //}?>					
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Nominal Sumbangan</label>
		<div class="col-sm-9">
			<input type="number" id="nominal" class="col-xs-10 col-sm-5" placeholder="nominal" min="1" max="10000000000" step="0.01">
		</div>
	</div>
	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<button class="btn btn-info" type="submit"><i class="ace-icon fa fa-check bigger-110"></i>Submit</button>
			&nbsp; &nbsp; &nbsp;
			<button class="btn" type="reset"><i class="ace-icon fa fa-undo bigger-110"></i>Reset</button>
		</div>
	</div>
</form>
<div class="table-header">
	Daftar Sumbangan Mahasiswa
</div>
<div>
	<table id="tbl" class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th class="center" width="5%">No</th>
				<th class="center" width="20%">Komponen Biaya</th>
				<th class="center" width="20%">Periode Akademik</th>
				<th class="center" width="12%">Nominal</th>
				<th class="center" width="8%">Aksi</th>
			</tr>
		</thead>
		<tbody>
			<?php $i=1;foreach ($this->listSumbDtl as $dtSumb){?>
			<tr>
				<td><?php echo $i;?></td>
				<td><?php echo $dtSumb['nm_komp'];?></td>
				<td><?php echo $dtSumb['kd_periode'];?></td>
				<td align="right"><?php echo number_format($dtSumb['nominal'],2,',','.');?></td>
				<td class="center">
					<a class="red" onclick="confirm('Apakah Anda yakin akan menghapus sumbangan ini ?','<?php echo $this->baseUrl;?>','/ajax/delsumbangan',new Array('<?php echo $dtSumb['nim'];?>','<?php echo $dtSumb['id_komp'];?>','<?php echo $dtSumb['kd_periode'];?>'))"><i class="ace-icon fa fa-trash-o bigger-130"></i></a>
				</td>
			</tr>
			<?php $i++;}?>
		</tbody>
	</table>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/inssumbangan","/sumbangan/new?nim=<?php echo $this->nim;?>&src=<?php echo $this->src;?>&new=","u");
	  return false;
	});
</script>