<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Data Soal</h3>
</div>
<div class="inqbox-content">
	<div class="panel panel-primary">
		<div class="panel-body">
			<div class="col-sm-2">Nomor Soal</div>
			<div class="col-sm-10">: <?php echo $this->ord;?></div>
			<div class="col-sm-2">Soal</div>
			<div class="col-sm-10">: <?php echo $this->question;?></div>
		</div>
	</div>
	<div class="panel-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="col-md-12">
				<div class="form-group">
					<label class="col-sm-2 control-label">Alfabet Pilihan </label>
					<div class="col-sm-10">
						<input type="hidden" id="id_quiz1" value="<?php echo $this->id_quiz1;?>">
						<select class="form-control" id="ord">
							<option value="1">a</option>
							<option value="2">b</option>
							<option value="3">c</option>
							<option value="4">d</option>
							<option value="5">e</option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Pilihan Jawaban </label>
					<div class="col-sm-10">
						<textarea id="choice" class="form-control" placeholder="pilihan jawaban" rows="8"></textarea>
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="box-footer col-sm-6">
					<button type="submit" class="btn btn-primary pull-right col-sm-4" id="btnsbm">Tambah</button>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-4" id="btnres">Reset</button>
				</div>
			</div>
		</form>
	</div>
	<div class="table-responsive">
		<table id="tbkls" class="table table-bordered table-hover">
			<thead align="center">
				<tr>
					<th width="5%">NO</th>
					<th>PILIHAN</th>
					<th width="15%">JAWABAN BENAR</th>
					<th width="15%">PILIH JAWABAN</th>
					<th width="10%">AKSI</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=a;foreach ($this->listPilihan as $dataQuiz2) { ?>
				<tr>
					<td><?php echo $i; ?></td>
					<td><?php echo $dataQuiz2['choice']; ?></td>
					<td align="center">
						<?php if($this->jawaban==$dataQuiz2['id_quiz2']){ ?>
						<i class="fa fa-star"></i>
						<?php } ?>
					</td>
					<td align="center">
						<?php if($this->jawaban!=$dataQuiz2['id_quiz2']){ ?>
						<button type="button" class="btn btn-warning btn-xs" onclick="confirm('Apakah Anda yakin memilih pilihan ini sebagai jawaban benar ? ','<?php echo $this->baseUrl;?>','/ajax/updjawabanquiz1',new Array('<?php echo $this->id_quiz1;?>','<?php echo $dataQuiz2['id_quiz2'];?>'))"><i class="fa fa-check"></i></button>
						<?php } ?>
					</td>
					<td align="center">
						<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan menghapus data ini? ','<?php echo $this->baseUrl;?>','/ajax/delquiz2',new Array('<?php echo $dataQuiz2['id_quiz2'];?>'))"><i class="fa fa-remove"></i></button>
					</td>
				</tr>
				<?php $i++; } ?>
		</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/insquiz2","/quiz/index3?id=<?php echo $this->id_quiz1;?>&new=","u");
	  return false;
});
</script>
<script>
        document.addEventListener("DOMContentLoaded", function(event) { 
            var scrollpos = localStorage.getItem('scrollpos');
            if (scrollpos) window.scrollTo(0, scrollpos);
        });

        window.onbeforeunload = function(e) {
            localStorage.setItem('scrollpos', window.scrollY);
        };
</script>