<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker-bs3.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data User</h3>
	</div>
	<div class="box-body">
		<div class="col-md-6">
			<form class="form-horizontal" method="post" id="frm">
				<div class="box-body">
					<div class="form-group">
						<label class="col-sm-4 control-label">Username</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="uname" placeholder="username" value="<?php echo $this->uname;?>" readonly>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Nama</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="nm" placeholder="nama" maxlength="40" value="<?php echo $this->nm;?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Email</label>
						<div class="col-sm-8">
							<input type="email" class="form-control" id="email" placeholder="email" value="<?php echo $this->email;?>">
						</div>
					</div>
					<div class="box-footer col-sm-12">
						<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
						<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan</button>
					</div>
				</div>
			</form>
		</div>
		<div class="col-md-6">
			<form class="form-horizontal" method="post" id="frm2">
				<div class="box-body">
					<div class="form-group">
						<label class="col-sm-4 control-label">Password Baru</label>
						<div class="col-sm-8">
							<input type="hidden" id="uname" value="<?php echo $this->uname;?>">
							<input type="password" class="form-control" id="pwd1" placeholder="password" maxlength="30">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Password Sekali Lagi</label>
						<div class="col-sm-8">
							<input type="password" class="form-control" id="pwd2" placeholder="password" maxlength="30">
						</div>
					</div>
					<div class="box-footer col-sm-12">
						<button type="submit" class="btn btn-danger pull-right col-sm-4" id="btnres">GANTI PASSWORD</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/alert.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax4/upduser","/profile/index?new=","u");
	  return false;
	});
	$("#frm2").submit(function() {
		ajaxSubmit("frm2","<?php echo $this->baseUrl;?>","/ajax4/upduserpwd","/profile/index?&new=","u");
	  return false;
	});
</script>