<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/assets/css/chosen.min.css" />
<form class="form-horizontal" role="form" id="frm">
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Angkatan </label>
		<div class="col-sm-9">
			<select id="akt"  multiple="multiple" class="chosen-select col-xs-10 col-sm-5" data-placeholder="pilih angkatan" name="akt">
				<?php foreach ($this->listAkt as $dataAngkatan) { ?>
				<option value="<?php echo $dataAngkatan['id_angkatan']; ?>"><?php echo $dataAngkatan['id_angkatan']; ?></option>
				<?php } ?>
			</select>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Program Studi </label>
		<div class="col-sm-9">
			<select id="prd"  multiple="multiple" class="chosen-select col-xs-10 col-sm-5" data-placeholder="pilih program studi" name="prd">
				<?php foreach ($this->listProdi as $dtProdi) { ?>
				<option value="<?php echo $dtProdi['kd_prodi']; ?>"><?php echo $dtProdi['nm_prodi']; ?></option>
				<?php } ?>
			</select>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Periode Akademik </label>
		<div class="col-sm-9">
			<select id="per" class="col-xs-10 col-sm-5">
				<option value="">&lt;Pilih Periode Akademik&gt;</option>
				<?php foreach ($this->listPeriode as $dtPer) { ?>
				<option value="<?php echo $dtPer['kd_periode'];?>"><?php echo $dtPer['kd_periode']?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<button class="btn btn-info" type="submit"><i class="ace-icon fa fa-search bigger-110"></i>Show</button>
		</div>
	</div>
</form>
<script src="<?php echo $this->baseUrl;?>/public/assets/js/chosen.jquery.min.js"></script>
<script type="text/javascript">$('.chosen-select').chosen({allow_single_deselect:true});</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
		var type=$('#type').val();
	    ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/showreport?t="+type,"/report/show","s");
	    return false;
	  });
	});
</script>