<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Paket Kelas</h3>
	</div>
	<div class="box-body">
		<div class="col-md-6">
			<div class="col-sm-4">Program Studi</div>
			<div class="col-sm-8">: <?php echo $this->nm;?></div>			
		</div>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">Periode Akademik</label>
				<input type="hidden" id="prd" value="<?php echo $this->kd;?>">
				<div class="col-sm-4">
					<select class="form-control" id="per">
						<option disabled selected value="">pilih periode akademik</option>
						<?php foreach ($this->listPeriode as $dt) { ?>
						<option value="<?php echo $dt['kd_periode']?>"><?php echo $dt['kd_periode']?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Range Nilai</label>
				<div class="col-sm-4">
					<select class="form-control" id="range">
						<option disabled selected value="">pilih range nilai</option>
						<?php foreach ($this->listRange as $dtRange) { ?>
						<option value="<?php echo $dtRange['id_range_hdr']?>"><?php echo $dtRange['nama_range']?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="submit" class="btn btn-primary pull-right col-sm-2" id="btnsbm">Tambah</button>
				<button type="reset" class="btn btn-default pull-left col-sm-2" id="btnres">Reset</button>
			</div>
		</div>
	</form>
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbrule" class="table table-bordered table-hover">
				<thead align="center">
					<tr>
						<th>NO</th>
						<th>PERIODE AKADEMIK</th>
						<th>KODE RANGE NILAI</th>
						<th>NAMA RANGE NILAI</th>
						<th>AKSI</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listRuleNilai as $dataRule) { ?>
					<tr>
						<td><?php echo $i; ?></td>
						<td><?php echo $dataRule['kd_periode'];?></td>
						<td><?php echo $dataRule['id_range_hdr'];?></td>
						<td><?php echo $dataRule['nama_range']; ?></td>
						<td align="center">
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan menghapus aturan nilai prodi ini?<br><strong><?php echo str_replace("'", "\'", $this->nm."<br>".$dataRule['kd_periode']);?></strong>','<?php echo $this->baseUrl;?>','/ajax2/delrule',new Array('<?php echo $dataRule['kd_prodi'];?>','<?php echo $dataRule['kd_periode'];?>'))"><i class="fa fa-remove"></i></button>
						</td>
					</tr>
					<?php $i++; } ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbrule',true,true,true,true,true,false);});</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax2/insrule","/rulenilai/list?kd=<?php echo $this->kd;?>&new=","u");
	  return false;
	});
</script>