<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/plugins/select2/select2.min.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/dist/css/AdminLTE.min.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker-bs3.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Mahasiswa Keluar</h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">NIM</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="nim" placeholder="klik untuk pilih mahasiswa" maxlength="20" readonly value="<?php echo $this->nim;?>">
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Nama Mahasiswa</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="nm_mhs" placeholder="terisi otomatis dari pilihan mahasiswa" readonly value="<?php echo $this->nm_mhs;?>">
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Tanggal Keluar</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="tglout" placeholder="tanggal keluar" readonly tgl value="<?php echo $this->tglout;?>">
				</div>
			</div>
			<div class="form-group">
					<label class="col-sm-2 control-label">Keterangan Keluar</label>
					<div class="col-sm-4">
						<select class="form-control" id="jns_kel">
							<?php foreach ($this->listJnsKeluar as $dt) { ?>
							<?php
								if($dt['id_jns_keluar']==$this->jns_kel){
								  $kel="selected";
								}else{
								  $kel="";
								}
								?>
							<?php if($dt['id_jns_keluar']!=1){ ?>
							<option value="<?php echo $dt['id_jns_keluar']?>" <?php echo $kel;?>><?php echo $dt['ket_keluar']?></option>
							<?php } ?>
							<?php } ?>
						</select>
					</div>
				</div>
			<div class="box-footer col-sm-6">
				<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
				<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan</button>
			</div>
		</div>
	</form>
</div>
<script src="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/moment.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker.js"></script>
<script>
	$(function(){$("[tgl]").daterangepicker({singleDatePicker:true,format:'DD MMMM YYYY'});});
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax3/insmout","/mhsout/list?new=","u");
	  return false;
	});
</script>