<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="box box-info">
	<div class="box-header with-border">
		<div class="col-sm-8">
			<strong>
			ANGKATAN : <?php echo $this->akt; ?>
			</strong>
		</div>
		<div class="col-sm-8">
			<strong>
			PROGRAM STUDI : <?php echo $this->prd; ?>
			</strong>
		</div>
		<div class="col-sm-8">
			<strong>
			TANGGAL LULUS : <?php echo $this->startdate." s/d ".$this->enddate; ?>
			</strong>
		</div>
	</div>
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbalm" class="table table-bordered table-hover" style="width:1400px">
				<thead align="center">
					<tr>
						<th width="12%">NIM</th>
						<th>NAMA MAHASISWA</th>
						<th width="5%">ANGKATAN</th>
						<th width="15%">PROGRAM STUDI</th>
						<th width="8%">STATUS</th>
						<th width="12%">TANGGAL</th>
						<th width="15%">KETERANGAN</th>
						<th width="5%">AKSI</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->listMhsOut as $dataAlm) { ?>
					<tr>
						<td><?php echo $dataAlm['nim']; ?></td>
						<td><?php echo $dataAlm['nm_mhs']; ?></td>
						<td align="center"><?php echo $dataAlm['id_angkatan']; ?></td>
						<td><?php echo $dataAlm['nm_prodi']; ?></td>
						<td align="center"><?php echo $dataAlm['status_mhs']; ?></td>
						<td><?php echo $dataAlm['tgl_keluar_fmt']; ?></td>
						<td align="center"><?php echo $dataAlm['ket_keluar']; ?></td>
						<td align="center">
							<button type="button" class="btn btn-warning btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/mhsout/edit?nim=<?php echo $dataAlm['nim'];?>')"><i class="fa fa-pencil"></i></button>
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan membatalkan status keluar mahasiswa ini? <strong><?php echo str_replace("'", "\'", $dataAlm['nm_mhs']);?></strong>','<?php echo $this->baseUrl;?>','/ajax3/delmout',new Array('<?php echo $dataAlm['nim'];?>'))"><i class="fa fa-remove"></i></button>
						</td>
					</tr>
					<?php } ?>
			</table>
		</div>
	</div>
</div>
<!-- DataTables -->
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbalm',true,true,true,true,true,false);});</script>