<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
<div class="inqbox-title border-top-danger">
	 <h5>Form Her-Registrasi</h5>
</div>
<div class="inqbox-content">
	<?php if($this->allowReg==1){?>
		<form method="post" id="frm" class="form-horizontal"> 
			<div class="form-group">
 				<label class="col-sm-3 control-label">Periode Akademik</label>
 				<label class="col-sm-4"><?php echo $this->per;?></label>
 			</div>
 			<div class="form-group">
 				<label class="col-sm-3 control-label">Status Her-Registrasi</label>
 				<div class="col-sm-4">
 					<input type="text" id="per" value="<?php echo $this->per;?>" style="display:none;">
					<select id="kd_reg" class="form-control">
						<option value="" disabled="disabled" selected="selected">pilih status her-registrasi</option>
						<?php foreach ($this->listStatReg as $dtStat) { ?>
						<option value="<?php echo $dtStat['kd_status_reg'];?>" ><?php echo $dtStat['status_reg'];?></option>
						<?php } ?>
					</select>
 				</div>
 			</div>
 			<div class="form-group">
 				<div class="col-sm-4 col-sm-offset-3">
 					<button class="btn btn-white" type="reset">Batal</button>
 					<button class="btn btn-primary" type="submit">Her-Register</button>
 				</div>
 			</div>
		</form>
		<div class="alert alert-info">
			Setelah Anda melakukan <strong>Her-Registrasi</strong>, langkah selanjutnya adalah mengisi form KRS dengan klik button pada kolom <strong>KRS</strong>
		</div>
	<?php }else{?>
	<div class="alert alert-warning">
		Saat ini (<strong><?php echo date("d F Y") ?></strong>) tidak dalam jadwal <strong>Her-Registrasi</strong>
	</div>
	<?php }?>
</div>
<div class="inqbox-title border-top-danger">
	 <h5>Histori Her-Registrasi</h5>
</div>
<div class="inqbox-content">
	<div class="table-responsive">
		<table class="table table-striped table-bordered table-hover" id="tbreg">
			<thead align="center">
				<tr>
					<th>NO</th>
					<th>PERIODE AKADEMIK</th>
					<th>STATUS REGISTRASI</th>
					<th>KRS</th>
					<th>AKSI</th>
				</tr>
			</thead>
			<tbody>
				<?php $n=1;foreach ($this->listRegister as $dataReg) { ?>
				<?php
					$stat_reg=$dataReg['status_reg']."(".$dataReg['status_mhs_periode'].")";
					$aksi="Cancel";
					$class="warning";
					$disCancel="1";
					if(($dataReg['kd_periode']==$this->per)and($this->allowReg==1)){
						$disCancel="0";
					}
					if(($dataReg['krs']=='f')or($dataReg['krs']==null)){
						$krs="disabled";
					}else{
						$krs="";
					}
					?>
				<tr>
					<td align="center"><?php echo $n; ?></td>
					<td align="center"><?php echo $dataReg['kd_periode']; ?></td>
					<td align="center"><?php echo $stat_reg; ?></td>
					<td align="center"><button type="button" class="btn btn-primary btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/krs/index?per=<?php echo $dataReg['kd_periode'];?>')" <?php echo $krs;?>><i class="fa fa-list"></i></button></td>
					<td align="center">
						<?php if($disCancel=="0"){?>
						<button type="button" class="btn btn-<?php echo $class;?> btn-xs" onclick="confirm('Apakah Anda yakin membatalkan registrasi ini?','<?php echo $this->baseUrl;?>','/ajax/delreg', new Array ('<?php echo $dataReg['nim'];?>','<?php echo $dataReg['kd_periode'];?>'))" ><?php echo $aksi; ?></button>
						<?php }else{?>
						<?php }?>
					</td>
				</tr>
				<?php $n++;} ?>
		</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/insreg","/register?new=","u");
	  return false;
	});
</script>