<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<?php if($this->listcount < 1){ ?> 
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Info Program Studi</h3>
	</div>
	<div class="box-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="box-body">
                <div class="form-group">
					<label class="col-sm-2 control-label">Capaian KKNI (indonesia)</label>
					<div class="col-sm-4">
						<input type="hidden" id="kd" value="<?php echo $this->kd; ?>">
						<input type="text" class="form-control" id="capaian_kkni_id" placeholder="Capaian KKNI (indonesia)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Capaian KKNI (english)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="capaian_kkni_en" placeholder="Capaian KKNI (english)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Capaian Asosisasi (indonesia)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="capaian_asosiasi_id" placeholder="Capaian Asosisasi (indonesia)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Capaian Asosisasi (english)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="capaian_asosiasi_en" placeholder="Capaian Asosisasi (english)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Capaian Perguruan Tingggi (indonesia)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="capaian_pt_major_id" placeholder="Capaian Perguruan Tingggi (indonesia)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Capaian Perguruan Tingggi (english)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="capaian_pt_major_en" placeholder="Capaian Perguruan Tingggi (english)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Capaian Perguruan Tinggi (Pendukung) (indonesia)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="capaian_pt_minor_id" placeholder="Capaian Perguruan Tinggi (Pendukung) (indonesia)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Capaian Perguruan Tinggi (Pendukung) (english)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="capaian_pt_minor_en" placeholder="Capaian Perguruan Tinggi (Pendukung) (english)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Capaian Lain (indonesia)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="capaian_pt_other_id" placeholder="Capaian Lain (indonesia)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Capaian Lain (english)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="capaian_pt_other_en" placeholder="Capaian Lain (english)">
					</div>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
					<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan</button>
				</div>
			</div>
		</form>
	</div>
</div>
<?php } ?>
<div class="box box-info">
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbroom" class="table table-bordered table-hover">
				<thead align="center">
					<tr>
						<th>KODE PRODI</th>
						<th>LABEL SKPI</th>
                        <th>CAPAIAN KKNI</th>
                        <th>CAPAIAN ASOSIASI</th>
                        <th>CAPAIAN PERGURUAN TINGGI</th>
                        <th>CAPAIAN PERGURUAN TINGGI (Pendukung)</th>
                        <th>CAPAIAN LAIN</th>
						<th>AKSI</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listProdiSkpiLabel as $data) { ?>
					<tr>
						<td><?php echo $data['kd_prodi']; ?></td>
						<td><?php echo $data['nm_prodi']; ?></td>
                        <td><button type="button" class="btn btn-info btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/prodi/capaian1?id=<?php echo $data['id_prodi_skpi_label'];?>')"><?php echo $data['capaian_kkni_id'].'('.$data['capaian_kkni_en'].')'; ?></button></td>
						<td><button type="button" class="btn btn-info btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/prodi/capaian2?id=<?php echo $data['id_prodi_skpi_label'];?>')"><?php echo $data['capaian_asosiasi_id'].'('.$data['capaian_asosiasi_en'].')'; ?></button></td>
                        <td><button type="button" class="btn btn-info btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/prodi/capaian3?id=<?php echo $data['id_prodi_skpi_label'];?>')"><?php echo $data['capaian_pt_major_id'].'('.$data['capaian_pt_major_en'].')'; ?></button></td>
                        <td><button type="button" class="btn btn-info btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/prodi/capaian4?id=<?php echo $data['id_prodi_skpi_label'];?>')"><?php echo $data['capaian_pt_minor_id'].'('.$data['capaian_pt_minor_en'].')'; ?></button></td>
                        <td><button type="button" class="btn btn-info btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/prodi/capaian5?id=<?php echo $data['id_prodi_skpi_label'];?>')"><?php echo $data['capaian_pt_other_id'].'('.$data['capaian_pt_other_en'].')'; ?></button></td>
						<td align="center">
							<button type="button" class="btn btn-warning btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/prodi/edit3?id=<?php echo $data['id_prodi_skpi_label'];?>')"><i class="fa fa-pencil"></i></button>
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan menghapus prodi ini ? <strong><?php echo str_replace("'", "\'", $data['nm_prodi']);?></strong>','<?php echo $this->baseUrl;?>','/ajax4/delprdskpilabel',new Array('<?php echo $data['id_prodi_skpi_label'];?>'))"><i class="fa fa-remove"></i></button>
						</td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<!-- DataTables -->
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbroom',true,true,true,true,true,false);});</script>
<!-- Form Action -->
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax4/insprdskpilabel","/prodi/detil2?kd=<?php echo $this->kd; ?>&new=","u");
	  return false;
	});
</script>