<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<?php if($this->listcount < 1){ ?> 
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Info Program Studi</h3>
	</div>
	<div class="box-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="box-body">
                <div class="form-group">
					<label class="col-sm-2 control-label">Gelar (indonesia)</label>
					<div class="col-sm-4">
						<input type="hidden" id="kd" value="<?php echo $this->kd; ?>">
						<input type="text" class="form-control" id="gelar_id" placeholder="Gelar (indonesia)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Gelar (english)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="gelar_en" placeholder="Gelar (english)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Jenis Pendidikan (indonesia)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="jenis_pend_id" placeholder="Jenis Pendidikan (indonesia)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Jenis Pendidikan (english)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="jenis_pend_en" placeholder="Jenis Pendidikan (english)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Syarat Pendidikan (indonesia)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="req_pend_id" placeholder="Syarat Pendidikan (indonesia">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Syarat Pendidikan (english)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="req_pend_en" placeholder="Syarat Pendidikan (english)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Bahasa (indonesia)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="bahasa_id" placeholder="Bahasa (indonesia)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Bahasa (english)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="bahasa_en" placeholder="Bahasa (english)">
					</div>
				</div>
		<div class="form-group">
					<label class="col-sm-2 control-label">Studi lanjutan (indonesia)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="lanjut_id" placeholder="Studi lanjutan (indonesia)">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Studi lanjutan (english)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="lanjut_en" placeholder="Studi lanjutan (english)">
					</div>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
					<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan</button>
				</div>
			</div>
		</form>
	</div>
</div>
<?php } ?>
<div class="box box-info">
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbroom" class="table table-bordered table-hover">
				<thead align="center">
					<tr>
						<th>KODE PRODI</th>
						<th>NAMA PROGRAM STUDI</th>
                        			<th>GELAR</th>
                        			<th>JENIS PENDIDIKAN</th>
                        			<th>SYARAT PENDIDIKAN</th>
                        			<th>BAHASA</th>
						<th>STUDI LANJUTAN</th>
						<th>AKSI</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listProdiInfo as $data) { ?>
					<tr>
						<td><?php echo $data['kd_prodi']; ?></td>
						<td><?php echo $data['nm_prodi']; ?></td>
			                        <td><?php echo $data['gelar_id'].'<br><i>('.$data['gelar_en'].')</i>'; ?></td>
                        			<td><?php echo $data['jenis_pend_id'].'<br><i>('.$data['jenis_pend_en'].')</i>'; ?></td>
			                        <td><?php echo $data['req_pend_id'].'<br><i>('.$data['req_pend_en'].')</i>'; ?></td>
                        			<td><?php echo $data['bahasa_id'].'<br><i>('.$data['bahasa_en'].')</i>'; ?></td>
						<td><?php echo $data['studi_lanjut_id'].'<br><i>('.$data['studi_lanjut_en'].')</i>'; ?></td>
						<td align="center">
							<button type="button" class="btn btn-warning btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/prodi/edit2?kd=<?php echo $data['kd_prodi'];?>')"><i class="fa fa-pencil"></i></button>
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan menghapus prodi ini ? <strong><?php echo str_replace("'", "\'", $data['nm_prodi']);?></strong>','<?php echo $this->baseUrl;?>','/ajax4/delprdinfo',new Array('<?php echo $data['kd_prodi'];?>'))"><i class="fa fa-remove"></i></button>
						</td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<!-- DataTables -->
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbroom',true,true,true,true,true,false);});</script>
<!-- Form Action -->
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax4/insprdinfo","/prodi/detil?kd=","u");
	  return false;
	});
</script>