<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker-bs3.css">
<div class="box box-info">
	<div class="box-header with-border">
	<h3 class="box-title">DETIL DATA PRODI <?php echo $this->nm; ?> CAPAIAN ASOSIASI</h3>
	</div>
	<div class="box-body">
		<form class="form-horizontal" method="post" id="frm">
            <div class="box-body">
                <div class="form-group">
					<label class="col-sm-2 control-label">Label SKPI</label>
					<div class="col-sm-4">
						<input type="hidden" id="id" value="<?php echo $this->id; ?>">
                        <input type="hidden" id="id_prodi_skpi_label" value="<?php echo $this->id_prodi_skpi_label; ?>">
						<input type="text" class="form-control" value="<?php echo $this->nm; ?>" readonly>
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Capaian Asosiasi (indonesia)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" value="<?php echo $this->kkni_in; ?>" readonly>
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Capaian Asosiasi (english)</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" value="<?php echo $this->kkni_en; ?>" readonly>
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Urutan</label>
					<div class="col-sm-4">
						<input type="number" class="form-control" id="urutan" placeholder="Urutan" value="<?php echo $this->urutan; ?>">
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Apakah Ada Nomer?</label>
					<div class="col-sm-4">
                    	<select class="form-control" id="is_numbered" >
                            <option value="t" <?php if($this->is_numbered == 't') echo 'selected';?>>Ya</option>
                            <option value="f" <?php if($this->is_numbered == 'f') echo 'selected';?>>Tidak</option>
                        </select>
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Keterangan (indonesia)</label>
					<div class="col-sm-4">
						<textarea class="form-control" id="keterangan_id" rows="3" placeholder="Keterangan (indonesia)"><?php echo $this->keterangan_id; ?></textarea>
					</div>
				</div>
                <div class="form-group">
					<label class="col-sm-2 control-label">Keterangan (english)</label>
					<div class="col-sm-4">
						<textarea class="form-control" id="keterangan_en" rows="3" placeholder="Keterangan (english)"><?php echo $this->keterangan_en; ?></textarea>
					</div>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
					<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan</button>
				</div>
			</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax4/updprdcapaian2","/prodi/capaian2?id=","u");
	  return false;
	});
</script>