<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker-bs3.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Program Studi</h3>
	</div>
	<div class="box-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="box-body">
				<div class="form-group">
					<label class="col-sm-2 control-label">Kode Program Studi</label>
					<div class="col-sm-4">
						<input type="hidden" id="old_kd" value="<?php echo $this->kd; ?>">
						<input type="text" class="form-control" id="kd" placeholder="kode program studi" maxlength="8" value="<?php echo $this->kd;?>">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Nama Program Studi</label>
					<div class="col-sm-4">
						<input type="text" class="form-control" id="nm" placeholder="nama program studi" maxlength="40" value="<?php echo $this->nm;?>">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Jenjang Prodi</label>
					<div class="col-sm-4">
						<select class="form-control" id="jenjang">
							<option disabled value="" selected>pilih jenjang</option>
							<?php foreach ($this->listJenjang as $data) {?>
							<?php
								if($data['id_jenjang_prodi']==$this->jenjang){
									$jenjang="selected";
								}else{
									$jenjang="";
								}
								?>
							<option value="<?php echo $data['id_jenjang_prodi'];?>" <?php echo $jenjang;?> ><?php echo $data['nama_jenjang'];?></option>
							<?php } ?>
						</select>
					</div>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
					<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan</button>
				</div>
			</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax4/updprd","/prodi/index?new=","u");
	  return false;
	});
</script>