<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker-bs3.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Kalender Akademik Periode <?php echo $this->per; ?></h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">Agenda Akademik</label>
				<div class="col-sm-4">
					<input type="hidden" id="per" value="<?php echo $this->per;?>">
					<select id="aktAkd" class="form-control">
						<option value="" disabled="disabled" selected>pilih agenda akademik</option>
						<?php foreach ($this->listAktAkd as $dtAktAkd){ ?>
						<option value="<?php echo $dtAktAkd['kd_aktivitas']?>"><?php echo $dtAktAkd['deskripsi']?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Tanggal Mulai</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="startdate" placeholder="tanggal mulai" readonly tgl>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Tanggal Selesai</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="enddate" placeholder="tanggal selesai" readonly tgl>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
				<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan</button>
			</div>
		</div>
	</form>
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbakt" class="table table-bordered table-hover">
				<thead align="center">
					<tr>
						<th width="35%">TANGGAL</th>
						<th>AGENDA AKADEMIK</th>
						<th width="10%">AKSI</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listKalender as $data) { ?>
					<tr>
						<td><?php echo $data['start_date_fmt']." s/d ".$data['end_date_fmt']; ?></td>
						<td><?php echo $data['deskripsi']; ?></td>
						<td align="center">
							<button type="button" class="btn btn-warning btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/kalender/edit?per=<?php echo $data['kd_periode'];?>&akt=<?php echo $data['kd_aktivitas'];?>')"><i class="fa fa-pencil"></i></button>
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan menghapus agenda akademik ini ? <strong><?php echo $data['deskripsi'];?></strong>','<?php echo $this->baseUrl;?>','/ajax2/delkal',new Array('<?php echo $data['kd_periode'];?>','<?php echo $data['kd_aktivitas'];?>'))"><i class="fa fa-remove"></i></button>
						</td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/moment.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/daterangepicker/daterangepicker.js"></script>
<script>
	$(function () {
		$(function(){$("[tgl]").daterangepicker({singleDatePicker:true,format:'DD MMMM YYYY'});});
	});
</script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbakt',true,true,true,true,true,false);});</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax2/inskal","/kalender/index?id=<?php echo $this->per;?>&new=","u");
	  return false;
	});
</script>