<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="box  box-info">
	<div class="box-header with-border" class="col-sm-2">
		<div class="col-sm-8">
			<strong>
			PROGRAM STUDI : <?php echo $this->prd;?>
			</strong>
		</div>
	</div>
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbmk" class="table table-bordered table-hover">
				<thead align="center">
					<tr>
						<th>NO</th>
						<th>NAMA MATA KULIAH</th>
						<th>PROGRAM STUDI</th>
						<th>AKSI</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;foreach ($this->listMk as $dataMk) { ?>
					<tr>
						<td><?php echo $i; ?></td>
						<td><?php echo $dataMk['nm_mk']; ?></td>
						<td><?php echo $dataMk['nm_prodi']; ?></td>
						<td align="center">
							<button type="button" class="btn btn-warning btn-xs" onclick="nav('<?php echo $this->baseUrl;?>/matkul/edit?id=<?php echo $dataMk['id_mk'];?>')"><i class="fa fa-pencil"></i></button>
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan menghapus mata kuliah ini? <strong><?php echo str_replace("'", "\'", $dataMk['nm_mk']);?></strong>','<?php echo $this->baseUrl;?>','/ajax/delmatkul',new Array('<?php echo $dataMk['id_mk'];?>'))"><i class="fa fa-remove"></i></button>
						</td>
					</tr>
					<?php $i++; } ?>
			</table>
		</div>
	</div>
</div>
<!-- DataTables -->
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl?>/public/js/tabel.js"></script>
<script>$(function () {tabel('tbmk',true,true,true,true,true,false);});</script>