<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/plugins/morris/morris.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/plugins/select2/select2.min.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/dist/css/AdminLTE.min.css">
<?php //echo $this->x;?>
<?php if(!$this->chart){?>
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Filter </h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">FILTER : STATUS DOSEN</label>
				<div class="col-sm-4">
					<select id="stat" class="form-control select2" multiple="multiple" data-placeholder="pilih status dosen" name="stat">
						<option value="t">Aktif</option>
						<option value="f">Tidak Aktif</option>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">PARAMETER</label>
				<input type="hidden" id="cht" value="1">
				<div class="col-sm-4">
					<select id="par" class="form-control" data-placeholder="pilih parameter" name="par">
						<option value="kat_dosen">Kelompok Dosen</option>
						<option value="jk">Jenis Kelamin</option>
						<option value="jab_dosen">Jabatan</option>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="submit" class="btn btn-info pull-right col-sm-2">Show</button>
			</div>
		</div>
	</form>
</div>
<?php }else{ ?>
<div class="box box-success">
	<div class="box-header with-border">
		<h3 class="box-title">Report Chart Dosen</h3>
		<div class="box-tools pull-right">
			<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		</div>
		<div class="box-body chart-responsive">
			<div class="chart" id="cht_dsn" style="height: 300px;"></div>
		</div>
	</div>
</div>
<?php } ?>
<script src="<?php echo $this->baseUrl;?>/public/plugins/select2/select2.full.min.js"></script>
<script>
	$("#stat").select2();
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
	    ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax5/showdsncht","/dosen/report","s");
	    return false;
	  });
	});
</script>
<script src="<?php echo $this->baseUrl;?>/public/plugins/morris/raphael.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/plugins/morris/morris.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/plugins/morris/html2canvas.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/js/chart.js"></script>
<script>
	$(function () {
		chart2('cht_dsn',<?php echo json_encode($this->data);?>);	   
	});
</script>