<div class="row">
	<div class="col-sm-8">
		<div class="col-sm-4">Program Studi</div>
		<div class="col-sm-8">: <?php echo $this->prd;?></div>
		<div class="col-sm-4">Angkatan</div>
		<div class="col-sm-8">: <?php echo $this->akt;?></div>
		<div class="col-sm-4">Status Masuk</div>
		<div class="col-sm-8">: <?php echo $this->sm;?></div>
		<div class="col-sm-4">Gelombang</div>
		<div class="col-sm-8">: <?php echo $this->gel;?></div>
		<div class="col-sm-4">Komponen Biaya</div>
		<div class="col-sm-8">: <?php echo $this->kom;?></div>
		<div class="col-sm-4">Paket Biaya</div>
		<div class="col-sm-8">: <?php echo $this->pkt;?></div>
		<div class="col-sm-4">Nominal Biaya (Default)</div>
		<div class="col-sm-8">: <?php echo number_format($this->nom,2,',','.');?></div>
	</div>
</div>
<div>
	<form class="form-horizontal" role="form" id="frm">
		<div class="form-group">
			<input type="hidden" id="akt" value="<?php echo $this->akt;?>">
			<input type="hidden" id="prd" value="<?php echo $this->kdprd;?>">
			<input type="hidden" id="sm" value="<?php echo $this->idsm;?>">
			<input type="hidden" id="gel" value="<?php echo $this->idgel;?>">
			<input type="hidden" id="komp" value="<?php echo $this->idkom;?>">
			<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Status Her-Registrasi</label>
			<div class="col-sm-9">
				<select class="col-xs-10 col-sm-5" id="statreg">
					<option value="" disabled="disabled" selected="selected">pilih status her-registrasi</option>
					<?php foreach ($this->listStatReg as $dtStReg){?>
					<option value="<?php echo $dtStReg['kd_status_reg'];?>"><?php echo $dtStReg['status_reg']?></option>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Nominal Formula</label>
			<div class="col-sm-9">
				<input type="number" id="nomform" class="col-xs-10 col-sm-5" placeholder="nominal formula" min="1" max="10000000000" step="0.01" value="<?php echo $this->nom;?>">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Periode Akademik</label>
			<div class="col-sm-9">
				<select class="col-xs-10 col-sm-5" id="per">
					<option value="" disabled="disabled" selected="selected">pilih periode</option>
					<?php foreach ($this->listThn as $dtThn){?>
					<?php foreach ($this->listSmtPer as $dtSmt){?>
					<option value="<?php echo $dtThn['tahun_keu']."-".$dtSmt['id_smt'];?>">
						<?php echo intval($this->akt)+intval($dtThn['tahun_keu'])-1;?>-<?php echo intval($this->akt)+intval($dtThn['tahun_keu'])?>/<?php echo $dtSmt['id_smt']?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Formula Biaya</label>
			<div class="col-sm-9">
				<select class="col-xs-10 col-sm-5" id="rule">
					<option value="" disabled="disabled" selected="selected">pilih formula biaya</option>
					<?php foreach ($this->listRule as $dtRule){?>
					<option value="<?php echo $dtRule['id_rule'];?>">
						<?php echo $dtRule['nm_rule'];?>
					</option>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Nominal/Parameter</label>
			<div class="col-sm-9">
				<select class="col-xs-10 col-sm-5 hidden" id="par">
					<option value="" disabled="disabled" selected="selected">pilih parameter biaya</option>
					<?php foreach ($this->listParam as $dtParam){?>
					<option value="<?php echo $dtParam['id_param'];?>">
						<?php echo $dtParam['nm_param'];?>
					</option>
					<?php }?>
				</select>
				<input type="number" id="nomfix" class="col-xs-10 col-sm-5 hidden" placeholder="nominal fix" min="1" max="10000000000" step="0.01">
				<input type="number" id="multiply" class="col-xs-10 col-sm-5 hidden" placeholder="bilangan pengali" min="1" max="10000000000" step="0.01">
			</div>
		</div>
		<div class="clearfix form-actions">
			<div class="col-md-offset-3 col-md-9">
				<button class="btn btn-info" type="submit" sb value="<?php echo $i;?>"><i class="ace-icon fa fa-check bigger-110"></i>Submit</button>
				&nbsp; &nbsp; &nbsp;
				<button class="btn" type="reset" id="reset"><i class="ace-icon fa fa-undo bigger-110"></i>Reset</button>
			</div>
		</div>
	</form>
</div>
<div>
	<?php foreach ($this->listStatReg as $dtStatReg) { ?>
	<h5><strong>Status Her Registrasi Mahasiswa : <?php echo $dtStatReg['status_reg'];?></strong></h5>
	<table class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th class="center" width="5%">No</th>
				<th class="center" width="20%">Periode Akademik</th>
				<th class="center" width="15%">Nominal Formula</th>
				<th class="center">Formula</th>
				<th class="center" width="15%">Nominal/Parameter</th>
				<th class="center" width="10%">Aksi</th>
			</tr>
		</thead>
		<tbody>
			<?php $i=1;foreach ($this->listFormula as $dtFormula) { ?>
			<?php if($dtFormula['kd_status_reg']==$dtStatReg['kd_status_reg']){?>
			<tr>
				<td class="center"><?php echo $i;?></td>
				<td>
					<?php $thnAwal=$this->akt+$dtFormula['tahun_keu']-1;?>
					<?php $thnAkhir=$this->akt+$dtFormula['tahun_keu'];?>
					<?php echo $thnAwal."-".$thnAkhir."/".$dtFormula['id_smt'];?>
				</td>
				<td align="right"><?php echo number_format($dtFormula['nominal_formula'],2,',','.');?></td>
				<td class="center"><?php echo $dtFormula['nm_rule'];?></td>
				<?php 
					$param="";
					if($dtFormula['id_rule']==1){
						$param=number_format($dtFormula['hard_nominal'],2,',','.');
					}elseif ($dtFormula['id_rule']==2){
						$param=$dtFormula['nm_param'];
					}elseif ($dtFormula['id_rule']==3){
						$param=number_format($dtFormula['bil_pengali'],2,',','.');
					}
				?>
				<td class="center"><?php echo $param;?></td>
				<td class="center">
					<a class="red" onclick="confirm('Apakah Anda yakin akan menghapus aturan biaya ini ? <strong><?php echo str_replace("'", "\'", $dtFormula['nm_rule']);?></strong>','<?php echo $this->baseUrl;?>','/ajax/delformulabiaya',new Array('<?php echo $dtFormula['id_angkatan'];?>','<?php echo $dtFormula['kd_prodi'];?>','<?php echo $dtFormula['id_stat_masuk'];?>','<?php echo $dtFormula['id_gelombang'];?>','<?php echo $dtFormula['id_komp'];?>','<?php echo $dtFormula['tahun_keu'];?>','<?php echo $dtFormula['id_smt'];?>','<?php echo $dtFormula['kd_status_reg'];?>'))"><i class="ace-icon fa fa-trash-o bigger-130"></i></a>
				</td>
			</tr>
			<?php $i++;}?>
			<?php }?>
		</tbody>
	</table>
	<?php } ?>
</div>
<script>
	$("#rule").change(function() {
	  var rule=$("#rule").val();
	  if(rule=='1'){
		  $("#nomfix").removeClass("hidden");
		  $("#par").removeClass("hidden").addClass("hidden");
		  $("#multiply").removeClass("hidden").addClass("hidden");
	  }else if(rule=='2'){
		  $("#nomfix").removeClass("hidden").addClass("hidden");
		  $("#par").removeClass("hidden");
		  $("#multiply").removeClass("hidden").addClass("hidden");
	  }else if(rule=='3'){
		  $("#nomfix").removeClass("hidden").addClass("hidden");
		  $("#par").removeClass("hidden").addClass("hidden");
		  $("#multiply").removeClass("hidden");
	  }else{
		  $("#nomfix").removeClass("hidden").addClass("hidden");
		  $("#par").removeClass("hidden").addClass("hidden");
		  $("#multiply").removeClass("hidden").addClass("hidden");
	  }
	});
</script>
<script>
	$("#reset").on('click',(function() {
	  $("#nomfix").removeClass("hidden").addClass("hidden");
	  $("#par").removeClass("hidden").addClass("hidden");
	  $("#multiply").removeClass("hidden").addClass("hidden");
	}));
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("[sb]").on('click',(function() {
	 ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/insformulabiaya","/biaya/detil?akt=<?php echo $this->akt;?>&prd=<?php echo $this->kdprd;?>&sm=<?php echo $this->idsm;?>&gel=<?php echo $this->idgel;?>&kom=<?php echo $this->idkom;?>&new=","u");
	 return false;
	}));
</script>