<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/plugins/select2/select2.min.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/dist/css/AdminLTE.min.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Filter</h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">Angkatan</label>
				<div class="col-sm-4">
					<select class="form-control select2" id="akt" sel-2>
						<option disabled selected value="">pilih angkatan</option>
						<?php foreach ($this->listAkt as $dt) { ?>
						<option value="<?php echo $dt['id_angkatan']?>"><?php echo $dt['id_angkatan']?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Program Studi</label>
				<div class="col-sm-4">
					<select class="form-control select2" id="prd" sel-2>
						<option disabled selected value="">pilih program studi</option>
						<?php foreach ($this->listProdi as $dt) { ?>
						<option value="<?php echo $dt['kd_prodi']?>"><?php echo $dt['nm_prodi']?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">NIM</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="nim" placeholder="klik untuk pilih mahasiswa" maxlength="20" readonly onclick="hbox('<?php echo $this->baseUrl;?>','helper/mahasiswa',new Array('nim','nm_mhs'), new Array('akt','prd'))">
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Nama Mahasiswa</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="nm_mhs" placeholder="terisi otomatis dari pilihan mahasiswa" readonly>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Periode Akademik</label>
				<div class="col-sm-4">
					<select id="per" class="form-control select2" sel-2>
						<option value="">SEMUA PERIODE</option>
						<?php foreach ($this->listPeriode as $dtPer) { ?>
						<option value="<?php echo $dtPer['kd_periode'];?>"><?php echo $dtPer['kd_periode'];?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="submit" class="btn btn-info pull-right col-sm-2">Show</button>
			</div>
		</div>
	</form>
</div>
<script src="<?php echo $this->baseUrl;?>/public/plugins/select2/select2.full.min.js"></script>
<script>
	$("[sel-2]").select2();
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/alert.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
	  	nim = $("#nim").val();
	  	if(nim==""){
	  		alertbox("Mahasiswa tidak boleh kosong");
	  	}else{
	  		ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax3/showkhs","/nilai/pkhs","s");
	  	}
	    return false;
	  });
	});
</script>