<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Filter </h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">ANGKATAN</label>
				<div class="col-sm-4">
					<select id="akt" class="form-control" name="akt">
						<?php foreach ($this->listAkt as $dataAngkatan) { ?>
						<option value="<?php echo $dataAngkatan['id_angkatan']; ?>"><?php echo $dataAngkatan['id_angkatan']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">PRODI</label>
				<div class="col-sm-4">
					<select id="prd" class="form-control" name="prd">
						<?php foreach ($this->listProdi as $dataProdi) { ?>
						<option value="<?php echo $dataProdi['kd_prodi']; ?>"><?php echo $dataProdi['kd_prodi']." : ".$dataProdi['nm_prodi']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">PERIODE AKADEMIK</label>
				<div class="col-sm-4">
					<select id="per" class="form-control" name="per">
						<?php foreach ($this->listPeriode as $dataPeriode) { ?>
						<option value="<?php echo $dataPeriode['kd_periode']; ?>"><?php echo $dataPeriode['kd_periode'];?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="submit" class="btn btn-success pull-right col-sm-4">Generate Matriks</button>
			</div>
		</div>
	</form>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
	    ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax5/showmatrixrep","/nilai/ematrix","s");
	    return false;
	  });
	});
</script>