<div class="box box-info">
	<div class="box-header with-border">
		
	</div>
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbnilai" class="table table-bordered table-hover">
				<tr>
					<th rowspan="2">No</th>
					<th rowspan="2">Mata Kuliah</th>
					<th rowspan="2">Kode</th>
					<th rowspan="2">Semester</th>
					<th rowspan="2">Dosen</th>
					<th rowspan="2">Kelas</th>
					<th colspan="<?php echo count($this->listAturan);?>">FIX</th>
					<th rowspan="2">TUNDA</th>
					<th rowspan="2">BELUM FIX</th>
					<th rowspan="2">TOTAL</th>
				</tr>
				<tr>
					<?php foreach ($this->listAturan as $dtAturan){?>
					<th><?php echo $dtAturan['indeks'];?></th>
					<?php }?>
				</tr>
				<?php $i=1; foreach ($this->listPaket as $dataPaket) { ?>
				<tr>
					<td align="center"><?php echo $i;?></td>
					<td><?php echo $dataPaket['nm_mk'];?></td>
					<td><?php echo $dataPaket['kode_mk'];?></td>
					<td align="center"><?php echo $dataPaket['smt_def'];?></td>
					<td><?php echo $dataPaket['nm_dosen'];?></td>
					<td align="center"><?php echo $dataPaket['nm_kelas']." ".$dataPaket['jns_kelas'];?></td>
					<?php $j=0;foreach ($this->listAturan as $dtAturan){?>
					<td align="center"><?php echo $dataPaket[$j];?></td>
					<?php $j++;}?>
					<td align="center"><?php echo $dataPaket['tunda'];?></td>
					<td align="center"><?php echo $dataPaket['notfix'];?></td>
					<td align="center"><?php echo ($dataPaket['fix']+$dataPaket['notfix']+$dataPaket['tunda']);?></td>
				</tr>
				<?php $i++;} ?>
			</table>
		</div>
	</div>
</div>