<div class="row">
	<div class="col-sm-6">
		<div class="col-sm-4">Program Studi</div>
		<div class="col-sm-8">: <?php echo $this->nm_prodi;?></div>
		<div class="col-sm-4">Periode Akademik</div>
		<div class="col-sm-8">: <?php echo $this->kd_per;?></div>
		<div class="col-sm-4">Nama Kelas</div>
		<div class="col-sm-8">: <?php echo $this->nm_kelas." (".$this->jns_kelas.")";?></div>
		<div class="col-sm-4">Dosen</div>
		<div class="col-sm-8">: <?php echo $this->nm_dsn;?></div>
		<div class="col-sm-4">Mata Kuliah</div>
		<div class="col-sm-8">: <?php echo $this->nm_mk." (".$this->kd_mk.") - ".$this->sks." SKS";?></div>
	</div>
</div>
<div id="frmreg" style="display:none;">
       	<form class="form-horizontal" method="post" id="frm_o">
       		<div class="box-body">
       			<div class="form-group">
       				<label class="col-sm-3 control-label no-padding-right">Approval </label>
       				<div class="col-sm-9">
       					<input type="text" id="id_prp_o" style="display:none;">
       					<select id="stat_o" class="col-xs-10 col-sm-12">
       						<option value="1" >APPROVE</option>
       						<option value="-1">REJECT</option>
       					</select>
       				</div>
       			</div>
       			<div class="form-group">
       				<label class="col-sm-3 control-label no-padding-right">Catatan </label>
       				<div class="col-sm-9">
      					<input type="text" id="ket_o" class="col-xs-10 col-sm-12">
       				</div>
       			</div>
       			<div class="clearfix form-actions">
				<div class="col-md-offset-3 col-md-9">
					<button class="btn btn-info" type="button" id="sb1"><i class="ace-icon fa fa-check bigger-110"></i>Submit</button>
					&nbsp; &nbsp; &nbsp;
					<button class="btn" type="reset" id="reset"><i class="ace-icon fa fa-undo bigger-110"></i>Reset</button>
				</div>
			</div>
       		</div>
       	</form>
</div>
<div class="box box-info">
	<div class="table-header">
		Pengajuan TA
	</div>
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbnilai" class="table table-bordered table-hover">
				<thead align="center">
					<tr>
						<th style="width:5%">NO</th>
						<th style="width:10%">NIM</th>
						<th style="width:18%">NAMA</th>
						<th style="width:12%">PEMBIMBING</th>
						<th>PERIHAL</th>
						<th style="width:12%">APPROVER</th>
						<th style="width:10%">STATUS</th>
						<th style="width:10%">LOG APPROVED</th>
						<th style="width:12%">AKSI</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=0;$x=1;foreach ($this->listPrp as $data) { ?>
					<?php if (($data['sistem']=='SIK')and($data['bagian']=='Keuangan')){ ?>
					<tr>
						<td><?php echo $x; ?></td>
						<td><?php echo $data['nim']?></a></td>
						<td><?php echo $data['nm_mhs']; ?></td>
						<td><?php echo $data['nm_dosen_pemb1']."<br>".$data['nm_dosen_pemb2']; ?></td>
						<td><?php echo $data['perihal']; ?></td>
						<td align="center"><?php echo $data['bagian']; ?></td>
						<td align="center"><?php echo $data['approved']; ?></td>
						<td align="center"><?php echo $data['approver']."(".$data['tanggal'].") Note : ".$data['note']; ?></td>
						<td align="center">
							<?php if(($data['approved']=='APPROVED')or($data['approved']=='REJECTED')){?>
							<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan membatalkan approval data ini? ','<?php echo $this->baseUrl;?>','/ajax/verifytacancel',new Array('<?php echo $data['id_prp_ujian_ta1_approver'];?>'))">Cancel</button>
							<?php }else{?>
							<?php if($data['approved']=='PENDING'){?>
							<button type="button" class="btn btn-success btn-xs" value="<?php echo $data['id_prp_ujian_ta1_approver'];?>" reg>Approval</button>
							<?php }?>
							<?php }?>
						</td>
					</tr>
					<?php $i++;$x++; } } ?>
					<input type="hidden" id="x" value="<?php echo $x;?>">
			</table>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("[reg]").on('click',(function() {
	 x=$(this).val();
	 $("#myModal").modal('show');
	 form=$("#frmreg").html();
	 $("#myModal").find('.modal-body').html("Silakan isi status approval <br>"+form);
	 $("#myModal").find("#frm_o").attr('id','frm');
	 $("#myModal").find("#id_prp_o").attr('id','id_prp');
	 $("#myModal").find("#stat_o").attr('id','stat');
	 $("#myModal").find("#sb").attr('id','sb1');
	 $("#myModal").find("#ket_o").attr('id','ket');
	 $("#sb1").on('click',(function() {
	 		$('#id_prp_o').val(x);
	 		$('#stat_o').val($("#myModal").find('#stat').val());
	 		$('#ket_o').val($("#myModal").find('#ket').val());
	   		ajaxSubmit("frm_o","<?php echo $this->baseUrl;?>","/ajax/verifyta","/verifyta/detil?id=<?php echo $this->kd_paket;?>&new=","u");
	   		return false;
	 }));
	 return false;
	}));
</script>