<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<div class="box box-info">
	<div class="box-header with-border">
		<div class="col-sm-8">
			<strong>
			PROGRAM STUDI : <?php echo $this->nm_prd; ?>
			</strong>
		</div>
		<div class="col-sm-8">
			<strong>
			SEMESTER : <?php  echo $this->smt; ?>
			</strong>
		</div>
		<div class="col-sm-8">
			<strong>
			NAMA KELAS : <?php echo $this->nm_kls; ?>
			</strong>
		</div>
		<div class="col-sm-8">
			<strong>
			MATA KULIAH : <?php echo $this->nm_mk; ?>
			</strong>
		</div>
	</div>
	<form id="frm_krs" method="post">
		<div class="box-body">
			<?php if($this->opt=='1'){ ?>
			<div class="table-responsive">
				<table class="table table-bordered table-hover">
					<tr>
						<th rowspan="2" width="4%">No</th>
						<th width="3%">
							<input type="hidden" id="prd" value="<?php echo $this->prd;?>">
							<input type="hidden" id="id_kls" value="<?php echo $this->id_kls;?>">
						</th>
						<th colspan="5">
							Data KRS SIA (<?php echo count($this->listKrsSIA) ?>)
							<button id="transfer" class="btn bg-yellow pull-right">Transfer Data KRS &gt;&gt;</button>
						</th>
						<th width="12%" colspan="4">
							Data KRS di Feeder (<?php echo count($this->listKrsFeeder['data']) ?>)
							<button type="button" id="updnilai" class="btn bg-maroon pull-right">Update Nilai</button>
						</th>
					</tr>
					<tr>
						<th><input type="checkbox" name="ckbCheckAll" id="ckbCheckAll" onClick="selectAll(this)"></th>
						<th width="12%">NIM</th>
						<th>NAMA MAHASISWA</th>
						<th width="10%">ANGKATAN</th>
						<th width="10%">NILAI ANGKA</th>
						<th width="10%">NILAI HURUF</th>
						<th width="10%">STATUS</th>
						<th><input type="checkbox" name="ckbCheckAll2" id="ckbCheckAll2" onClick="selectAll2(this)"></th>
						<th width="10%">NILAI ANGKA</th>
						<th width="10%">NILAI HURUF</th>
					</tr>
					<?php $n=1;$x=0;$y=0;foreach ($this->listKrsSIA as $dataKrsSIA ) { ?>
					<?php
						$id_reg="-";
						$status="Not Found";
						$warna="lightyellow";
						$nAFeeder="";
						$nHFeeder="";
						$nIFeeder="";
						foreach ($this->listKrsFeeder['data'] as $dataKrsFeeder) {
							if(trim($dataKrsSIA['nim'])==trim($dataKrsFeeder['nim'])){
								$id_reg = $dataKrsFeeder['id_registrasi_mahasiswa'];
								$status = "Found";
								$warna="lightgreen";
								$nAFeeder=$dataKrsFeeder['nilai_angka'];
								$nHFeeder=$dataKrsFeeder['nilai_huruf'];
								$nIFeeder=$dataKrsFeeder['nilai_indeks'];
							}
						}
						?>
					<tr bgcolor="<?php echo $warna; ?>">
						<td><?php echo $n;?></td>
						<?php if($id_reg=='-'){ ?>
						<td>
							<?php $arrIdx=explode('/', $dataKrsSIA['index']); ?>
							<input type="checkbox" id="cbkul_<?php echo $x;?>" value="<?php echo $dataKrsSIA['nim']."###".floatval($dataKrsSIA['nilai_tot'])."###".$arrIdx[0]."###".floatval($arrIdx[1]);?>" cbkul>
							<input type="text" style="display:none;" id="kul_<?php echo $x;?>">
						</td>
						<?php $x++;}else{ ?>
						<td></td>
						<?php } ?>
						<td><?php echo $dataKrsSIA['nim']; ?></td>
						<td><?php echo $dataKrsSIA['nm_mhs']; ?></td>
						<td align="center"><?php echo $dataKrsSIA['id_angkatan']; ?></td>
						<td align="center"><?php echo number_format($dataKrsSIA['nilai_tot'],1,'.',','); ?></td>
						<?php 
							$arrIdx=explode('/', $dataKrsSIA['index']);
						?>
						<td align="center"><?php echo  $dataKrsSIA['index']; ?></td>
						<?php if($id_reg=='-'){ ?>
							<td align="center">NOT FOUND</td>
							<td></td>
						<?php }else{?>
							<td align="center">FOUND</td>
							<?php if((number_format($dataKrsSIA['nilai_tot'],1,'.',',')!=$nAFeeder)or(trim($arrIdx[0])!=trim($nHFeeder)) or (trim($arrIdx[1])!=trim($nIFeeder))){?>
							<td class="btn btn-danger"><input type="checkbox" id="cbnlm_<?php echo $y;?>" value="<?php echo $id_reg."###".$dataKrsSIA['nilai_tot']."###".$arrIdx[0]."###".$arrIdx[1];?>" cbnlm><input type="text" style="display:none;" id="nlm_<?php echo $y;?>"></td>
							<?php $y++;}else{?>
							<td class="btn btn-success">OK</td>
							<?php }?>
						<?php } ?>
						<td align="center"><?php echo $nAFeeder; ?></td>
						<td align="center"><?php echo $nHFeeder."/".$nIFeeder; ?></td>
					</tr>
					<?php $n++;} ?>
				</table>
				<input type="hidden" id="x" value="<?php echo $x;?>">
				<input type="hidden" id="y" value="<?php echo $y;?>">
			</div>
			<?php }else{ ?>
			<div class="table-responsive">
				<table class="table table-bordered table-hover">
					<tr>
						<th rowspan="2" width="4%">No</th>
						<th  colspan="3" width="12%">KRS di Feeder (<?php echo count($this->listKrsFeeder) ?>)</th>
						<th width="12%">Data KRS di SIA (<?php echo count($this->listKrsSIA) ?>)</th>
					</tr>
					<tr>
						<th width="12%">NIM</th>
						<th width="10%">NILAI ANGKA</th>
						<th width="10%">NILAI HURUF</th>
						<th width="10%">STATUS</th>
					</tr>
					<?php $n=1;foreach ($this->listKrsFeeder as $dataKrsFeeder ) { ?>
					<?php
						$nim="-";
						$status="Not Found";
						$warna="lightyellow";
						foreach ($this->listKrsSIA as $dataKrsSIA) {
							if(trim($dataKrsSIA['nim'])==trim($dataKrsFeeder['nim'])){
								$nim = $dataKrsSIA['nim'];
								$status = "Found";
								$warna="lightgreen";
							}
						}
						?>
					<tr bgcolor="<?php echo $warna; ?>">
						<td><?php echo $n;?></td>
						<td><?php echo $dataKrsFeeder['nim']; ?></td>
						<td><?php echo $dataKrsFeeder['nilai_angka']; ?></td>
						<td><?php echo $dataKrsFeeder['nilai_huruf']; ?></td>
						<td align="center"><?php echo $status; ?></td>
					</tr>
					<?php $n++;} ?>
				</table>
			</div>
			<?php } ?>
			</div>
		</div>
	</form>
</div>
<script>
	$("[cbkul]").on('change',(function() {
		id=$(this).attr('id');
		n= id.split('_');
		if($(this).is(':checked')){
			$("#kul_"+n[1]).val($(this).val());
		}else{
			$("#kul_"+n[1]).val('');
		}
	}));
	$("[cbnlm]").on('change',(function() {
		id=$(this).attr('id');
		n= id.split('_');
		if($(this).is(':checked')){
			$("#nlm_"+n[1]).val($(this).val());
		}else{
			$("#nlm_"+n[1]).val('');
		}
	}));
</script>
<script>
	function selectAll(all){
		var checked = all.checked;
		var chkBoxes = $("[cbkul]");
		for (var counter=0;counter<=chkBoxes.length;counter++) {
			chkBoxes[counter].checked = checked ;
			a=chkBoxes[counter]
			id=$(a).attr('id');
			n= id.split('_');
			if($(chkBoxes[counter]).is(':checked')){
				$("#kul_"+n[1]).val($(chkBoxes[counter]).val());
			}else{
				$("#kul_"+n[1]).val('');
			}
		}
	}
	function selectAll2(all){
		var checked = all.checked;
		var chkBoxes = $("[cbnlm]");
		for (var counter=0;counter<=chkBoxes.length;counter++) {
			chkBoxes[counter].checked = checked ;
			a=chkBoxes[counter]
			id=$(a).attr('id');
			n= id.split('_');
			if($(chkBoxes[counter]).is(':checked')){
				$("#nlm_"+n[1]).val($(chkBoxes[counter]).val());
			}else{
				$("#nlm_"+n[1]).val('');
			}
		}
	}
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm_krs").submit(function() {
	  ajaxSubmit("frm_krs","<?php echo $this->baseUrl;?>","/ajax4/insfkrs","/zzfkrs/list?nm=<?php echo $this->nm_kls;?>&mk=<?php echo $this->kd_mk;?>&sm=<?php echo $this->smt;?>&prd=<?php echo $this->prd;?>&o=<?php echo $this->opt;?>&kls=<?php echo $this->kls;?>&new=","u");
	  return false;
	});
	$("#updnilai").on('click',(function() {
	  ajaxSubmit("frm_krs","<?php echo $this->baseUrl;?>","/ajax4/insfnlm","/zzfkrs/list?nm=<?php echo $this->nm_kls;?>&mk=<?php echo $this->kd_mk;?>&sm=<?php echo $this->smt;?>&prd=<?php echo $this->prd;?>&o=<?php echo $this->opt;?>&kls=<?php echo $this->kls;?>&new=","u");
	  return false;
	}));
</script>