<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/plugins/select2/select2.min.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/dist/css/AdminLTE.min.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Filter </h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">Periode Akademik</label>
				<div class="col-sm-4">
					<select id="per" class="form-control select2" data-placeholder="pilih periode" name="akt" sel-2>
						<?php foreach ($this->listPeriode as $dataPeriode) { ?>
						<option value="<?php echo $dataPeriode['kd_periode']; ?>"><?php echo $dataPeriode['kd_periode']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Program Studi</label>
				<div class="col-sm-4">
					<select id="prd" class="form-control select2" data-placeholder="pilih program studi" name="prd" sel-2>
						<?php foreach ($this->listProdi as $dataProdi) { ?>
						<option value="<?php echo $dataProdi['kd_prodi']; ?>"><?php echo $dataProdi['kd_prodi']." : ".$dataProdi['nm_prodi']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Opsi Tampilan</label>
				<div class="col-sm-4">
					<select id="opt" name="opt" class="form-control">
						<option value="1">SIA -&gt; Feeder (Transfer Data)</option>
						<option value="2">Feeder -&gt; SIA (Cek Data Feeder)</option>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="submit" class="btn btn-info pull-right col-sm-2">Search</button>
			</div>
		</div>
	</form>
</div>
<script src="<?php echo $this->baseUrl;?>/public/plugins/select2/select2.full.min.js"></script>
<script>
	$("[sel-2]").select2();
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
	    ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax4/showfkls","/zzfkls/list","s");
	    return false;
	  });
	});
</script>