<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Kurikulum</h3>
	</div>
	<div class="box-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="box-body">
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label">Kode Mata Kuliah</label>
						<div class="col-sm-8">
							<input type="hidden" id="id_mk_kur" value="<?php echo $this->id_mk_kur;?>">
							<input type="text" class="form-control" id="kd_mk" placeholder="kode mata kuliah" maxlength="20" value="<?php echo $this->kd_mk;?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Nama Mata Kuliah</label>
						<div class="col-sm-8">
							<input type="hidden" id="id_kur" value="<?php echo $this->id_kurikulum;?>">
							<input type="text" id="id_mk" style="display: none;" value="<?php echo $this->id_mk;?>">
							<input type="text" class="form-control" id="nm_mk" placeholder="kilk untuk pilih nama mata kuliah" readonly value="<?php echo $this->nm_mk;?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Jenis Mata Kuliah</label>
						<div class="col-sm-8">
							<select class="form-control" id="jns_mk">
								<option disabled value="">pilih jenis mata kuliah</option>
								<option value="0" <?php echo $this->jenis_mk0;?>>Teori Wajib</option>
								<option value="1" <?php echo $this->jenis_mk1;?>>Teori Pilihan</option>
								<option value="2" <?php echo $this->jenis_mk2;?>>Praktikum</option>
								<option value="3" <?php echo $this->jenis_mk3;?>>Tugas Akhir</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Semester</label>
						<div class="col-sm-8">
							<select class="form-control" id="smt">
								<option disabled selected value="">pilih semester</option>
								<?php for ($i=1; $i<=$this->smt_normal; $i++){ ?>
								<?php
									if($i==$this->smt_def){
									  $sel_smt="selected";
									}else{
									  $sel_smt="";
									}
									?>
								<option value="<?php echo $i;?>" <?php echo $sel_smt;?> ><?php echo $i;?></option>
								<?php } ?>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Kelompok Mata Kuliah</label>
						<div class="col-sm-8">
							<select class="form-control" id="id_kat">
								<option disabled value="">pilih kelompok mata kuliah</option>
								<?php foreach ($this->listKatMatkul as $dataKat) {?>
								<?php
									if($this->id_kat==$dataKat['id_kat_mk']){
									  $selKat="selected";
									}else{
									  $selKat="";
									}
									?>
								<option value="<?php echo $dataKat['id_kat_mk'];?>" <?php echo $selKat;?>><?php echo $dataKat['nm_kat_mk'];?></option>
								<?php } ?>
							</select>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label">SKS Tatap Muka</label>
						<div class="col-sm-8">
							<input type="number" class="form-control" id="sks_tm" placeholder="sks tatap muka" min="0" max="8" step="1" value="<?php echo $this->sks_tm;?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">SKS Praktikum</label>
						<div class="col-sm-8">
							<input type="number" class="form-control" id="sks_p" placeholder="sks praktikum" min="0" max="8" step="1" value="<?php echo $this->sks_prak;?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">SKS Pr. Lapangan</label>
						<div class="col-sm-8">
							<input type="number" class="form-control" id="sks_pl" placeholder="sks praktek lapangan" min="0" max="8" step="1" value="<?php echo $this->sks_prak_lap;?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">SKS Simulasi</label>
						<div class="col-sm-8">
							<input type="number" class="form-control" id="sks_s" placeholder="sks simulasi" min="0" max="8" step="1" value="<?php echo $this->sks_sim;?>">
						</div>
					</div>
				</div>
			</div>
			<div class="box-body">
				<div class="box-footer col-sm-6">
					<button type="submit" class="btn btn-primary pull-right col-sm-4" id="btnsbm">Simpan</button>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-4" id="btnres">Reset</button>
				</div>
			</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/updmkkur","/kurikulum/detil?id=<?php echo $this->id_kurikulum;?>&new=","u");
	  return false;
	});
</script>