 <link rel="stylesheet" href="<?php echo $this->baseUrl;?>/public/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Data Perguruan Tinggi</h3>
	</div>
	<div class="box-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="box-body">
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label">Kode PT</label>
						<div class="col-sm-8">
							<input type="hidden" id="old_kd" value="<?php echo $this->kd_pt;?>">
							<input type="text" class="form-control" id="kd_pt" placeholder="kode perguruan tinggi" maxlength="10" value="<?php echo $this->kd_pt;?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Nama PT</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="nm" placeholder="nama perguruan tinggi" maxlength="50" value="<?php echo strtoupper($this->nm_pt);?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Nama Pendek</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="nick" placeholder="nama pendek perguruan tinggi" maxlength="25" value="<?php echo strtoupper($this->nick);?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Alamat</label>
						<div class="col-sm-8">
							<textarea class="form-control" rows="2" placeholder="alamat" id="almt"><?php echo $this->alamat;?></textarea>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Kota</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="kota" placeholder="kota" maxlength="20" value="<?php echo $this->kota;?>">
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label">Email Kampus</label>
						<div class="col-sm-8">
							<input type="email" class="form-control" id="email" maxlength="40" placeholder="email" value="<?php echo $this->email;?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Website</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="web" maxlength="40" placeholder="website" value="<?php echo $this->web;?>">
						</div>
					</div>
					<div class="form-group">
					<label class="col-sm-4 control-label">Nomor Telepon</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="telp" placeholder="nomor telepon" data-inputmask='"mask": "999999999999"' data-mask value="<?php echo $this->telp;?>">
						</div>
					</div>
					<div class="form-group">
					<label class="col-sm-4 control-label">Fax</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="fax" placeholder="fax" data-inputmask='"mask": "999999999999"' data-mask value="<?php echo $this->fax;?>">
						</div>
					</div>
				</div>				
			</div>
			<div class="box-body">
				<div class="form-group">
					<label class="col-sm-2 control-label">Visi</label>
					<div class="col-sm-10">
						<textarea class="form-control"  style="width: 100%;" rows="4" placeholder="visi" id="visi"><?php echo $this->visi;?></textarea>
					</div>
				</div>
				<div class="form-group">
					<div class="box-header">
						<h3 class="box-title">MISI</h3>
		            </div>
		            <div class="box-body pad">
		            	<textarea id="misi" class="textarea" placeholder="tulis misi perguruan tinggi di sini" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"><?php echo $this->misi; ?></textarea>	
		            </div>
		        </div>
		        <div class="box-footer col-sm-12">
					<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
					<button type="submit" class="btn btn-primary pull-right col-sm-2">Simpan</button>
				</div>
			</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl?>/public/plugins/input-mask/jquery.inputmask.js"></script>
<script src="<?php echo $this->baseUrl?>/public/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
<script>
	$(function () {$("[data-mask]").inputmask();});
</script>
<script src="<?php echo $this->baseUrl;?>/public/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script>
  $(function () {
    $(".textarea").wysihtml5();
  });
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  	ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax4/updpt","/pt/index?new=","u");
	  	return false;
	});
</script>