<div class="row">
	<div class="col-lg-7">
		<div class="inqbox float-e-margins">
			<div class="inqbox-title border-top-danger">
				<h5>Pengumuman<small class="m-l-sm">Announcement</small></h5>
			</div>
			<?php if($this->listNewsFeed){?>
			<?php foreach ($this->listNewsFeed as $dtNews){?>
			<div class="inqbox-content">
				<div class="panel panel-info">
					<div class="panel-heading">
						<?php echo $dtNews['judul'] ?>
						<span class="pull-right"><?php echo $dtNews['date_created']?></span>
					</div>
					<div class="panel-body">
						<?php echo $dtNews['konten'];?>
					</div>
				</div>
			</div>
			<?php }?>
			<?php }else{?>
			<div class="inqbox-content">
				<div class="panel panel-info">
					<div class="panel-body" align="center">
						<strong>Belum ada pengumuman untuk saat ini</strong>
					</div>
				</div>
			</div>
			<?php }?>
		</div>
		<div class="inqbox float-e-margins">
			<div class="inqbox-title border-top-danger">
				<h5>Kalender Akademik <?php echo $this->per;?><small class="m-l-sm">Academic Calendar</small></h5>
			</div>
			<div class="inqbox-content">
				<div class="panel panel-info">
					<div class="table-responsive">
						<table id="tbakt" class="table table-bordered table-hover">
							<thead align="center">
								<tr>
									<th width="40%">TANGGAL</th>
									<th>AGENDA AKADEMIK</th>
								</tr>
							</thead>
							<tbody>
								<?php $i=1;foreach ($this->listKalender as $data) { ?>
								<tr>
									<td><?php echo $data['start_date_fmt']." s/d ".$data['end_date_fmt']; ?></td>
									<td><?php echo $data['deskripsi']; ?></td>
								</tr>
								<?php $i++; } ?>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-5">
		<div class="inqbox float-e-margins">
			<div class="inqbox-title border-top-danger">
				<h5>PERWALIAN <?php echo $this->per;?></h5>
				<button class="btn btn-sm btn-primary pull-right" onclick="nav('<?php echo $this->baseUrl;?>/perwalian')">Kirim Pesan</button>
			</div>
			<div class="inqbox-content">
				<div class="panel panel-primary">
					<div class="panel-body">
						<?php foreach ($this->listPerwalian as $dtPerwalian){ ?>
						<div class="social-feed-separated">
							<div class="social-avatar">
								<a href="#">
									<?php if($dtPerwalian['asal_feedback']=='M'){?>
									<img alt="image" src="<?php echo $this->baseUrl;?>/image/jpg?url=/public/file/mhs/foto/<?php echo $this->idmhs;?>.jpg" alt="Foto Mahasiswa" onerror="this.src='<?php echo $this->baseUrl;?>/image/jpg?url=/public/file/mhs/foto/default.jpg'">
									<?php }else{?>
									<img alt="image" src="<?php echo $this->baseUrl;?>/image/jpg?url=/public/file/dsn/foto/<?php echo $this->kd_dw;?>.jpg" alt="Foto Dosen" onerror="this.src='<?php echo $this->baseUrl;?>/image/jpg?url=/public/file/dsn/foto/default.jpg'">
									<?php }?>
								</a>
							</div>
							<div class="social-feed-box">
								<div class="social-avatar">
									<a><?php echo $dtPerwalian['sender']." &gt; ".$dtPerwalian['receiver']?></a>
									<small class="text-muted"><?php echo $dtPerwalian['waktu_posting'];?> - <?php echo $dtPerwalian['tanggal_posting_fmt']?></small>
								</div>
								<div class="social-body">
									<p>
										<?php echo $dtPerwalian['isi_feedback'];?>
									</p>
								</div>
							</div>
						</div>
						<?php } ?>
					</div>
				</div>
			</div>
		</div>
		<div class="inqbox float-e-margins">
			<div class="inqbox-title border-top-danger">
				<h5>Visi dan Misi <small class="m-l-sm">Vision and Mission</small></h5>
				<div class="inqbox-tools">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
				</div>
			</div>
			<div class="inqbox-content">
				<div class="panel panel-primary">
					<div class="panel-heading">
						VISI
					</div>
					<div class="panel-body" align="center">
						<i><?php echo $this->visi;?></i>
					</div>
				</div>
				<div class="panel panel-success">
					<div class="panel-heading">
						MISI
					</div>
					<div class="panel-body">
						<?php echo $this->misi;?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id=modSurv tabindex=-1 role=dialog aria-labelledby=myModalLabel aria-hidden=true>
	<div class=modal-dialog>
		<div class=modal-content>
			<div class=modal-header>
				<h4>Survey <?php echo $this->titleSurv; ?></h4>
			</div>
			<div class=modal-body>
				<div class="alert alert-info">Luangkan 1 menit untuk mengisi survey ini <i class="fa fa-smile-o"></i> </div>
				<div>
					<?php echo $this->quest;?>
				</div>
				<form class="form-horizontal" method="post" id="frm">
					<div class="form-group">
						<label class="col-sm-4 control-label">Penilaian :</label>
						<input type="hidden" id="idsurv" value="<?php echo $this->id_surv;?>">
						<input type="hidden" id="nim" value="<?php echo $this->nim;?>">
						<input type="text" id="rating" style="display:none;">
						<div class="col-sm-8">
							<div class="i-checks"><label> <input type="radio" value="1" name="rat" class="rating"> <i></i> Sangat Buruk </label></div>
							<div class="i-checks"><label> <input type="radio" value="2" name="rat" class="rating"> <i></i> Buruk </label></div>
							<div class="i-checks"><label> <input type="radio" value="3" name="rat" class="rating"> <i></i> Cukup Baik </label></div>
							<div class="i-checks"><label> <input type="radio" value="4" name="rat" class="rating"> <i></i> Baik </label></div>
							<div class="i-checks"><label> <input type="radio" value="5" name="rat" class="rating"> <i></i> Sangat Baik </label></div>
						</div>
						<label class="col-sm-4 control-label">Masukan dan Saran</label>
						<div class="col-sm-8">
							<textarea rows="6" cols="300" class="form-control" id="comm" placeholder="masukan dan saran"></textarea>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-4 col-sm-offset-3">
							<button type="submit" class="btn btn-primary" id="btnsbm">Submit</button>
							<button type="reset" class="btn btn-default" id="btnres">Reset</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
	<?php if($this->survey=="y"){?>
	$(window).load(function(){
        $('#modSurv').modal({backdrop: 'static',keyboard: false});
    });
	<?php }?>
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script>
	$("#frm").submit(function() {
	  var rating = $(".rating:checked").val();
	  $("#rating").val(rating);
	  $('#modSurv').modal('hide');
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/inssurv","/home/index?new=","u");  
	  return false;
	});
</script>