<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Data Keuangan Mahasiswa</h3>
</div>
<div class="inqbox-content">
	<div class="row">
		<h3 class="callout callout-danger"><i class="icon fa fa-exclamation-triangle"></i>&nbsp;&nbsp;Mohon maaf, Anda tidak diberikan akses ke menu ini, dikarenakan adanya tunggakan pembayaran. <br>Silakan cek status keuangan Anda di Menu Status Keuangan</h3>
	</div>
</div>