 <div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title"><?php echo $this->title; ?></h3>
	</div>
	<div class="box-body">
		<div class="col-md-6">
			<?php echo $this->info1; ?>
		</div>
		<div class="col-md-6">
			<?php echo $this->info2; ?>
		</div>
	</div>
	<div class="box-body">
		<div class="table-responsive">
		   <?php echo $this->tabel ?>	
		</div>
	</div>
</div>