<div class="row">
	<div class="col-sm-8">
		<div class="col-sm-4">Nama (NIM)</div>
		<div class="col-sm-8">: <?php echo $this->nm." (".$this->nim.")";?></div>
		<div class="col-sm-4">Program Studi</div>
		<div class="col-sm-8">: <?php echo $this->nm_prd;?></div>
		<div class="col-sm-4">Angkatan</div>
		<div class="col-sm-8">: <?php echo $this->akt;?></div>
		<div class="col-sm-4">Status Masuk</div>
		<div class="col-sm-8">: <?php echo $this->stat_msk;?></div>
		<div class="col-sm-4">Gelombang</div>
		<div class="col-sm-8">: <?php echo $this->nm_gel;;?></div>
		<div class="col-sm-4">Periode Akademik</div>
		<div class="col-sm-8">: <?php echo $this->per;?></div>
	</div>
</div>
<div>
	<form class="form-horizontal" role="form" id="frm">
		<div class="form-group">
			<input type="hidden" id="nim" value="<?php echo $this->nim;?>">
			<input type="hidden" id="per" value="<?php echo $this->per;?>">
			<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Komponen Biaya</label>
			<div class="col-sm-9">
				<select class="col-xs-10 col-sm-5" id="komp">
					<option value="" disabled="disabled" selected="selected">pilih komponen biaya</option>
					<?php foreach ($this->listKompBiaya as $dtKomp){?>
					<?php if($dtKomp['biaya_ta']=='f'){?>
					<option value="<?php echo $dtKomp['id_komp'];?>"><?php echo $dtKomp['nm_komp']?></option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Keterangan Kompensasi</label>
			<div class="col-sm-9">
				<textarea class="col-xs-10 col-sm-5" id="ket"></textarea>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Formula Pengurangan Biaya</label>
			<div class="col-sm-9">
				<select class="col-xs-10 col-sm-5" id="rule">
					<option value="" disabled="disabled" selected="selected">pilih formula pengurangan</option>
					<?php foreach ($this->listRule as $dtRule){?>
					<option value="<?php echo $dtRule['id_rule'];?>">
						<?php echo $dtRule['nm_rule'];?>
					</option>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Nominal/Parameter</label>
			<div class="col-sm-9">
				<select class="col-xs-10 col-sm-5 hidden" id="par">
					<option value="" disabled="disabled" selected="selected">pilih parameter biaya</option>
					<?php foreach ($this->listParam as $dtParam){?>
					<option value="<?php echo $dtParam['id_param'];?>">
						<?php echo $dtParam['nm_param'];?>
					</option>
					<?php }?>
				</select>
				<input type="number" id="nomfix" class="col-xs-10 col-sm-5 hidden" placeholder="nominal fix" min="-9999999999" max="10000000000" step="0.01">
				<input type="number" id="multiply" class="col-xs-10 col-sm-5 hidden" placeholder="bilangan pengali" min="0.01" max="10000000000" step="0.01">
			</div>
		</div>
		<div class="form-group hidden f-dedpar">
			<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Pengurangan Parameter</label>
			<div class="col-sm-9">
				<input type="number" id="dedpar" class="col-xs-10 col-sm-5" placeholder="pengurangan parameter" min="1" max="10" step="1">
			</div>
		</div>
		<div class="clearfix form-actions">
			<div class="col-md-offset-3 col-md-9">
				<button class="btn btn-info" type="submit"><i class="ace-icon fa fa-check bigger-110"></i>Submit</button>
				&nbsp; &nbsp; &nbsp;
				<button class="btn" type="reset" id="reset"><i class="ace-icon fa fa-undo bigger-110"></i>Reset</button>
			</div>
		</div>
	</form>
</div>
<div class="table-header">
	Daftar Kompensasi/Pengurangan Biaya Mahasiswa
</div>
<div>
	<table id="tbl" class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th class="center" width="5%" rowspan="2">No</th>
				<th class="center">Komponen Biaya</th>
				<th class="center" width="20%">Formula Pengurangan</th>
				<th class="center">Nilai Fix/Parameter</th>
				<th class="center" width="12%">Nominal</th>
				<th class="center" width="12%">Keterangan</th>
				<th class="center" width="7%">Aksi</th>
			</tr>
		</thead>
		<tbody>
			<?php $totKomp=0;$i=1;foreach ($this->listKompensasi as $dtKomp){?>
			<?php $totKomp=$totKomp+$dtKomp['nominal_kompensasi'];?>
			<tr>
				<td class="center"><?php echo $i;?></td>
				<td><?php echo $dtKomp['nm_komp'];?></td>
				<td class="center"><?php echo $dtKomp['nm_rule'];?></td>
				<td class="center">
					<?php
						if($dtKomp['id_rule']=='1'){
							echo number_format($dtKomp['hard_nominal'],2,',','.');	
						}elseif ($dtKomp['id_rule']=='2'){
							echo $dtKomp['nm_param']." (".$dtKomp['deducted_param'].")";
						}elseif ($dtKomp['id_rule']=='3'){
							echo $dtKomp['bil_pengali'];
						}
					?>
				</td>
				<td align="right"><?php echo number_format($dtKomp['nominal_kompensasi'],2,',','.');?></td>
				<td><?php echo $dtKomp['keterangan'];?></td>
				<td class="center">
					<div class="hidden-sm hidden-xs action-buttons">
						<a class="red" onclick="confirm('Apakah Anda yakin akan menghapus kompensasi biaya ini ? <strong><?php echo $dtKomp['nm_komp'];?></strong>','<?php echo $this->baseUrl;?>','/ajax/delkompensasi',new Array('<?php echo $dtKomp['nim'];?>','<?php echo $dtKomp['kd_periode'];?>','<?php echo $dtKomp['id_komp'];?>'))"><i class="ace-icon fa fa-trash-o bigger-130"></i></a>
					</div>
				</td>
			</tr>
			<?php $i++;}?>
			<tr>
				<td colspan="4"><strong>Total Kompensasi / Pengurangan</strong></td>
				<td align="right"><strong><?php echo number_format($totKomp,2,',','.');?></strong></td>
				<td colspan="2"></td>
			</tr>
		</tbody>
	</table>
</div>
<script>
	$("#rule").change(function() {
	  var rule=$("#rule").val();
	  if(rule=='1'){
		  $("#nomfix").removeClass("hidden");
		  $("#par").removeClass("hidden").addClass("hidden");
		  $("#multiply").removeClass("hidden").addClass("hidden");
		  $(".f-dedpar").removeClass("hidden").addClass("hidden");
	  }else if(rule=='2'){
		  $("#nomfix").removeClass("hidden").addClass("hidden");
		  $("#par").removeClass("hidden");
		  $("#multiply").removeClass("hidden").addClass("hidden");
		  $(".f-dedpar").removeClass("hidden");
	  }else if(rule=='3'){
		  $("#nomfix").removeClass("hidden").addClass("hidden");
		  $("#par").removeClass("hidden").addClass("hidden");
		  $("#multiply").removeClass("hidden");
		  $(".f-dedpar").removeClass("hidden").addClass("hidden");
	  }else{
		  $("#nomfix").removeClass("hidden").addClass("hidden");
		  $("#par").removeClass("hidden").addClass("hidden");
		  $("#multiply").removeClass("hidden").addClass("hidden");
		  $(".f-dedpar").removeClass("hidden").addClass("hidden");
	  }
	});
</script>
<script>
	$("#reset").on('click',(function() {
	  $("#nomfix").removeClass("hidden").addClass("hidden");
	  $("#par").removeClass("hidden").addClass("hidden");
	  $("#multiply").removeClass("hidden").addClass("hidden");
	  $(".f-dedpar").removeClass("hidden").addClass("hidden");
	}));
</script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	 ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/inskompensasi","/kompensasi/index?nim=<?php echo $this->nim;?>&per=<?php echo $this->per;?>&new=","u");
	 return false;
	});
</script>