<form class="form-horizontal" role="form" id="frm">
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> No Virtual Account * </label>
		<div class="col-sm-9">
			<input type="hidden" id="id" value="<?php echo $this->no;?>">
			<input type="text" id="no" placeholder="no virtual account" class="col-xs-10 col-sm-5" maxlength="100" value="<?php echo $this->no;?>" />
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Bank * </label>
		<div class="col-sm-9">
			<select id="bank" class="chosen-select col-xs-10 col-sm-5" data-placeholder="pilih bank" name="bank">
				<?php foreach($this->listBank as $dtBank){?>
				<?php
					$selBank="";
					if($dtBank['id_bank']==$this->bank){
						$selBank="selected='selected'";
					}
				?>
				<option value="<?php echo $dtBank['id_bank'];?>" <?php echo $selBank;?> ><?php echo $dtBank['nm_bank']." (Rek : ".$dtBank['no_rek'].")";?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<button class="btn btn-info" type="submit"><i class="ace-icon fa fa-check bigger-110"></i>Submit</button>
			&nbsp; &nbsp; &nbsp;
			<button class="btn" type="reset"><i class="ace-icon fa fa-undo bigger-110"></i>Reset</button>
		</div>
	</div>
</form>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/va/aupd","/va/list?b=f&new=","u");
	  return false;
	});
</script>