<form class="form-horizontal" role="form" id="frm">
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Bank * </label>
		<div class="col-sm-9">
			<select id="bank" class="chosen-select col-xs-10 col-sm-5" data-placeholder="pilih bank" name="bank">
				<?php foreach($this->listBank as $dtBank){?>
				<option value="<?php echo $dtBank['id_bank'];?>"><?php echo $dtBank['nm_bank']." (Rek : ".$dtBank['no_rek'].")";?></option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Template Virtual Account</label>
		<div class="col-sm-9">
			<button type="button" id="generate" class="btn btn-sm btn-success col-sm-3">Generate Template</button>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">File VA</label>
		<div class="col-sm-9">
			<input type="file" id="fileToUpload" name="fileToUpload" accept="application/vnd.ms-excel" class="col-xs-10 col-sm-5" >
		</div>
	</div>
	<div><?php echo $this->msg;?></div>
	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<button class="btn btn-info" type="button" id="upload"><i class="ace-icon fa fa-upload bigger-110"></i>Upload</button>
			&nbsp; &nbsp; &nbsp;
			<button class="btn" type="reset"><i class="ace-icon fa fa-undo bigger-110"></i>Reset</button>
		</div>
	</div>
</form>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$('#generate').on('click', function() {
	  var bank=$('#bank').val();
	  nav('<?php echo $this->baseUrl;?>/va/export?bank='+bank);
	});
</script>
<script>
	$('#upload').on('click', function() {
	  var bank=$('#bank').val();
	  ajaxUpload('fileToUpload','<?php echo $this->baseUrl;?>','/va/aupl?bank='+bank);
	});
</script>