<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">KRS Mata Kuliah TA</h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<h5 class="callout callout-info">
				<i class="icon fa fa-info-circle"></i>&nbsp;&nbsp;Apabila data tidak ditemukan, berarti mahasiswa tersebut belum melakukan registrasi akademik. Registrasikan dahulu di menu Rencana Akademik &gt; Registrasi Akademik
			</h5>
			<div class="form-group">
				<label class="col-sm-2 control-label">Angkatan</label>
				<div class="col-sm-4">
					<select class="form-control select2" id="akt">
						<option disabled selected value="">pilih angkatan</option>
						<?php foreach ($this->listAkt as $dt) { ?>
						<option value="<?php echo $dt['id_angkatan']?>"><?php echo $dt['id_angkatan']?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Program Studi</label>
				<div class="col-sm-4">
					<select class="form-control" id="prd">
						<option disabled selected value="">pilih program studi</option>
						<?php foreach ($this->listProdi as $dt) { ?>
						<option value="<?php echo $dt['kd_prodi']?>"><?php echo $dt['nm_prodi']?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">NIM</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="nim" placeholder="klik untuk pilih mahasiswa" maxlength="20" readonly onclick="hbox('<?php echo $this->baseUrl;?>','helper/mahasiswa',new Array('nim','nm_mhs'), new Array('akt','prd'))">
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Nama Mahasiswa</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="nm_mhs" placeholder="terisi otomatis dari pilihan mahasiswa" readonly>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Periode Akademik</label>
				<div class="col-sm-4">
					<select id="per" class="form-control">
						<?php foreach ($this->listPeriode as $dtPer) { ?>
						<?php
							if($this->per_aktif==$dtPer['kd_periode']){
								$sel_per="selected";
							}else{
								$sel_per="";
							}
							?>
						<option value="<?php echo $dtPer['kd_periode'];?>" <?php echo $sel_per;?> ><?php echo $dtPer['kd_periode'];?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
				<button type="submit" class="btn btn-primary pull-right col-sm-2">Search</button>
			</div>
		</div>
	</form>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/alert.js"></script>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
	  	nim = $("#nim").val();
	  	per = $("#per").val();
	  	if((nim=="")||(per=="")){
	  		alertbox("Mahasiswa tidak boleh kosong");
	  	}else{
	  		ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax3/showkrsta","/krsta/new?nim="+nim+"&per="+per+"&back=1","s");
	  	}
	    return false;
	  });
	});
</script>