<link rel="stylesheet" href="<?php echo $this->baseUrl?>/public/plugins/datatables/dataTables.bootstrap.css">
<?php //echo $this->x;?>
<?php if(!$this->per){?>
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Filter </h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">FILTER : PERIODE</label>
				<div class="col-sm-4">
					<select id="per" class="form-control data-placeholder="pilih periode akademik" name="per">
						<?php foreach ($this->listPeriode as $dataPeriode) { ?>
						<option value="<?php echo $dataPeriode['kd_periode']; ?>"><?php echo $dataPeriode['kd_periode']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">FILTER : PRODI</label>
				<div class="col-sm-4">
					<select id="prd" class="form-control data-placeholder="pilih program studi" name="prd">
						<?php foreach ($this->listProdi as $dataProdi) { ?>
						<option value="<?php echo $dataProdi['kd_prodi']; ?>"><?php echo $dataProdi['kd_prodi']." : ".$dataProdi['nm_prodi']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="submit" class="btn btn-info pull-right col-sm-2">Show</button>
			</div>
		</div>
	</form>
</div>
<?php }else{ ?>
<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">REKAP KRS TA PERIODE <?php echo $this->per;?> PRODI <?php echo $this->nm_prd;?></h3>
	</div>
	<div class="box-body">
		<div class="table-responsive">
			<table id="tbl" class="table table-bordered table-hover table-striped" style="width:2220px; table-layout:fixed;">
				<thead align="center">
					<tr align="center">
						<td width="3%">NO</td>
						<td width="8%">NIM</td>
						<td>NAMA MAHASISWA</td>
						<td width="5%">ANGKATAN</td>
						<td width="8%">MATA KULIAH</td>
						<td width="25%">JUDUL</td>
						<td width="8%">NO.REG</td>
						<td width="12%">DOSEN PEMBIMBING 1</td>
						<td width="12%">DOSEN PEMBIMBING 2</td>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;$n=1;foreach ($this->listReport as $dataRep) { ?>
					<?php 
						$nim[0]="";
						$nm[0]="";
						$akt[0]="";
					?>
					<tr>
						<td align="center"><?php echo $n; ?></td>
						<td align="center"><?php echo $dataRep['nim']; ?></td>
						<td><?php echo $dataRep['nm_mhs']; ?></td>
						<td align="center"><?php echo $dataRep['id_angkatan']; ?></td>
						<td align="center"><?php echo $dataRep['nm_mk']; ?></td>
						<td><?php echo $dataRep['judul']; ?></td>
						<td><?php echo $dataRep['no_reg']; ?></td>
						<td><?php echo $dataRep['nm_dosen_pemb1']; ?></td>
						<td><?php echo $dataRep['nm_dosen_pemb2']; ?></td>
					</tr>
					<?php $i++;$n++;} ?>
			</table>
		</div>
	</div>
</div>
<?php } ?>

<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
	    ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax5/showkrstarep","/krsta/report","s");
	    return false;
	  });
	});
</script>