<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Upload Lulusan</h3>
	</div>
	<div class="box-body">
		<div class="box-body">
			<div class="col-md-6">
				<div>
					<form class="form-horizontal" method="post" id="frm" enctype="multipart/form-data">
						<div class="box-body">
							<div class="form-group">
								<label class="col-sm-4 control-label">Template Lulusan</label>
								<div class="col-sm-8">
									<button type="button" onclick="nav('<?php echo $this->baseUrl;?>/public/file/temp_alm.xls')" class="btn btn-success col-sm-6">Generate Template</button>
								</div>
							</div>
							<div class="form-group">
								<label class="col-sm-4 control-label">File Lulusan</label>
								<div class="col-sm-8">
									<input type="file" id="fileToUpload" name="fileToUpload" accept="application/vnd.ms-excel" >
								</div>
							</div>
							<div><?php echo $this->msg;?></div>
							<div class="box-footer">
								<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
								<button type="button" id="upload" class="btn btn-primary pull-right col-sm-2">Upload</button>
							</div>
						</div>
					</form>
				</div>
				<?php
				 echo date("Y-m-d", strtotime('10/16/2003')); ?>
			</div>
			<div class="col-md-6">
				<h5 class="callout callout-info">
					<i class="icon fa fa-info-circle"></i>
					<ul>
						<li>Klik pada tombol "Generate Template" untuk mendapatkan template lulusan dalam bentuk file excel</li>
						<li>Setelah pengeditan selesai, klik tombol pilih file, kemudian cari file yang sudah diedit tadi, kemudian klik tombol upload</li>
					</ul>
				</h5>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$('#upload').on('click', function() {
	  ajaxUpload('fileToUpload','<?php echo $this->baseUrl;?>','/ajax3/uplalm');
	});
</script>