<div class="box box-info">
	<div class="box-header with-border">
		<h3 class="box-title">Filter </h3>
	</div>
	<form class="form-horizontal" method="post" id="frm">
		<div class="box-body">
			<div class="form-group">
				<label class="col-sm-2 control-label">Angkatan</label>
				<div class="col-sm-4">
					<select id="akt" class="form-control" data-placeholder="pilih angkatan" name="akt">
						<option disabled selected value="">pilih angkatan</option>
						<?php foreach ($this->listAkt as $dataAngkatan) { ?>
						<option value="<?php echo $dataAngkatan['id_angkatan']; ?>"><?php echo $dataAngkatan['id_angkatan']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Program Studi</label>
				<div class="col-sm-4">
					<select id="prd" class="form-control" data-placeholder="pilih program studi" name="prd">
						<option disabled selected value="">pilih program studi</option>
						<?php foreach ($this->listProdi as $dataProdi) { ?>
						<option value="<?php echo $dataProdi['kd_prodi']; ?>"><?php echo $dataProdi['kd_prodi']." : ".$dataProdi['nm_prodi']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Periode Akademik</label>
				<div class="col-sm-4">
					<select id="per" class="form-control" data-placeholder="pilih status mahasiswa" name="per">
						<option disabled selected value="">pilih periode akademik</option>
						<?php foreach ($this->listPeriode as $dataPer) { ?>
						<option value="<?php echo $dataPer['kd_periode']; ?>"><?php echo $dataPer['kd_periode']; ?></option>
						<?php } ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Jenis Ujian</label>
				<div class="col-sm-4">
					<select id="jns" class="form-control  data-placeholder="pilih status mahasiswa" name="stat" sel-2>
						<option value="1">UJIAN TENGAH SEMESTER (UTS)</option>
						<option value="2">UJIAN AKHIR SEMESTER (UAS)</option>
					</select>
				</div>
			</div>
			<div class="box-footer col-sm-6">
				<button type="reset" class="btn btn-default pull-left col-sm-2">Reset</button>
				<button type="submit" class="btn btn-primary pull-right col-sm-4">Download Kartu Ujian</button>
			</div>
		</div>
	</form>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	  $("#frm").submit(function() {
		akt = $("#akt").val();
		per = $("#per").val();
		prd = $("#prd").val();
		jns = $("#jns").val();
	    nav('<?php echo $this->baseUrl;?>/ujian/excel?akt='+akt+'&per='+per+'&prd='+prd+'&jns='+jns);
	    return false;
	  });
	});
</script>