<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Data Materi Ajar</h3>
</div>
<div class="inqbox-content">
	<div class="panel panel-primary">
		<div class="panel-body">
			<div class="col-sm-4">Program Studi</div>
			<div class="col-sm-8">: <?php echo $this->nm_prodi;?></div>
			<div class="col-sm-4">Periode Akademik</div>
			<div class="col-sm-8">: <?php echo $this->kd_per;?></div>
			<div class="col-sm-4">Jenis Kelas</div>
			<div class="col-sm-8">: <?php echo $this->jns_kelas;?></div>
			<div class="col-sm-4">Dosen</div>
			<div class="col-sm-8">: <?php echo $this->nm_dsn." (".$this->kd_dsn.")";?></div>
			<div class="col-sm-4">Mata Kuliah</div>
			<div class="col-sm-8">: <?php echo $this->nm_mk." (".$this->kd_mk.") - ".$this->sks." SKS";?></div>
		</div>
	</div>
	<div class="panel-body">
		<form class="form-horizontal" method="post" id="frm">
			<div class="col-md-12">
				<div class="form-group">
					<label class="col-sm-2 control-label">Minggu</label>
					<div class="col-sm-10">
						<input type="hidden" id="kd_kelas" value="<?php echo $this->kd_kls;?>">
						<select class="form-control" id="rps">
							<?php foreach($this->listRps as $dtRps){ ?>
							<option value="<?php echo $dtRps['id_rps_detil'];?>">(<?php echo $dtRps['minggu'];?>) <?php echo substr($dtRps['kemampuan_akhir'],0,40);?></option>
							<?php } ?>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Judul Bahan Ajar</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="jdl" placeholder="judul bahan ajar">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Keterangan</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="ket" placeholder="keterangan">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Link (Opsional)</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="link" placeholder="link">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">File Materi (*.pdf, *.doc/x, *.xls/x, *.ppt/x) : Max : 20 Mb</label>
					<div class="col-sm-10">
						<input type="file" id="file2" name="file2" accept="application/pdf, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-powerpoint,  application/vnd.openxmlformats-officedocument.presentationml.presentation" required="required">
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="box-footer col-sm-6">
					<button type="submit" class="btn btn-primary pull-right col-sm-4" id="btnsbm">Tambah</button>
				</div>
				<div class="box-footer col-sm-6">
					<button type="reset" class="btn btn-default pull-left col-sm-4" id="btnres">Reset</button>
				</div>
			</div>
		</form>
	</div>
	<div class="table-responsive">
		<table id="tbkls" class="table table-bordered table-hover">
			<thead align="center">
				<tr>
					<th width="5%">NO</th>
					<th width="8%">MINGGU</th>
					<th>JUDUL</th>
					<th width="35%">MATERI</th>
					<th width="20%">KONTRIBUTOR</th>
					<th width="10%">AKSI</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=1;foreach ($this->listBahan as $dataBhn) { ?>
				<tr>
					<td><?php echo $i; ?></td>
					<td><?php echo $dataBhn['minggu']; ?></td>
					<td><?php echo $dataBhn['judul_bahan_ajar']; ?></td>
					<td>
						<strong>Keterangan</strong> : <?php echo $dataBhn['keterangan']; ?><br>
						<strong>Nama File</strong> : <?php echo $dataBhn['nm_file']; ?><br>
						<strong>Link</strong> : <a href="<?php echo $dataBhn['link']; ?>"><?php echo $dataBhn['link']; ?></a>
					</td>
					<td align="center">
						<?php echo $dataBhn['nm_dosen']." (".$dataBhn['created'].")"; ?>
					</td>
					<td align="center">
						<?php 
            					    $arrFile=explode(".",$dataBhn['nm_file']);
        	    				    $ext=end($arrFile);
	            				?>
						<button type="button" class="btn btn-info btn-sm" onclick="nav('<?php echo $this->baseUrl;?>/image/anyfile?url=public/file/materi/<?php echo $dataBhn['id_bahan_ajar'].".".$ext?>&newname=<?php echo $dataBhn['nm_file'];?>')"><i class="fa fa-download"></i></button>
						<button type="button" class="btn btn-danger btn-xs" onclick="confirm('Apakah Anda yakin akan menghapus data ini? ','<?php echo $this->baseUrl;?>','/ajax/delbahan',new Array('<?php echo $dataBhn['id_bahan_ajar'];?>'))"><i class="fa fa-remove"></i></button>
					</td>
				</tr>
				<?php $i++; } ?>
		</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form2.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmitUpload("frm",["file2"],"","/ajax/insbahan","/materi/index?id=<?php echo $this->kd_kls;?>&bb=&new=","u");
	  return false;
	});
</script>