<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title><?php echo $this->title;?></title>
      <link rel="shortcut icon" href="<?php echo $this->baseUrl;?>/image/png?url=public/img/logo.png">
      <link href="<?php echo $this->baseUrl;?>/public/css/bootstrap.min.css" rel="stylesheet">
      <link href="<?php echo $this->baseUrl; ?>/public/fonts/font-awesome/css/font-awesome.css" rel="stylesheet">
      <link href="<?php echo $this->baseUrl;?>/public/css/animate.css" rel="stylesheet">
      <link href="<?php echo $this->baseUrl;?>/public/css/style.css" rel="stylesheet">
   </head>
   <body background="<?php echo $this->baseUrl;?>/image/png?url=public/img/bg3.png">
      <div class="loginColumns animated fadeInDown">
         <div class="row">
            <div class="col-md-6" style="color:white">
               <h1 class="font-bold">PORTAL DOSEN</h1>
               <h2 class="font-bold"><?php echo $this->nm_pt;?></h2>
               <p>
               	 <strong>PORTAL DOSEN</strong> adalah salah satu layanan akademik yang diberikan kepada dosen atau tenaga pengajar di lingkungan <?php echo $this->nm_pt; ?> 
               	 guna memberikan akses terhadap informasi serta menyediakan data-data yang diperlukan oleh Bagian akademik secara online dan dapat diakses <i>anywhere and anytime</i>   
               </p>
               <p>
                  Silakan login untuk menuju halaman <i>dashboard</i> Portal Dosen untuk melakukan akses informasi. Apabila Anda tidak dapat melakukan login, silakan hubungi bagian Akademik.
               </p>
            </div>
            <div class="col-md-6">
               <div class="inqbox-content">
                  <form class="m-t"  method="post">
                     <div class="col-sm-9 pull-right"><img src="<?php echo $this->baseUrl;?>/image/png?url=public/img/logo.png" width="100px"><br><br></div>
                     <div class="form-group">
                        <input type="text" name="txtUsername" class="form-control" placeholder="Username" required="" autofocus="autofocus">
                     </div>
                     <div class="form-group">
                        <input type="password" name="txtPass" class="form-control" placeholder="Password" required="">
                     </div>
                     <div>
						<label><?php echo $this->message; ?></label>
					 </div>
                     <input type="submit" class="btn btn-primary block full-width m-b" value="Login">
                     <a href="#">
                     	<small>Forgot password?</small>
                     </a>
                  </form>
               </div>
            </div>
         </div>
         <hr/>
         <div class="row">
            <div class="col-md-6" style="color:white">
            	<?php echo $this->nm_pt; ?>
            </div>
            <div class="col-md-6 text-right" style="color:white">
               <small><?php echo $this->nickname;?> &copy; 2016</small>
            </div>
         </div>
      </div>
   </body>
</html>