 <div class="inqbox float-e-margins">
 	<div class="inqbox-title border-top-success">
 		<h5>Data Password</h5>
 	</div>
 	<div class="inqbox-content">
 		<form method="post" id="frm" class="form-horizontal"> 
 			<div class="form-group">
 				<label class="col-sm-3 control-label">Password Lama</label>
 				<div class="col-sm-4">
 					<input type="hidden" id="e_old">
 					<input type="password" id="old_pwd" class="form-control">
 				</div>
 			</div>
 			<div class="form-group">
 				<label class="col-sm-3 control-label">Password Baru</label>
 				<div class="col-sm-4">
 					<input type="password" id="new_pwd1" class="form-control">
 				</div>
 			</div>
 			<div class="form-group">
 				<label class="col-sm-3 control-label">Ketik Lagi Password Baru</label>
 				<div class="col-sm-4">
 					<input type="password" id="new_pwd2" class="form-control">
 				</div>
 			</div>
 			<div class="hr-line-dashed"></div>
 			<div class="form-group">
 				<div class="col-sm-4 col-sm-offset-3">
 					<button class="btn btn-white" type="reset">Batal</button>
 					<button class="btn btn-primary" type="submit">Simpan Password</button>
 				</div>
 			</div>
 		</form>
 	</div>
</div>
<script src="<?php echo $this->baseUrl;?>/public/js/custom/form.js"></script>
<script>
	$("#frm").submit(function() {
	  ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/updpwd","/profil/password?new=","u");
	  return false;
	});
</script>