<div class="row">
	<div class="col-sm-8">
		<div class="col-sm-4">Program Studi</div>
		<div class="col-sm-8">: <?php echo $this->prd;?></div>
		<div class="col-sm-4">Angkatan</div>
		<div class="col-sm-8">: <?php echo $this->akt;?></div>
		<div class="col-sm-4">Status Masuk</div>
		<div class="col-sm-8">: <?php echo $this->sm;?></div>
		<div class="col-sm-4">Gelombang</div>
		<div class="col-sm-8">: <?php echo $this->gel;?></div>
		<div class="col-sm-4">Status Registrasi</div>
		<div class="col-sm-8">: <?php echo $this->stat;?></div>
		<div class="col-sm-4">Periode Akademik</div>
		<div class="col-sm-8">: <?php echo $this->per;?></div>
	</div>
</div>
<div class="table-header">Komponen Biaya Periodik</div>
<form class="form-horizontal" role="form" id="frm">
	<table class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th class="center" width="5%">No</th>
				<th class="center" width="20%">Komponen Biaya</th>
				<th class="center">Formula</th>
				<th class="center" width="15%">Nominal/Parameter</th>
				<th class="center" width="5%">Urutan</th>
			</tr>
		</thead>
		<tbody>
			<?php $i=1;foreach ($this->listFormula as $dtFormula) { ?>
			<tr>
				<td class="center"><?php echo $i;?></td>
				<td class="center"><?php echo $dtFormula['nm_komp'];?></td>
				<td class="center"><?php echo $dtFormula['nm_rule'];?></td>
				<?php 
					$param="";
					if($dtFormula['id_rule']==1){
						$param=number_format($dtFormula['hard_nominal'],2,',','.');
					}elseif ($dtFormula['id_rule']==2){
						$param=$dtFormula['nm_param'];
					}elseif ($dtFormula['id_rule']==3){
						$param=number_format($dtFormula['bil_pengali'],2,',','.');
					}
				?>
				<td class="center"><?php echo $param;?></td>
				<td class="center">
					<input type="number" class="col-sm-12" value="<?php echo $dtFormula['urutan_komp'];?>" id="order_<?php echo $i;?>" min="0" max="<?php echo count($this->listFormula)?>">
					<input type="hidden" id="komp_<?php echo $i;?>" value="<?php echo $dtFormula['id_komp'];?>">
				</td>
			</tr>
			<?php $i++;}?>
		</tbody>
	</table>
	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<input type="hidden" id="n" value="<?php echo $i;?>">
			<input type="hidden" id="akt" value="<?php echo $this->akt;?>">
			<input type="hidden" id="prd" value="<?php echo $this->kdprd;?>">
			<input type="hidden" id="sm" value="<?php echo $this->idsm;?>">
			<input type="hidden" id="gel" value="<?php echo $this->idgel;?>">
			<input type="hidden" id="thn" value="<?php echo $this->thn;?>">
			<input type="hidden" id="smt" value="<?php echo $this->smt;?>">
			<input type="hidden" id="reg" value="<?php echo $this->reg;?>">
			<button class="btn btn-info" type="submit" id="sb"><i class="ace-icon fa fa-check bigger-110"></i>Submit</button>
			&nbsp; &nbsp; &nbsp;
			<button class="btn" type="reset"><i class="ace-icon fa fa-undo bigger-110"></i>Reset</button>
		</div>
	</div>
</form>
<script src="<?php echo $this->baseUrl;?>/public/js/form.js"></script>
<script>
	$("#sb").on('click',(function() {
	 ajaxSubmit("frm","<?php echo $this->baseUrl;?>","/ajax/updfbiaya","/fbiaya/detil?akt=<?php echo $this->akt;?>&prd=<?php echo $this->kdprd;?>&sm=<?php echo $this->idsm;?>&gel=<?php echo $this->idgel;?>&per=<?php echo $this->per;?>&reg=<?php echo $this->reg;?>&new=","u");
	 return false;
	}));
</script>