						</div>
					</div>
                </div>
				<div class="footer">
               		<div class="pull-right">
                  		Bag.Layanan Akademik
               		</div>
               	<div>
               		<strong><?php echo $this->nm_pt;?> &copy; 2015-2016
               	</div>
            	</div>     
            	<div id=loader style=display:none><img id=loadingbar src=<?php echo $this->baseUrl;?>/public/img/loading.gif></div>           
            </div>
            <script src="<?php echo $this->baseUrl; ?>/public/js/plugins/metisMenu/jquery.metisMenu.js"></script>
       		<script src="<?php echo $this->baseUrl; ?>/public/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    </body>
</html>