<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl;?>/public/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
<div class="inqbox-title border-top-danger">
	<h3 class="box-title">Daftar Kelas (Online Learning)</h3>
</div>
<div class="inqbox-content">
	<div class="table-responsive">
		<h5 class="alert alert-info">
		<i class="icon fa fa-info-circle"></i>
		<ul>
			<li>Klik tombol berisi <button class="btn btn-primary btn-xs">Angka</button> di kolom Materi Ajar untuk mengunggah Materi untuk dapat diakses seluruh peserta didik di kelas</li>
			<li>Untuk memulai membuat diskusi, tugas klik <button class="btn btn-primary btn-xs"><i class="fa fa-gear"></i></button> pada kolom Online Learning</li>
		</ul>
		</h5>
		<h5>Sebagai Dosen Penanggung Jawab</h5>
		<table id="tbkls" class="table table-bordered table-hover">
			<thead align="center">
				<tr>
					<th>NO</th>
					<th>SMT</th>
					<th>KODE MK</th>
					<th>NAMA MK</th>
					<th>NAMA DOSEN PJ</th>
					<th>PAKET KELAS</th>
					<th>TIM TEACHING</th>
					<th>MATERI AJAR</th>
					<th width="10%">ONLINE LEARNING</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=1;foreach ($this->listKelas as $dataKls) { ?>
				<tr>
					<td><?php echo $i; ?></td>
					<td align="center"><?php echo $dataKls['smt_def'];?></td>
					<td><?php echo $dataKls['kode_mk']; ?></td>
					<td><?php echo $dataKls['nm_mk']; ?></td>
					<td><?php echo $dataKls['nm_dosen']; ?></td>
					<td align="center"><?php echo $dataKls['n_paket_kelas'];?></td>
					<td align="center"><?php echo $dataKls['n_tim_teaching'];?></td>
					<td align="center">
						<button type="button" class="btn btn-primary btn-xs" onclick="nav('<?php echo $this->baseUrl?>/materi/index?id=<?php echo $dataKls['kd_kelas']; ?>')"><?php echo $dataKls['n_bahan_ajar'];?></button>
					</td>
					<td align="center">
						<button type="button" class="btn btn-primary btn-xs" onclick="nav('<?php echo $this->baseUrl?>/lms/detil?id=<?php echo $dataKls['kd_kelas']; ?>')"><i class="fa fa-gear"></i></button>
					</td>
				</tr>
				<?php $i++; } ?>
		</table>
		<h5>Sebagai Dosen Tim Teaching</h5>
		<table id="tbkls" class="table table-bordered table-hover">
			<thead align="center">
				<tr>
					<th>NO</th>
					<th>SMT</th>
					<th>KODE MK</th>
					<th>NAMA MK</th>
					<th>NAMA DOSEN PJ</th>
					<th>MATERI AJAR</th>
					<th width="5%">LMS</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=1;foreach ($this->listKelasTt as $dataKls) { ?>
				<tr>
					<td><?php echo $i; ?></td>
					<td align="center"><?php echo $dataKls['smt_def'];?></td>
					<td><?php echo $dataKls['kode_mk']; ?></td>
					<td><?php echo $dataKls['nm_mk']; ?></td>
					<td><?php echo $dataKls['nm_dosen_pj']; ?></td>
					<td align="center">
						<button type="button" class="btn btn-primary btn-xs" onclick="nav('<?php echo $this->baseUrl?>/materi/index?id=<?php echo $dataKls['kd_kelas']; ?>')"><i class="fa fa-eye"></i></button>
					</td>
					<td align="center">
						<button type="button" class="btn btn-primary btn-xs" onclick="nav('<?php echo $this->baseUrl?>/lms/detil?id=<?php echo $dataKls['kd_kelas']; ?>')"><i class="fa fa-gear"></i></button>
					</td>
				</tr>
				<?php $i++; } ?>
		</table>
	</div>
</div>